### PR TITLE
Fix ofxPanel disable header

### PR DESCRIPTION
**Pull request by roymacdonald**
I've made several improvements to ofxGuiGroup and ofxPanel, which address https://github.com/openframeworks/openFrameworks/issues/6470 and https://github.com/openframeworks/openFrameworks/issues/6145.

I removed a lot of redundant code for setting the position of the gui elements, and replaced for a single function, this way the behavior is easier to understand, less bug prone and looks better as well. :)

### CODE REVIEW

**Comment by roymacdonald** [comment]
I was using the following code for testing.
`ofApp.h`
```
#pragma once

#include "ofMain.h"
#include "ofxGui.h"

class ofApp : public ofBaseApp{
	
public:
	void setup();
	void draw();
	void drawGui();	
	
	void keyReleased(int key);


	ofParameter<float> radius;
	ofParameter<ofColor> color;
	ofParameter<ofVec2f> center;
	ofParameter<int> circleResolution;
	ofParameter<bool> filled;
	ofParameter<string> screenSize;

    ofParameterGroup params;
    ofParameterGroup params1;
    ofParameterGroup params2;

    ofxPanel gui, gui2;
	
	ofParameter<float> spacing = {"spacing", 1, 0, 100};
	ofParameter<float> spacingNext = {"spacing next", 3, 0, 300};
	ofParameter<float> childrenLeftIndent = {"children Left Indent", 4, 0, 200};
	ofParameter<float> childrenRightIndent = {"children Right Indent", 0, 0, 200};
	
	void spacingChanged(float&);
	ofEventListeners listeners;
	
};

```
`ofApp.cpp`

```
#include "ofApp.h"


//--------------------------------------------------------------
void ofApp::setup()
{
	//customization1
//	    ofxGuiSetFont(OF_TTF_SERIF, 27);
	//    ofxGuiSetDefaultHeight(18);
	//    ofxGuiSetBorderColor(16);
	//    ofxGuiSetFillColor(ofColor(48));
	//    ofxGuiSetTextColor(ofColor::white);
	//    ofxGuiSetHeaderColor(ofColor(32));
	ofxGuiEnableHiResDisplay();
	gui.setup("panel"); // most of the time you don't need a name but don't forget to call setup
	
	params.setName("Params");
	params1.setName("params1");
	params2.setName("params2");
	
	params1.add(filled.set("bFill", true));
	params1.add(radius.set("radiusq", 140, 10, 300));
	params1.add(center.set("center", ofVec2f(ofGetWidth() * .5, ofGetHeight() * .5), ofVec2f(0, 0), ofVec2f(ofGetWidth(), ofGetHeight())));
	
	params2.add(color.set("color", ofColor(100, 100, 140), ofColor(0, 0), ofColor(255, 255)));
	params2.add(circleResolution.set("circleRes", 5, 3, 90));
	
	params.add(screenSize.set("screenSize", ""));
	params2.add(params1);
	params.add(params2);
	gui.add(params);
	
	gui.setPosition(50, 300);
	
	//customization2
	//    gui.disableHeader();
	//    gui.getGroup("params1").minimize();

	gui2.setup();
	gui2.add(spacing);
	gui2.add(spacingNext);
	gui2.add(childrenLeftIndent);
	gui2.add(childrenRightIndent);
	listeners.push(spacing.newListener(this, &ofApp::spacingChanged));
	listeners.push(spacingNext.newListener(this, &ofApp::spacingChanged));
	listeners.push(childrenLeftIndent.newListener(this, &ofApp::spacingChanged));
	listeners.push(childrenRightIndent.newListener(this, &ofApp::spacingChanged));
	
}
//--------------------------------------------------------------
void ofApp::spacingChanged(float&){
	ofxGuiGroup::elementSpacing = spacing;
	ofxGuiGroup::groupSpacing = spacingNext;
	ofxGuiGroup::childrenLeftIndent = childrenLeftIndent;
	ofxGuiGroup::childrenRightIndent = childrenRightIndent;
	gui.sizeChangedCB();
	
}
//--------------------------------------------------------------
void ofApp::drawGui(){
	
}
//--------------------------------------------------------------
void ofApp::draw()
{
	ofBackgroundGradient(ofColor::white, ofColor::gray);
	
	filled?ofFill():ofNoFill();
	
	ofSetColor(color);
	ofDrawCircle((ofVec2f) center, radius);
	gui.draw();
	
		
	gui2.draw();

		
}
//--------------------------------------------------------------
void ofApp::keyReleased(int key){
	if(key == '1'){
		auto & g = gui.getGroup("params");
		if(g.isMinimized()){
			g.maximize() ;
		}else{
			g.minimize();
		}
	}else if(key == '2'){
		auto & g = gui.getGroup("params");
		if(g.isHeaderEnabled()){
			g.disableHeader();
		}else{
			g.enableHeader();
		}
	}else if(key == '3'){
		if(gui.isMinimized()){
			gui.maximize() ;
		}else{
			gui.minimize();
		}
	}else if(key == '4'){
		if(gui.isHeaderEnabled()){
			gui.disableHeader();
		}else{
			gui.enableHeader();
		}
	}else if(key == '5'){
		auto & g = gui.getGroup("params1");
		g.setup("params1");
		if(g.isMinimized()){
			g.maximize() ;
		}else{
			g.minimize();
		}
	}
}

```

@arturoc @ofZach @ofTheo can you take a look please?

**Comment by roymacdonald** [comment]
This is how it was before
Screen Shot 2019-11-29 at 20 08 14
This is how it looks after the changes
Screen Shot 2019-11-29 at 20 06 33

Besides reducing the code base, this fixes the positioning of elements and gives control over the left and right indents of groups element spacing and group spacing. Also the text now is rendered properly centered, both for `ofBitmapFont` and `ofTrueTypeFont`. Previously the indenting of groups was done using a percentage of the with of the parent group, which led to a quite large indent when making the gui wider, over which there was no control. Now the indent is simply based on a static value representing the indent in pixels.

**Comment by moebiussurfing** [comment]
cool @roymacdonald !
i am not sure if I am doing something bad, but I get:
```
/openFrameworks/apps/_TEST/guiFromParametersExampleTEST/src/ofApp.cpp:115:18: No member named 'elementSpacing' in 'ofxGuiGroup'
/openFrameworks/apps/_TEST/guiFromParametersExampleTEST/src/ofApp.cpp:116:18: No member named 'groupSpacing' in 'ofxGuiGroup'
/openFrameworks/apps/_TEST/guiFromParametersExampleTEST/src/ofApp.cpp:117:5: No member named 'childrenLeftIndent' in 'ofxGuiGroup'; did you mean simply 'childrenLeftIndent'?
/openFrameworks/apps/_TEST/guiFromParametersExampleTEST/src/ofApp.h:56:24: 'childrenLeftIndent' declared here
/openFrameworks/apps/_TEST/guiFromParametersExampleTEST/src/ofApp.cpp:118:5: No member named 'childrenRightIndent' in 'ofxGuiGroup'; did you mean simply 'childrenRightIndent'?
```

> $ git checkout
> Your branch is up to date with 'github-desktop-roymacdonald/fix-ofxPanelDisableHeader'.
>

**Comment by moebiussurfing** [comment]
oops sorry, I had another OF folder, sorry. I chack and back...

**Comment by moebiussurfing** [comment]
yes, it works. here's how it looks here:

Screen Shot 2019-11-29 at 23 02 40

**Comment by moebiussurfing** [comment]
thanks @roymacdonald, tell me if you want that I check some other thing about it

**Comment by moebiussurfing** [comment]
just in case this is not expected...

when starting it looks:
Screen Shot 2019-11-29 at 23 58 46

then when pressing keys 5,4 etc:
Screen Shot 2019-11-29 at 23 59 33

another group appears below but looks like empty:
Screen Shot 2019-11-30 at 00 01 39

**Comment by roymacdonald** [comment]
Hi @moebiussurfing THnaks for checking. That empty panel that appears is there for testing this edge case that you try to get a group that does not exist which is created automatically. we discussed it in the issue you posted.

**Comment by roymacdonald** [comment]
Hey @ofTheo and @arturoc what's needed to get this PR merged? There are several different improvements on this single RP, shall I make separate PRs for each one of these instead of this PR??

**Comment by ofTheo** [comment]
I think its probably good to merge. I'll let @arturoc confirm but from what I can tell np on my end. 
If we find any issues before 0.12 it will be easier to fix if in master.

**Comment by roymacdonald** [comment]
I've been using a lot and see no issues. It is just a bunch of aesthetic changes and small optimizations.

**Comment by arturoc** [comment]
Cant really say from the code since it's a big change but yeah since it goes to master let's just merge it so others can test it

**Pull request merged**
