### PR TITLE
Apothecary - iOS Boost 1.58.0 static library for Filesystem, System

### PR DESCRIPTION
**Pull request by danoli3**
This PR includes the static libraries for boost for iOS Boost 1.58.0 Filesystem, System (arm64, armv7, i386, x86_64)

https://github.com/openframeworks/openFrameworks/issues/3926

### CODE REVIEW

**Comment by arturoc** [comment]
do you have any changes for the apothecary formula?

**Comment by danoli3** [comment]
@arturoc yeah right here: https://github.com/openframeworks/openFrameworks/commit/e97ff6303538d3773d61d63eceeee69609b42f94

**Comment by danoli3** [comment]
I'm just about to test all these iOS Static libs together and PR the changes to the xconfig

**Comment by arturoc** [comment]
ok, perfect, feel free to merge it whenever you are done with it

**Comment by Miles-Tone** [comment]
Hi there, i think this goes here...

Im getting these errors when trying to compile the of_v20150617_ios_nightly

screen shot 2015-06-17 at 09 55 01

**Comment by arturoc** [comment]
yes, the ios projects are surely broken right now since they are missing this includes

**Comment by Miles-Tone** [comment]
ah ok, thanks Arturo
I wish i was learned enough to help. Maybe ill be experienced enough when 1.0 is being made to be useful.
I'll keep my eyes on the nightly builds

**Comment by danoli3** [comment]
The iOS Boost libs in this PR are not linking correctly. Re-looking at the script to define why it thinks they are for OSX.

**Comment by arturoc** [comment]
i think i added a check for type==osx and type==ios in this scripts but i never implemented the ios part, i can look into it if you want

**Comment by danoli3** [comment]
Yeah that's all working. It was just when at the symbolic link stage in the openFrameworks lib build it was saying that the simulator architectures x86_64 and i386 where built for OS X not iOS... 

I've had a look at my other iOSBoost script and there was one stage I missed where I am decomposing the built architecture in the build directory and re-structuring it using the correct Apple iPhoneOS or iPhoneSimulator located ```ar crus```. Seems to do the stick (this only seems to apply for Boost as well due to bjam).

**Pull request closed without merging**
