### PR TITLE
Fix typo in makefiles

### PR DESCRIPTION
**Pull request by sjltaylor**
`OUPUT` is corrected to `OUTPUT` in all misspelt cases in the project make files.

### CODE REVIEW

**Comment by sjltaylor** [comment]
oF and examples projects build successfully on Debian 8.1 x86_64

**Comment by bakercp** [comment]
This looks good.  Let's let CI do it's magic and see what happens!

**Comment by sjltaylor** [comment]
oh, the compiler died. how can we kick-off a rebuild?

**Comment by bakercp** [comment]
Theoretically you should be able to log onto travis and hit the refresh button (click through details and it should show up there ...).  That said, there have been some issues with CI lately and @bilderbuchi et al are working on getting them up and running smoothly again..

**Comment by sjltaylor** [comment]
no refresh button for me

**Comment by arturoc** [comment]
i'm going to merge it since it seems the OF library build without problem

**Comment by bakercp** [comment]
Nice catch @sjltaylor . Thanks!

**Comment by bilderbuchi** [comment]
You see that refresh button if you are logged in @ Travis and have push rights to the repo. Probably best to just ask someone from the team to rebuild

**Pull request merged**
