### PR TITLE
trigonometricMotionExample README

### PR DESCRIPTION
**Pull request by frauzufall**
* adds README
* converts some spaces into tabs

Another example where it would be nice if someone can tell me if my explanations are understandable.

### CODE REVIEW

**Comment by frauzufall** [comment]
ping @roymacdonald

**Comment by roymacdonald** [comment]
Hi, nice you added this :)
I think that it is quite clear.
Just one correction.

Where it says "The resulting line visualizes the history of these two frequencies, the left frequency controlling the vertical position of the line points, the top frequency controlling the horizontal positions."
I'd change frequency/frequencies for waves or oscillations

best!
BTW: are you doing this in the documentation sprint in Denver?

**Comment by bakercp** [comment]
@frauzufall take a look at @roymacdonald 's feedback and we can merge.

**Comment by frauzufall** [comment]
Thanks, @roymacdonald! Yes, I am in Denver :)

**Comment by bakercp** [comment]
Thanks!

**Pull request merged**
