### PR TITLE
current platform list

### PR DESCRIPTION
**Pull request by tpltnt**
Hi,

i created/updated document to address (and solve?) #3506. Somehow it has a bunch of unrelated are associated, but i resolved all merge conflicts.

Cheers,
tpltnt

### CODE REVIEW

**Comment by oxillo** [comment]
Thank you for this great work. 
Just one change : in the windows section, there is still some reference to mingw/codeblocks. I think it should be replaced by MSYS2.

**Comment by tpltnt** [comment]
@oxillo there is still a codeblocks tutorial for windows in the docs-folder. I added your hint about MSYS2.

**Comment by kylemcdonald** [comment]
hmm this still looks like it has a ton of extra commits.

i usually do something like this when things go wrong (assuming your remotes are named `origin` and `upstream`):

```
cd openFrameworks
git checkout master
git fetch upstream
git reset --hard upstream/master
git push origin master --force
```

Then your master branch should be in sync with the openFrameworks master branch. Then you can do this:

```
git checkout -b feature-issue-3506
# make your changes
git add .
git commit -m "updated platforms.md"
git push origin feature-issue-3506
```

Then submit the PR, which should have only one commit.

Hope that helps!

**Comment by tpltnt** [comment]
@kylemcdonald thanks for pointing out the reset. I did not do that, but the rest is identical to my (previous) steps. I will submit a new PR.

**Pull request closed without merging**
