### PR TITLE
Test removing GLUT window

### PR DESCRIPTION
**Pull request by NickHardeman**

### CODE REVIEW

**Comment by NickHardeman** [comment]
Wondering if any platform  still uses GLUT window. I couldn't find anything internally

**Comment by NickHardeman** [comment]
Related: #7672

**Comment by danoli3** [comment]
+ removal GLUT its license was permissive modification and to open source anyways, burn it

**Comment by dimitre** [comment]
Great! +1.

**Comment by dimitre** [comment]
I think you should left this uncommented
```c++
//#if !defined(TARGET_OF_IOS) & !defined(TARGET_ANDROID) & !defined(TARGET_EMSCRIPTEN) & !defined(TARGET_RASPBERRY_PI_LEGACY)
//    #include "ofAppGLFWWindow.h"
//#endif
```
so we can use this kind of command:
```c++
auto windowP = ((ofAppGLFWWindow*)ofGetWindowPtr())->getGLFWWindow();
```

**Review by danoli3 — APPROVED** [review]

**Comment by NickHardeman** [comment]
@danoli3 Some checks are failing, but seems unrelated to the removal of GLUT window.

**Comment by danoli3** [comment]
Investigating now, seems a prior cache cleared itself and now seeing an error!

**Comment by danoli3** [comment]
Found a bunch of glut mentions in the dev examples will need to fix those up too

**Comment by NickHardeman** [comment]
Ah yeah, I can look into that

**Comment by NickHardeman** [comment]
@danoli3 I think I caught all the includes in devApps. Should be good to go

**Comment by danoli3** [comment]
Cya ya Glut

**Pull request merged**
