### PR TITLE
cleanup: remove videoplayerView, remove unused code

### PR DESCRIPTION
**Pull request by i-n-g-o**
proposing to cleanup ofAVFoundationPlayer:
- removing ofACFoundationPlayerView
- removing unsused code in ofAVFoundationPlayer

### CODE REVIEW

**Comment by i-n-g-o** [comment]
Pinging @openframeworks/video?

**Comment by arturoc** [comment]
From what i've talked with @i-n-g-o it seems the original AV Foundation player was based on an example or something like that and some extra code that is not really need it. can somebody check this? ping @ofTheo @julapy @danoli3 otherwise i'll merge it later

**Comment by ofTheo** [comment]
I think its good to merge. 
Now that iOS and OS X use the same player code this isn�t needed anymore.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
