### PR TITLE
WIP: Fixes for gstreamer 1.20 broken video playback. closes #6871

### LINKED ISSUE #6871: gstreamer 1.20.0 breaks video on Linux
Hi,

I just updated my system, and it seems gstreamer breaks any video playback. Getting this when running the videoPlayer example:
```
[notice ] ofGstUtils: Got context from element 'vaapipostproc0': gst.gl.GLDisplay=context, gst.gl.GLDisplay=(GstGLDisplay)"\(GstGLDisplayX11\)\ gldisplayx11-0";

[notice ] ofGstUtils: Got context from element 'vaapipostproc0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";


(videoPlayerExample:12633): GStreamer-Base-CRITICAL **: 16:43:43.970: basetransform: second attempt to fixate caps returned invalid (NULL) caps on pad vaapipostproc0:sink

(videoPlayerExample:12633): GStreamer-Base-CRITICAL **: 16:43:43.970: basetransform: second attempt to fixate caps returned invalid (NULL) caps on pad vaapipostproc0:sink

(videoPlayerExample:12633): GStreamer-Base-CRITICAL **: 16:43:43.971: basetransform: second attempt to fixate caps returned invalid (NULL) caps on pad vaapipostproc0:sink

(videoPlayerExample:12633): GStreamer-Base-CRITICAL **: 16:43:43.971: basetransform: second attempt to fixate caps returned invalid (NULL) caps on pad vaapipostproc0:sink

(videoPlayerExample:12633): GStreamer-Base-CRITICAL **: 16:43:43.971: basetransform: second attempt to fixate caps returned invalid (NULL) caps on pad vaapipostproc0:sink

(videoPlayerExample:12633): GStreamer-Base-CRITICAL **: 16:43:43.971: basetransform: second attempt to fixate caps returned invalid (NULL) caps on pad vaapipostproc0:sink

(videoPlayerExample:12633): GStreamer-Base-CRITICAL **: 16:43:43.972: basetransform: second attempt to fixate caps returned invalid (NULL) caps on pad vaapipostproc0:sink
[ error ] ofGstUtils: startPipeline(): unable to pause pipeline after 5s[ error ]
ofGstUtils: gstHandleMessage(): embedded video playback halted for plugin, module qtdemux0  reported: Internal data stream error.[warning] ofGstVideoUtils: update(): ofGstVideoUtils not loaded
```
Needless to say, this is a HUGE bug. Please, please, please wait with upgrading gstreamer until this is fixed.

Running this on Arch Linux, oF version 0.11.2. Tested on xorg (bspwm) and wayland (sway).

EDIT: tested now with the latest nightly build, of_v20220210_linux64gcc6_nightly, and getting the same result.

### PR DESCRIPTION
**Pull request by ofTheo**
Fixes broken video playback with GStreamer 1.20 - partially closes #6871 
Huge thanks to Nicholas Lavella ( [from the forums](https://forum.openframeworks.cc/t/ofxgstreamer-on-m1-mac/40257/14?u=theo) ) for helping narrow it down to the callback. 

Needs testing on Linux and older Gstreamer versions ( though the changes should be backwards compatible ).

### CODE REVIEW

**Comment by nlavella09** [comment]
@ofTheo thanks again! Thought it would be good to report back here as well as the forums to keep results in one place.

Mixed results with gstreamer 1.21.0 & M1 Mac:
ofGstVideoGrabber fix works! Video plays through and no crash on exit with the bare bones example we were originally testing.

ofGstUtils fix still crashes for me with the same errors we were originally facing even with the new callback location. Enabling `bFrameByFrame` still does the trick for now but callbacks are still going to need something.

**Comment by ofTheo** [comment]
@nlavella09 - agreed! This isn't even close to a fix :) 
I fixed the setSpeed bug ( which is triggered on mouseMove in the example ) , by switching the flags ( the flush flag seems to the the culprit ), but then I loaded a different video to test and got a crash right away similar to how it was before. 

I am starting to think this may be a bug in GStreamer, but I think the next step might be to make a minimal example that follows their tutorials and see if that has the same issue. 

Thanks for all your help on this! Its a gnarly one!

**Comment by dimitre** [comment]
Not sure if it helps anything but I've just noticed Processing released an update on video library, supporting GStreamer 1.20.3 https://github.com/processing/processing-video/releases/tag/latest
https://github.com/processing/processing-video/tree/master/src/processing/video

**Comment by ofTheo** [comment]
Thanks @dimitre !

Hmm. Looking at the changes I don't really see anything that is related to the issues we're having. They are also using the callback based approach.  The only thing I can see is them switching from RGB to ARGB for the pixel format requested?

https://github.com/processing/processing-video/compare/latest-processing3...latest?w=1#diff-ef6f54cd20ca61b9bcd1a31950772fc00b28ccf6c6b649ebb5eb642b2a430b15R380

At this point I have something working on Linux/Mac where the video will play, but seeking or rate changes cause crashes in the queue thread. ( anything that is passing a flush flag ). 

I'm going to dig into it a little more, but will try the ARGB thing just incase that is related. 

Thanks!

**Pull request merged**
