### PR TITLE
Apothecary Formula - Tess2 fixes

### PR DESCRIPTION
**Pull request by danoli3**
Relevant Former PR: https://github.com/openframeworks/openFrameworks/pull/3613

Build Status: [Build Status](https://travis-ci.org/danoli3/apothecary-den/builds/49404443)

### CODE REVIEW

**Comment by danoli3** [comment]
Verified Build passing.

Merging now so others can build up the tess2 script.

**Comment by tgfrerer** [comment]
looking good! 

one thing: if we use the REV sha `24e4bdd4158909e9720422208ab0a0aca788e700` instead of `master`, we can be sure that we're locked to the correct revision for the patches to apply cleanly.

**Comment by danoli3** [comment]
Yeah good idea. I'll patch that directly.

**Comment by tgfrerer** [comment]
i've just discovered that the osx version would not link against the proper stdlibs. have updated the recipe and included the REV, PR in a sec...

**Pull request merged**
