### PR TITLE
change color consts to constexpr so they are calculated at compile time 

### LINKED ISSUE #5750: initialization state of OF in ctors/dtors:
i am using of 0.9.8 on win10. let's say that i want to share a sqlite database between apps. 
as i want to share paths to the DB in constructors and destructors, i realized that several OF functions are not yet or no more initialized in ctors or dtors:

- the ofLog() functionality
- the ofFilePath:: functionality (boost paths are crashing)
- ofToDataPath()

i am talking about something like:
```
	someClassCtor()
	{
		string sPath = ofFilePath::getAbsolutePath("data/../../../../../apps/logger-sqlite/", false);
		sPath = ofFilePath::getCurrentExeDir() + "data/../../../../../apps/logger-sqlite/";
                spath = ofToDataPath(../../../../../apps/logger-sqlite/");
		sPath = ofFilePath::removeTrailingSlash(sPath) + "/";
		return sPath;
	}
```
above functions may not be valid in ctors and dtors. if ofDataPath() has an issue it creates another issue calling the unitialized ofLog().

i am repeatedly running into this issue and have not figured out a workaround that works on all platforms ( i use win and linux/rpi). it is especially an issue when i work with threads and dtors. and i wish to keep the relative path system of OF, so i can share the apps between platforms and OF versions.

any hints? thx!

### PR DESCRIPTION
**Pull request by arturoc**
fixes #5750 at the risk of making #5731 even worse

### CODE REVIEW

**Comment by johanjohan** [comment]
thx arturo

**Comment by jvcleave** [comment]
could these be moved to a core ofxAddon?

**Comment by arturoc** [comment]
@jvcleave do you mean the constants? i think those should go in the core since they are pretty useful.

In any case the only possible solution i see without breaking user code, is turning the consts into constexpr won't work cause using a consexpr member of the own class type doesn't work in any compiler except gcc.

The original problem was caused cause of using variables declared directly in the file instead of a function or class which is known to be really problematic (see: (de)initialization fiasco) so i don't think is worth to try to solve it by breaking code and would instead recommend to declare variables inside a class or function or somehow have lazy initialization for statics through functions that only initializes those values the first time they are sued.

**Comment by jvcleave** [comment]
@arturoc I find them useful as well but they have been problematic for compile times (particularly in the early RPi days)

Was just a thought - they are pretty easy to #ifdef out

**Comment by arturoc** [comment]
are you sure that the problem is those constants and not ofColor itself being templated?

**Comment by jvcleave** [comment]
I would have to double check but I remember just commenting out the color names to solve it

**Pull request closed without merging**
