### PR TITLE
Bugfix/android vram memory leak

### PR DESCRIPTION
**Pull request by kkirby**
The camera's texture doesn't get deallocated, causing a pretty big memory leak when the app is paused/resumed several times. In theory, the texture should eventually deallocate automatically, but I haven't seen this occur.

### CODE REVIEW

**Comment by arturoc** [comment]
thanks for the fix, can you use ofTexture::clear instead of glDelete...

**Comment by kkirby** [comment]
@arturoc Since the texture is an external texture, calling `clear` is essentially a NOOP, unless I'm missing something.

```c++
void ofTexture::clear(){
	if(!texData.bUseExternalTextureID){
		release(texData.textureID); // <-- This is never reached because
		                            //     bUseExternalTextureID is true.
	}
	texData.bUseExternalTextureID = false;
	texData.textureID  = 0;
	texData.bAllocated = false;
}
```

**Comment by arturoc** [comment]
mmh so that texture is allocated by the OS or at least by android's camera class no? not sure why we should delete it ourselves if we haven't allocated

**Comment by kkirby** [comment]
The texture is generated [here](https://github.com/openFrameworks/openFrameworks/blob/master/addons/ofxAndroid/src/ofxAndroidVideoGrabber.cpp#L115).

```c++
void ofxAndroidVideoGrabber::Data::loadTexture(){
	ofTextureData td;
	GLuint texId[1];
	glGenTextures(1, texId); // <--
	...
	...
}
```

**Comment by arturoc** [comment]
oh i  see, thanks!

**Pull request merged**
