### PR TITLE
make 4.3 error fix

### LINKED ISSUE #6535: make 4.3 breaks compilation
Every project that depends on addons with an `addon_config.mk` file will not compile with make 4.3.1 on Arch Linux. I am getting the error:
```
Compiling kinectExample for Release
make[1]: Entering directory '/home/kf/of_v20200208_linux64gcc6_release/examples/computer_vision/kinectExample'
/home/kf/of_v20200208_linux64gcc6_release/libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk:210: *** missing separator.  Stop.
make[1]: Leaving directory '/home/kf/of_v20200208_linux64gcc6_release/examples/computer_vision/kinectExample'
make: *** [/home/kf/of_v20200208_linux64gcc6_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2

```
Downgrading to make 4.2.1 solves the issue. The issue persists over all the versions of oF that I've tried: 0.11, nightly builds etc.

### PR DESCRIPTION
**Pull request by oxillo**
Seem enough to fix #6535 on MSYS2

### CODE REVIEW

**Comment by cata0309** [comment]
This works and saved me a lot of time ! Thank you ! It should be merged !

**Comment by arturoc** [comment]
The msys2 tests are timing out, i've restarted them a couple of times without luck, once they pass i'll merge this. thanks for the commit and the feedback!

**Comment by cata0309** [comment]
No problem. Is there any contribution guide for people that are getting used to work with OF ? I would like to contribute more !

**Comment by oxillo** [comment]
MSYS2 stalls seem to be an ccache issue in appveyor. Will open an issue (and a PR)

**Comment by oxillo** [comment]
Issue #6565

**Comment by oxillo** [comment]
closing as merged with #6566

**Pull request closed without merging**
