### PR TITLE
supports the Rpi 4 with EGL and GLFW. Closes #6436

### LINKED ISSUE #6436: RPi 4 Support
Making a comment to track getting RPi 4 working in the core. 

This thread on the forum has been really helpful: https://forum.openframeworks.cc/t/rpi-4-raspbian-buster-openframeworks/32856

And there is a PR here which I haven't tried out yet. 
https://github.com/openframeworks/openFrameworks/pull/6325

Notes from @arturoc on allowing for switching between EGL and GL. 
https://github.com/openframeworks/openFrameworks/issues/6412#issuecomment-550284651 

This thread suggests legacy EGL support is not possible via the old approach:
https://www.raspberrypi.org/forums/viewtopic.php?p=1486714&sid=dc1c24dee4649d114b7cf089347f1833#p1486714 

**Current Status:** 
I have RPi 4 building the core and running headless ( using the nightly builds ) with these changes ( https://forum.openframeworks.cc/t/rpi-4-raspbian-buster-openframeworks/32856/21 ) 

- 1
Switch this [line in install_dependencies.sh](https://github.com/openframeworks/openFrameworks/blob/master/scripts/linux/debian/install_dependencies.sh#L40) to: 
```
apt-get install freeglut3-dev libasound2-dev libxmu-dev libxxf86vm-dev g++ libgl1-mesa-dev libglu1-mesa-dev libraw1394-dev libudev-dev libdrm-dev libglew-dev libopenal-dev libsndfile-dev libfreeimage-dev libcairo2-dev libfreetype6-dev libssl-dev libpulse-dev libusb-1.0-0-dev libgtk${GTK_VERSION}-dev libopencv-dev libegl1-mesa-dev libglvnd-dev libassimp-dev librtaudio-dev libboost-filesystem-dev libglfw3-dev  liburiparser-dev libcurl4-openssl-dev libpugixml-dev
```

- 2
And add `PROJECT_LDFLAGS += -latomic ` to [this file](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/linuxarmv6l/config.linuxarmv6l.default.mk#L142).

Once I have a monitor/keyboard will start looking into the GL / EGL changes needed to get windowed apps running.

### PR DESCRIPTION
**Pull request by ofTheo**
This PR adds support for Rpi 4 for both rendering approaches. 
Huge thanks to @ThomasColliers who did most of the work in this branch: https://github.com/ThomasColliers/openFrameworks/commit/36fd56f6ee1c33e25150be86126c8e02abf02086 

I just added a define to distinguish between the older models which can use the older EGL method and the newer models which can use both EGL and GLFW with X11. 

NOTE: I don't think its possible to run EGL with the old legacy driver from what I was reading in other forum posts. 

Things to still check/fix:
- [x] TARGET_RASPBERRY_PI_4 naming is a little weird could be refactored - just used it for now. Especially if there is Model 3 support. 
- [x] Also to consider do we want to do anything for this file too?: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/linuxarmv7l/config.linuxarmv7l.raspberry2.mk 
- [ ] Coming out of fullscreen issue with GLFW mode. Needs a resize to restore rendering. Will open a separate issue / PR after this is merged. 

Note for anyone wanting to automate the bash detection of Debian version. See this solution ( https://unix.stackexchange.com/posts/6348/revisions )

### CODE REVIEW

**Comment by kod3000** [comment]
**For the raspberry pi 4 installation**

**Is it possible to also update the file openFrameworks/scripts/linux/debian/install_dependencies.sh**

**The following error still occurs :**

> installing OF dependencies
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Note, selecting 'libsndfile1-dev' instead of 'libsndfile-dev'
> Package libgles1-mesa-dev is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   libglvnd-dev
> E: Package 'libgles1-mesa-dev' has no installation candidate
> error installing dependencies, there could be an error with your internet connection
> if the error persists, please report an issue in github: http://github.com/openframeworks/openFrameworks/issues

**changing 'libgles1-mesa-dev' to 'libgles1' solves the problem.**

**Comment by ofTheo** [comment]
@kod3000 Thanks for taking a look!  

I have that change in the install_dependencies.sh here:
https://github.com/openframeworks/openFrameworks/pull/6438/files#diff-7263e131fbc295fdf3622c0c204a498aR40 

Hopefully that is addressing what you mentioned.

**Comment by sourya-sen** [comment]
I'm having trouble compiling this for the rPi 3 to test, but that's probably because I don't know how to use the Apothecary. 

Grabbed this branch off @ofTheo, with the submodules, ran install_dependecies, then got stuck with the `missing tesselator.h` error. Tried to look into how the Apothecary works, couldn't figure the flags I'd need to use so then I got the latest Arm6 Nightly Release and took the `glm`, `json`, `kiss`, `tess2` and `utf8` folders from the `/libs` folder into my `openFrameworks/libs' folder. 

Now when I try to compile with `make Release -C /path/to/oF/libs/openFrameworksCompiled/project`,  this is where I'm stuck.

Screenshot 2019-11-10 at 3 45 39 PM

**Comment by sourya-sen** [comment]
Checking in from an RPI 3B+

Without any changes to the makefiles, running the GL Full KMS GL Driver on Buster, graphicsExample compiles and runs from X11. NOT FROM CLI.

So, if it's running Buster and the GL driver is enabled, it doesn't matter if it's a RPI3 or an RPI4 (for the makefile target).

Using the legacy GL driver, it doesn't work from the CLI (I don't think it's supposed to, either?) and gives the eglSwapBuffer() error as is documented on the forums.

**Comment by ofTheo** [comment]
Thanks @arturoc - I think that all makes sense!

In terms of headless.  There might be a way via: `sudo apt-get install xvfb` ( see https://www.raspberrypi.org/forums/viewtopic.php?p=506636&sid=9a675930f1f4dc6447c09a7971fdfc43#p506636 )  It will have to be different with the X powered window ( I don't think the other way is possible at this point as buster doesn't have the older drivers ).

@sourya-sen Thanks for testing! 
Could you try building with this line commented out? 
https://github.com/openframeworks/openFrameworks/pull/6438/files#diff-011c6dc421d3f054ec0e4dd9d10683d5R53 

That should revert to the older approach. 
I am guessing it won't work as I think its not so much a Rpi 4 hardware vs older but a Buster vs older distros issue. Would be interesting to see though. 

Also I am guessing but I think GLFW mode should work for you as well. 

**LEGACY vs NEWER**
If the distinction is more Buster and newer vs older Debian releases. We could do the following based on the Debian version being used. 
- On Buster we can default to the newer approach. 
- On Stretch we can default to the newer ( but I think both will work based on @bakercp 's post ) 
- On older builds it can default to the legacy mode.

**Comment by sourya-sen** [comment]
@ofTheo with the GL driver, I have a feeling headless through a VNC might work, I did set up the entire rPi headless through a VNC connection running X11 but I didn't actually check if OF works through that as well, switched to a proper monitor/keyboard combo once OF was compiled. The VNC server comes with the Raspbian distro, just needs to be enabled through raspi-config, through SSH. I can write a full guide if you want, specially if OF works through this approach.

I'll give the headless through VNC approach a go tomorrow, as well as the legacy approach with the line commented out - it's pretty late this side of the world right now :)

**Comment by ofTheo** [comment]
Thanks @sourya-sen ! 
Appreciate the help testing this. 

From what I understand VNC can be made to work and ssh -X but having it run without an active connection is harder. I _think_ this might solve that `sudo apt-get install xvfb` 

> Xvfb (short for X virtual framebuffer) is an in-memory display server for UNIX-like operating system (e.g., Linux). It enables you to run graphical applications without a display (e.g., browser tests on a CI server) while also having the ability to take screenshots.

**Comment by dimitre** [comment]
I've just checked out your pull request using the following commands:
```
git fetch origin pull/6438/head
git checkout -b pullrequest FETCH_HEAD
```

it only works here using Desktop and keyboard (not under ssh)
ofToggleFullscreen() doesn't work yet, only windowed.
and it fails if software uses FBO (sometimes with a message and others with Segmentation Fault.
Thank you!

**Comment by ofTheo** [comment]
Thanks @dimitre ! 
I got it working with headless after installing xvfb and enabling the GLFW renderer in the make file. 

You can then run a headless example with: 
`xvfb-run ./examples/graphics/polygonExample/bin/polygonExample` 

you get a warning about the gamma ramp not being enabled, but you have a rendering environment and can do GL calls and save out screen grabs etc. 

Will see if using GLFW fixes the fullscreen and fbo issues you mention. 
Thanks!

**Comment by ofTheo** [comment]
@dimitre FBOs and fullscreen works with the GLFW approach. 
I do see a weird issue a few frames after coming out of fullscreen with GLFW where the window has to be resized to restore rendering.  I'll see if I can track that down.

**Comment by sourya-sen** [comment]
FBOs have had issues on the rPi historically when the locale has not been set properly. It could be something similar along those lines, see #5917. I don't think it was every fully fixed.

**Comment by dimitre** [comment]
@ofTheo changed to GLFW and FBO is back working 
tried xvfb-run and it returns an error
ofAppGLFWWindow: 65544: X11: RandR gamma ramp support seems broken

**Comment by ofTheo** [comment]
@dimitre ah yes, I get that error too, but it runs and renders GL calls fine. 
Tested with some outputted screencaptures to png.

**Comment by ofTheo** [comment]
Updated the #defines to be less complex. 

At the moment for older Raspbian releases you need to uncomment this line:
https://github.com/openframeworks/openFrameworks/pull/6438/files#diff-011c6dc421d3f054ec0e4dd9d10683d5R48

I imagine there could be a way to detect the Raspbian version in the make file and switch automatically, but this is not really my area of expertise and I think it might involve calling some bash scripts from the make file. 

Maybe for now we could just include information on uncommenting this line in the Raspberry Pi Setup Guide?

**Comment by bakercp** [comment]
I should finally have access to a pi 3/4 this week. I can give it a run
through and report back.

**Comment by ofTheo** [comment]
Thanks @bakercp!  
I think we're pretty close. I would be curious to see if a Rpi 3 with Stretch or Jessie can run fine with the legacy Driver and USE_PI_LEGACY uncommented in the OF make file.

**Comment by sourya-sen** [comment]
Hey @ofTheo! I haven't had a chance to run stuff on the rPi3 since last weekend but will try to test the newest commits as soon as possible.

**Comment by ofTheo** [comment]
ugg - not sure why these make file commits are failing in the CI. 
pretty much all of them work on the PI. Regardless of if this line passes or fails. 

https://github.com/openframeworks/openFrameworks/pull/6438/commits/81e2e54c414fc2a3358d32ea39dc2cd2732e78e5#diff-011c6dc421d3f054ec0e4dd9d10683d5R58

**Comment by kod3000** [comment]
I'm using the rp4. I got it to work by cloning straight from github using the branch "feature-rpi4". 

Everything runs smoothly, the only thing extra that I did was copy the examples folder from the "of_v20191113_linuxarmv6l_nightly.tar.gz" build over to the cloned and ran them. 

I also installed the "xvfb" but got an error "ofAppGLFWWindow: 65544: X11: RandR gamma ramp support seems broken". I wasn't able to run it headless.

Using a keyboard and mouse the compiled examples work as expected. Fullscreen also seems to be functional. I'm going to try a couple of more examples if anything comes up I'll post it up.

Thanks for getting this functional :)

**Comment by ofTheo** [comment]
@kod3000 - thanks!
That RandR error doesn't stop it running headless. It seems to work fine headless despite the error. I could see if I could catch it though or disable the call on Rpi. 

Toggling fullscreen with ofToggleFullscreen() is weird though. 
See this issue: #6445

**Comment by ofTheo** [comment]
Okay so I think at this point I can get the makefile doing what it needs to and working fine on the CI server. 

The only thing is it looks like GLFW isn't installed on the Travis image which is being used and because the Debian version is Stretch ( VER_ID 9 ) the makefile is selecting the newer approach with GLFW and then erring when it can't find it. 

@arturoc what would be the simplest way to add GLFW to the CI server? Locally on the Rpi 4 I didn't even have to include it in the makefile just have it installed at the system level. 

The other alternative would be to detect that we are running on the CI and disable the GLFW approach, but I think it could be handy to have it use the system most users will be using.

**Comment by ofTheo** [comment]
Okay looks like this is building fine now. 
Think this should be good to go once the rest of the CI tests have passed. 

If there was ever a need for squash and merge its with this PR!
:)

**Comment by ofTheo** [comment]
The two CI failed checks are just for Android and MSYS2 so I think this is good to merge finally!

**Comment by arturoc** [comment]
from what i see the changes to the makefiles are mixing spaces and tabs which is super problematic for makefiles. can you change every new addition to tabs? some very specific lines need spaces though so don't use an autoformater or something that would turn the whole file to spaces please

**Comment by ofTheo** [comment]
@arturoc sure!
I ended up going back and forth a bit dealing with tab / space issues. All these files worked locally and on CI, but I can check and make the changes consistent.

**Comment by bakercp** [comment]
Hi All, I am installing this in class with a student right now and ran into the tabs spaces issue.  I'm happy to help, but will let you take a stab at it.  

Additionally, @ofTheo  would you mind setting the permissions back to 100755 on this file?

```
scripts/linux/debian/install_dependencies.sh 100755 → 100644 
```

I had to manually `chmod` to get it running again.

Thx!

**Comment by ofTheo** [comment]
thanks @bakercp - will add that to the PR for the tabs

**Comment by ofTheo** [comment]
@bakercp @arturoc can comments be tabbed or is that dangerous?

ie is this okay or should I not indent the # 
```
else
	# comment this for older EGL windowing. Has no effect if USE_PI_LEGACY is enabled
	# GLFW seems to provide a more robust window on newer Raspbian releases
	USE_GLFW_WINDOW = 1
	$(info using newer build and GLFW window)
endif

```

**Comment by dimitre** [comment]
I'm back home with access to a RPI4 and RPI3B+, let me know if you need any testing

**Pull request merged**
