### PR TITLE
fixes xcode template to not have OF as a dependcy but as a pre-build …

### PR DESCRIPTION
**Pull request by ofTheo**
…script. related to #6139

### CODE REVIEW

**Comment by ofZach** [comment]
just checked this -- on xcode 10 (using new build system) it fails: 

"Command PhaseScriptExecution failed with a nonzero exit code"

full build errors here: 

https://pastebin.com/n0YaEZTE

I will look at xcodebuild a bit closer and try to see what's happening

**Comment by ofZach** [comment]
oh sorry this was because I need to grab the libraries w/ the github repo...  my bad....

**Comment by ofZach** [comment]
can confirm that xcode 10 works but I'm seeing some strange behavior w/ OF apps on xcode 10 with the new build system -- for some reason, objects constructors are not getting called.  for example when you do 

ofImage img;

or 

ofVideoGrabber grabber;

in the h file, the constructor isn't called (but other functions, when you call them, are called).  When you use the legacy build system everything works as expected.   

@ofTheo wondering if you can check this with xcode 9 and the new build system?    I'll keep poking around.

**Comment by ofZach** [comment]
a little weirder (and maybe xcode 10 / new build related) if you change ofApp.h it doesn't force recompile of ofApp.cpp...   something is kind of janky, researching...

**Comment by ofZach** [comment]
In the meantime, I'm going to look at adding a "project.xcworkspace" via project generator that forces legacy build system, which seems to behave normally 

screen shot 2018-10-06 at 9 32 29 am

need to check if this is ok on older xcodes etc

**Comment by ofTheo** [comment]
Whoa, the constructor thing is super weird. I can check on 10.13. Are there different compiler / clang versions you can use in the build settings with the new build system?

**Pull request merged**
