### PR TITLE
Add mouseEntered/Exited events

### PR DESCRIPTION
**Pull request by mattfelsen**
Sorry, I accidentally split this into a new PR. See previous discussion at #3702

### CODE REVIEW

**Comment by bilderbuchi** [comment]
could somebody please review/merge this PR?

**Comment by mattfelsen** [comment]
All the followers were lost when this got split into a new PR...can I ping the commenters from the previous incarnations of this PR?

**Comment by bilderbuchi** [comment]
sure, it was only @admsyn and @arturoc, though (in the right column under "participants").

**Comment by mattfelsen** [comment]
Also @bakercp authored the previous PR that this one replaced

**Comment by mattfelsen** [comment]
I added a couple commits to add the new mouseEntered/mouseExited callbacks to the examples & templates. I used regex find/replace in Sublime which seemed to match most things, and then went through the changes (quickly) by hand to make sure things looked right. A couple things to note:
- I replaced tabs with spaces or unusual formatting in a few files so that the regex will match more cases for the next person tackling this same endeavor. A few examples:
  - examples/math/noise1dExample
  - examples/addons/kinectExample
- I added windowResized, gotMessage, and dragEvent to files that I noticed didn't have it. A few examples:
  - examples/graphics/lutFilterExample
- Skipped most of the android examples that didn't have related mouse events
- Skipped one of the iOS examples
These all seemed like sensible best guesses to me, but please let me know if anything looks off!

**Comment by kylemcdonald** [comment]
this looks good to me. could you merge or rebase to bring up to date with master and we can pull it? sorry for the wait. thanks for the doxygen comments as well!

**Comment by mattfelsen** [comment]
Looks like it was the removal of osxHighPerformanceVideoPlayerExample that broke it. Fixed now :+1: 

Related git/GH question, is there a way to fix this by rebasing? That changed all the existing commit hashes in my branch, which then wouldn't let me push cleanly, and requires either a --force push or deleting & recreating the branch (which is what I did last time – GitHub closed the PR & prevents reopening). If there's some git-fu you know, please share! :smile:

**Comment by kylemcdonald** [comment]
i think the best solution in this case would be the rebase followed by --force. obviously --force is scary, but it is fine as long as there are no branches from you or others based on the commits already on github.

the merge is fine too, thanks for resolving that!

**Comment by kylemcdonald** [comment]
i think one more discussion worth having in the future will be about which events we want to be present in the examples (and source code in new projects from the projectGenerator). as the number of callbacks on ofBaseApp increases, i think there's an argument to be made for more minimal examples...

**Comment by bakercp** [comment]
+1 on slimmer examples @kylemcdonald -- I'd vote for only including the the methods that are overridden (which is how I do it in my addons).  It's cleaner, and an opportunity for people to understand how their App interacts with the base class.

**Comment by madc** [comment]
Is it possible, that the current master is broken because of this PR?
Getting a couple of errors in `ofEvents.h` (compiling fine with b823e45e6cc82445ac9c1d862956af735c13bcba)

    /Users/.../openFrameworks/libs/openFrameworks/events/ofEvents.h:282:65: No member named 'mouseEntered' in 'ofxBaseGui'
    /Users/.../openFrameworks/libs/openFrameworks/events/ofEvents.h:283:64: No member named 'mouseExited' in 'ofxBaseGui'
    /Users/.../openFrameworks/libs/openFrameworks/events/ofEvents.h:318:68: No member named 'mouseEntered' in 'ofxBaseGui'
    /Users/.../openFrameworks/libs/openFrameworks/events/ofEvents.h:319:68: No member named 'mouseExited' in 'ofxBaseGui'

OS X 10.9, XCode 6.1.1

**Comment by mattfelsen** [comment]
Yes, probably. Can you try adding these two lines to see if it fixes the issue for you? Once I add them in the examples/guiExample project, I start getting separate errors about undefined symbols for ofxSlider but it may be unrelated

ofxBaseGui.h, line 71 reads:
`virtual bool mouseScrolled(ofMouseEventArgs & args) = 0;`

Add these lines below:
`virtual bool mouseEntered(ofMouseEventArgs & args) = 0;`
`virtual bool mouseExited(ofMouseEventArgs & args) = 0;`

**Comment by madc** [comment]
I had the problem with all oF projects I tried to compile, not an specific addon. But I just pulled the master again and everything is working now. Thanks and sorry for the inconvenience :)

**Comment by bilderbuchi** [comment]
@mattfelsen as soon as you rebase something which you also pushed to some public repo, you _will_ need to `--force`, as rebasing rewrites history (as you noticed).

**Comment by mattfelsen** [comment]
@kylemcdonald @bilderbuchi So confused here – in the past I did a force push to a branch that a PR was submitted from, and GitHub automatically closed the PR & locked in from being reopened! Granted, what I did then was roll back one commit, add a new commit, and push instead of pushing a bunch of rebased commits, so maybe that's why? Who knows. I tested force pushing rebased commits to a PR on my own repo a couple days ago and everything worked as expected. ¯\_(ツ)_/¯

**Comment by bilderbuchi** [comment]
how much in the past? the last time I had PRs mysteriously closing on me upon force-push was several years ago... could also be because I avoid rebasing (public history that others could already have pulled)
, though.

**Comment by mattfelsen** [comment]
Not too long, maybe 6 months?

Just tried a couple more tests on my repo. These worked as fine, updating the open PR:
- rebase, force push
- roll back a commit, add a new commit, force push

This closed the PR and prevented reopening:
- delete the branch, push a branch of the same name with different commits 

Oddly, the tooltip mentions that force-pushing will prevent reopening, but both rebasing or rolling back updated the PR instead of closing it. Maybe it's referring to old behavior that I saw which has since been changed/fixed.
screen shot 2015-05-17 at 10 22 34 am

¯\_(ツ)_/¯ again

**Comment by bilderbuchi** [comment]
I can see closing a PR when a branch was deleted&recreated as reasonable behaviour - this makes it impossible to confuse two branches which have the same name accidentally. probably that tooltip is just outdated, I guess you'll have to ask github support...

**Pull request merged**
