### PR TITLE
Avoid crash of doesDirectoryExists function

### PR DESCRIPTION
**Pull request by Taprik**
This function makes the app crash on win7. I put a try catch to avoid
the crash.
issue #5315

### CODE REVIEW

**Comment by Taprik** [comment]
Also adding a sort by date function.
Sorry for the mess, it's the first time I made a pull request

**Comment by arturoc** [comment]
thanks, this seems to be breaking msys2 though. looks like the stat strcut doesn't exist there.

can you use instead:
```
auto ta = std::filesystem::last_write_time(a);
auto tb = std::filesystem::last_write_time(b);
return ta < tb;
```

for the time comparison function?

**Comment by Taprik** [comment]
It works perfectly for me (of 0.9.3)
Thanks Arturo

**Comment by arturoc** [comment]
can you add it to the PR?

**Comment by arturoc** [comment]
looks good, can you also make sortByDate behave the same as sort? where if the files list is empty it'll call listDir before? thanks!

**Comment by arturoc** [comment]
thanks! i'll let the test finish and merge it later

**Pull request merged**
