### PR TITLE
fixing closing and restarting ofxAndroidVideoGrabber

### PR DESCRIPTION
**Pull request by danthemellowman**
fixes closing the Android Video Grabber

### CODE REVIEW

**Comment by HalfdanJ** [comment]
Uh, forgot that one! You removed close from setDeviceID, in that case the example app should be updated to call close when swapping camera.

**Comment by arturoc** [comment]
i think that's how it works currently in other platforms so i'm going to merge it but it's probably a good idea to make it restart if you change the device ID we could add that as a feature in ofVideoGrabber

**Comment by HalfdanJ** [comment]
Let me then update the example app so it works again. I will add a log notice if you change the device id while its running

**Comment by arturoc** [comment]
ok, thanks!

**Pull request merged**
