### PR TITLE
[[deprecated]] PR

### PR DESCRIPTION
**Pull request by dimitre**
All OF_DEPRECATED_MSG replaced by [[deprecated]] by regex
both in OF Core and addons.

Using Visual Studio Code -> replace in files
and some indent fix after.
```regex
OF_DEPRECATED_MSG\("(.*?)",\s?(.*?)\);
[[deprecated("$1")]]\n$2;
```

```regex
\[\[deprecated\("(.*?) is deprecated, 
[[deprecated("
```

```regex
(.*?) instead."\)\]\]
(.*?) instead"\)\]\]
```

closes https://github.com/openframeworks/openFrameworks/issues/7673

### CODE REVIEW

**Comment by dimitre** [comment]
one more ready to review
if you have the time @artificiel @ofTheo

**Comment by artificiel** [comment]
good move for regex!

some messages incorporate "XXX is deprecated" which is integrated by default; they can be shortened and only keep the "use YYY instead" part
```c++
[[deprecated("ofxAssimpModelLoader::loadModel() is deprecated, use load() instead.")]]
```
becomes
```c++
[[deprecated("use load() instead.")]]
```

**Comment by dimitre** [comment]
Good one, I've just did the update. 
Reading again I now want to remove the "instead" word

**Comment by dimitre** [comment]
I've removed the "instead" of the messages. more direct
good to merge in my opinion. I'll wait to see if anybody has objections

**Comment by dimitre** [comment]
@ofTheo I'm merging this one. If we decide anything different count on me for corrections

**Comment by ofTheo** [comment]
Awesome - thanks @dimitre !! 🎉

**Pull request merged**
