### PR TITLE
Fixed inline documentation for ofFilePath::getBaseName(...)

### PR DESCRIPTION
**Pull request by roymacdonald**

### CODE REVIEW

**Comment by roymacdonald** [comment]
Because it is such a minimal fix I decided that opening an issue, as the contributing guidelines  say, was unnecessary.

**Comment by bakercp** [comment]
Seems to also include updates to apothecary / project generator submodule checkpoints -- can you confirm?

**Comment by roymacdonald** [comment]
@bakercp right. I thought that I had removed those from the commit. damn `git add -A` and me for being lazy and using it

**Comment by roymacdonald** [comment]
@bakercp im a bit lost here. Any advice on how to remove this submodules from the PR?
Should I close this PR and make a new, clean one?

**Pull request closed without merging**
