### PR TITLE
Fixes #3980 and #3978

### LINKED ISSUE #3980: remove -lpthread C++ flag
I'm getting lots of warnings about the `-lpthread` flag not being used.

Can we delete this from the OSX project template flags for 0.9.0?

### PR DESCRIPTION
**Pull request by bakercp**
This should be tested by a few other OSX users w/ project generator etc to make sure nothing got messed up.  For some reason, it replaces the entire contents of the file on save.

### CODE REVIEW

**Comment by bakercp** [comment]
Hm ... this is strange, definitely don't merge this until some else tests it.

**Comment by bakercp** [comment]
It seems the file is no longer xml.

**Comment by bakercp** [comment]
This is broken, resubmitting.

**Comment by ofZach** [comment]
you may need to convert to xml using plutil

    plutil -convert xml1 filename

**Comment by bakercp** [comment]
Thanks @ofZach!

**Pull request closed without merging**
