### PR TITLE
Addon Script and Lib fixes

### PR DESCRIPTION
**Pull request by DomAmato**
Updates for opencv and assimp apothecary scripts and resulting libs

### CODE REVIEW

**Comment by DomAmato** [comment]
fixes isse: https://github.com/openframeworks/openFrameworks/issues/3916

Testing the current addon libs resulted in errors so I rebuilt them (this is including @elliotwoods libs) I copied the scripts over to the formulas just to make updating easier than typing in the path.

**Comment by arturoc** [comment]
there's something strange with this PR, some files that are already there like the formulas appear as completely new. i think the problem is that the folder names have change in capitalization. we should keep everything as lower case otherwise github, linux and osx with case sensitive fs will see opencv and openCv as 2 different folders

**Comment by DomAmato** [comment]
The formulas are usually located in addons/(addonName)/scripts/formulas and I moved them to apothecary/formulas so technically they are new files.

 I do see what you mean with the capitalization though specifically the openCv

**Comment by arturoc** [comment]
oh i see, why not leave them in the addons folders?

**Comment by bilderbuchi** [comment]
> oh i see, why not leave them in the addons folders?

I was wondering the same thing.

**Comment by DomAmato** [comment]
It was just for the sake of ease of typing in the apothecary formula to run it, I'll move it back

**Pull request closed without merging**
