### PR TITLE
Appveyor : add Msys2 build

### PR DESCRIPTION
**Pull request by oxillo**
Add MSYS2 32 and 64b bits building.
64 bits currently fails.
32 bits fails on string tests (see issue #5087)

### CODE REVIEW

**Comment by arturoc** [comment]
appveyor seems to fail randomly cause the repo is too big, i believe it'll be solved once we remove the binaries. for the strings issues, in linux we try to set the default locale to something with utf-8. i think that or something similar should solve it:

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppRunner.cpp#L136-L149


can you give it a try?

**Comment by oxillo** [comment]
Spent some hours on std::locale. My conclusion is that MSYS2 only supports "C" locale (not even C.utf8).
I'll set the default locale to "C" in ofAppRunner.cpp and make a MSYS2/C branch in the string tests. I'll submit a separate PR.

**Comment by oxillo** [comment]
According to [this answer](http://stackoverflow.com/questions/4406895/what-stdlocale-names-are-available-on-common-windows-compilers), Mingw C++ doesn't support other locales than "C" and "POSIX" as it is not based on GNU C library.
Opened #5090 to investigate solutions.

**Comment by arturoc** [comment]
just merged this, i've disabled the 64bit builds and the tests that needed a different locale until/if we figure something out

**Pull request merged**
