### PR TITLE
Travis Automated Testing of the Core

### PR DESCRIPTION
**Pull request by danoli3**
#### Automated PR / Commit and Merge testing of Core

Original Discussion here from 2012: ```Continuous integration/testing``` https://github.com/openframeworks/openFrameworks/issues/1068

- iOS Empty Example + openFrameworks Core iOS Build Testing

- OSX Empty Example + openFrameworks Core OSX Build Testing
- Adds a tick or cross to every PR for fail or success (once configured on Travis-ci website) (You may remember this happening a while ago when travis was added for documentation generation).

- Removes Documentation Automation - @HalfdanJ had some travis code to generate http://docs.openframeworks.cc automatically on merges. 
This should be done another way, travis is integration testing, even the Github API is designed for this.

### CODE REVIEW

**Comment by danoli3** [comment]
Example Branch: https://github.com/danoli3/openFrameworks/tree/Automated/Travis-OSX
Travis Status: https://travis-ci.org/danoli3/openFrameworks/branches

Using the template/emptyExample project for both
Limitations we have with Travis are the time per build (max 1 hour). 
So I thought for now the emptyExample is perfect. It validates the core has not been broken by a commit.

Testing this I created another branch from this, one which should soon fail.

https://github.com/danoli3/openFrameworks/tree/Automated/Travis-CoreFail
https://travis-ci.org/danoli3/openFrameworks/builds/68468345

**Comment by bilderbuchi** [comment]
> This should be done another way, travis is integration testing,

well, to be precise, Travis-CI is Continuous Integration, and artifact generation (and that includes docs) is a part of Continuous Integration. ;-)

**Comment by bilderbuchi** [comment]
also, there's no need to rip out the docs generation if we still want that, the builds can run in parallel with a proper travis.yml

**Comment by bilderbuchi** [comment]
also, I think we could run both linux and osx at the same time with the `os` flag.

**Comment by danoli3** [comment]
@bilderbuchi! Nice I'll check out that more detailed matrix style and get everything in one.

**Comment by danoli3** [comment]
Okay I think I've figured it out. I'll keep working on a new PR.

New changes so far just putting into https://github.com/danoli3/openFrameworks/tree/Automated/Travis-OSX for tests.

**Pull request closed without merging**
