### PR TITLE
Fixed Android Studio tutorial for 0.9

### PR DESCRIPTION
**Pull request by PTS93**
The old NDK info doesn't work with 0.9 and some settings need to be changed with current releases of Android Studio in order to compile.

Changed according to https://github.com/openframeworks/openFrameworks/pull/4374#issuecomment-141001075

I only mentioned that 0.9 is a minimum requirement so people don't try it right now with 0.8.4

### CODE REVIEW

**Comment by arturoc** [comment]
not sure why this PR won't merge can you take a look?

**Comment by PTS93** [comment]
Yea its weird. I can also not modify the file anymore directly in GitHub. Same issue with the last one, thats why I closed it again. I close and open up another..

**Comment by arturoc** [comment]
ok, i'v just divided the readme in 2, one for android studio and one for eclipse and the gradle properties is now in the repository so there's probably no need for this anymore but thanks!

**Comment by PTS93** [comment]
Oh cool. I just made a new one for the studio one. Thing that should still be changed though is the NDK download which is listing 0.9 which doesn't work anymore.

**Pull request closed without merging**
