### PR TITLE
Add ofIsFloatEqual() for better floating point equality comparisons.

### PR DESCRIPTION
**Pull request by bakercp**
This is in response to a discussion in #4871 #4872 but also can be applied more consistently in other places in the core.

pinging various people that have been a part of the discussion here docsprint
@danomatika @arturoc @ofZach @golanlevin @anikahhh @workergnome

### CODE REVIEW

**Comment by arturoc** [comment]
that seems overly complicated, i would just add something like ofIsPartiallyEqual or ofIsApproximatelyEqual to work with floats. not sure about the name but i think it should make clear that it's not exactly equal and for integers you will probably always use == anyway

**Comment by bakercp** [comment]
So to be clear, what part is overly complicated?  I've attempted to clearly document the functionality and references and basically copied it from the C++FAQ.  It seems that we'd want to support both float and double (particularly as GLM etc) comes online.  The fact that in the C++FAQ they use the same name (`isEqual`) seems to be a good case for calling it isEqual (and the documentation makes it clear what it is actually doing and why).  The float/integral templating ensures that the the more complicated epsilon approach won't be used for integral types.  Most advance users would know to use `==` for integral types, but new users would benefit from having it "do the right thing" for integral types.

**Comment by bakercp** [comment]
Also, if it matters, I chose return type specialization (instead of function parameter specialization) because I saw that it was done this way in ofEvent of::priv, etc.

**Comment by arturoc** [comment]
what i was trying to say is that i don't think we need a function to compare every possible type. just something to compare floats because doing == with floats can fail.

I would prefer something like ofIsFloatEqual or isAproxEqual or something like that. and that perhaps it's easier to just have explicit versions for float and double than the current template that will fail with an undecipherable error message if you try to do do something like:

```cpp
ofVec2f p1, p2;
ofIsEqual(p1, p2)
```

**Comment by danomatika** [comment]
I agree with Arturo in that the generic naming leads people to expect an implementation for other datatypes as well which is not needed. I think ofIsFloatEqual() would work fine with commenting along the lines of 

> In general, using == is fine when comparing floats without too many decimal places aka image widths, mouse positions, etc. However, when the number of decimal places increases, the floating point precision will go down and it becomes harder to compare things. Also, certain mathematical computations with result in infinitely large, infinitely small, or even irrational "Not A Number" values. In those cases it's recommended to use ofIsFloatEquals() which filters out such precision issues."

**Comment by danomatika** [comment]
Also, maybe I'm a bad programmer but I have almost never needed to do extended checks when comparing floats. I guess I don't need much precision and when I do, I use doubles anyway.

**Comment by bakercp** [comment]
OK.  I understand the concerns better now.  Am modifying it ...

**Comment by bakercp** [comment]
@arturoc @danomatika I believe this resolves the concerns.

As soon as this is merged, I can update the ofRectangle bugs and take a pass to make sure it's in use in other appropriate places in the core.

**Comment by bakercp** [comment]
@arturoc ping

**Comment by arturoc** [comment]
sorry to be picky but isn't it easier to just have a float and a double version? if you try to call it with any other type it'll throw a really complicated error, if there were more types it could make sense to have a worse error message in exchange for code re usability but since it's only 2 functions i think it's worth

**Comment by bakercp** [comment]
OK.  Makes sense.  I'll update it.

**Comment by arturoc** [comment]
thanks, sfinae is such a terrible hack to solve that c++ doesn't have a way to specify the type of the template parameters. it's useful in some cases but is really ugly in terms of syntax, the error messages it produces... there's a couple of places in the core where it's used but there were no other option

**Comment by bakercp** [comment]
OK I think this is cleaned up and ready to go as soon as CI finishes.  Once this is in I'll send fixes for the ofRectangle, etc.

**Comment by bakercp** [comment]
@arturoc The updates failed hard on appveyor.  Probably because it gets ambiguous with float,float double,double.  How should we solve this?

**Comment by arturoc** [comment]
mmh, yeah makes sense then i guess we need to use enable_if after all

**Comment by bakercp** [comment]
Closing this to remove all the in-progress commits.  Check out the final version here #4958.

**Pull request closed without merging**
