### PR TITLE
Apothecary - 0.9.0 Dependancy Libs Update and Core Changes (for iOS).

### PR DESCRIPTION
**Pull request by danoli3**
This pull includes the major 0.9.0 dependancy library updates as defined in the Apothecary scripts.

It also specifically includes static libraries for iOS in ```arm64, armv7, i386, x86_64``` compiled with libc++.

This includes all necessary code changes found in https://github.com/openframeworks/openFrameworks/pull/3651 (merged into this).

--------------------------------------------

### iOS Example Build Tests 

| iOS Example Tested              | i386 (Simulator) |  x86_64 (Simulator) | armv7 |  arm64 |
|---------------------------------|------------------|---------------------|-------|--------|
| Empty Example                   | Build Passing | Build Passing | Build Passing | Build Passing |
| advancedEventsExample            | Build Passing | Build Passing | Build Passing | Build Passing |
| advancedGraphics*  | Build Passing | Build Passing | Build Passing | Build Passing |
| audioInputExample```*```  | Build Passing | Build Passing | Build Passing | Build Passing |
| audioOutputExample```*```  | Build Passing | Build Passing | Build Passing | Build Passing |
| CoreLocationExample```**```   | Build Passing | Build Passing | Build Passing | Build Passing |
| dirListExample ```*```  | Build Passing | Build Passing | Build Passing | Build Passing |
| eventsExample```*```  | Build Passing | Build Passing | Build Passing | Build Passing |
| fontsExample  | Build Passing | Build Passing | Build Passing | Build Passing |
| fontShapesExample```*```  | Build Passing | Build Passing | Build Passing | Build Passing |
| graphicsExample```*```  | Build Passing | Build Passing | Build Passing | Build Passing |
| imageLoaderExample```*```  | Build Passing | Build Passing | Build Passing | Build Passing |
| ImagePickerExample  | Build Passing | Build Passing | Build Passing | Build Passing |
| iosCustomSizeExample```***```  | Build Passing | Build Passing | Build Passing | Build Passing |
| iosES2ShaderExample  | Build Passing | Build Passing | Build Passing | Build Passing |
| iosExternalDisplayExample  | Build Passing | Build Passing | Build Passing | Build Passing |
| iosNativeExample```***```  | Build Passing | Build Passing | Build Passing | Build Passing |
| iosOrientationExample```*```  | Build Passing | Build Passing | Build Passing | Build Passing |
| iosStoryboardExample  | Build Passing | Build Passing | Build Passing | Build Passing |
| iPhoneGuiExample  | Build Passing | Build Passing | Build Passing | Build Passing |
| KeyboardExample  | Build Passing | Build Passing | Build Passing | Build Passing |
| MapKitExample  | Build Passing | Build Passing | Build Passing | Build Passing |
| moviePlayerExample  | Build Passing | Build Passing | Build Passing | Build Passing |
| ofxGuiExample  | Build Passing | Build Passing | Build Passing | Build Passing |
| oscReceiverExample  | Build Passing | Build Passing | Build Passing | Build Passing |
| oscReceiverExample```****```  | Build Passing | Build Passing | Build Passing | Build Failure|
| polygonExample```*```   | Build Passing | Build Passing | Build Passing | Build Passing|
| PrimitivesExample```*```   | Build Passing | Build Passing | Build Passing | Build Passing|
| soundPlayerExample```*```   | Build Passing | Build Passing | Build Passing | Build Passing|
| textureExample```*```   | Build Passing | Build Passing | Build Passing | Build Passing|
| TouchAndAccelExample   | Build Passing | Build Passing | Build Passing | Build Passing|
| vboExample   | Build Passing | Build Passing | Build Passing | Build Passing|
| videoGrabberExample```*```   | Build Passing | Build Passing | Build Passing | Build Passing|
| xmlSettingsExample```*```   | Build Passing | Build Passing | Build Passing | Build Passing|

### Addons

| iOS Example Tested              | i386 (Simulator) |  x86_64 (Simulator) | armv7 |  arm64 |
|---------------------------------|------------------|---------------------|-------|--------|
| assimpExample            | Build Unknown | Build Unknown | Build Unknown | Build Unknown |
| opencvExample            | Build Unknown | Build Unknown | Build Unknown | Build Unknown |
| opencvFaceExample            | Build Unknown | Build Unknown | Build Unknown | Build Unknown |

### Test Devices Note: 

- Testing ```i386``` with iPhone4s Simulator 7.1 and 8.3.
- Testing ```x86_64``` with iPhone 6 8.3 Simulator
- Testing ```arm64``` with iPhone5s 8.3
- Testing ```armv7``` with iPad2 8.3

### Issues:

| Symbol             | Number |  Description |
|--------------------|---------|-------------|
| ```*```     | Issue 1  | in iOS 8.3 landscape mode having some issues (it goes into landscape, however is cutt off at the portrait width) (maybe problem in master too for 8.3). iOS 7.1 is fine. (unreleated to merge)|
| ```**```    | Issue 2  | No prompt for location access on iOS 8.0+ Physical Devices - Loc always 0. Bug with not asking permission (unrelated to merge) |
| ```***```   | Issue 3  | Had some broken code in this example. I've fixed in a seperate PR https://github.com/openframeworks/openFrameworks/pull/3823 (unrelated to merge) |
| ```****```  | Issue 4  | The Build Succeeded. OSC triggers a realtime assertion in the case of arm64OscOutboundPacketStream has an assertion about the sizes of some data types and it is getting broken in arm64, not a problem in x86_64   Link to assertion: https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxOsc/libs/oscpack/src/osc/OscOutboundPacketStream.cpp#L165  ```Assertion failed: (sizeof(osc::int32) == 4), function OutboundPacketStream, file openFrameworks/addons/ofxOsc/libs/oscpack/src/osc/OscOutboundPacketStream.cpp, line 166. ```|
    

--------------------------------------------

### Table Definitions: 

| Keys | Value |
|------|-------|
|Tested and Working | Build Passing|
| Not yet Tested | Build Unknown|
| Build Failure | Build Failure |

### CODE REVIEW

**Comment by ofTheo** [comment]
Thanks @danoli3  ! 

I almost feel we should merge this in now as it will mean we'll need to get the updated static libs for the other platforms in, which would be a big step to 0.9.0 

Curious what others think.

**Comment by julapy** [comment]
+1
it would be great to start working with 64bit OF in master.
and we can patch up any gaping holes as we find them.

**Comment by danoli3** [comment]
Let me test the majority of the iOS Examples first, then I think great idea. Doing this now.

**Comment by bakercp** [comment]
+1 on this.  I have OSX, Linux32 and Linux64 well tested in one of my
production branches and can provide static libs.


---
http://christopherbaker.net

**Comment by bakercp** [comment]
(to clarify I have Poco, openssl, and related libs for those platforms -- but school is out now so I have a little more flex time to help with this process again).

**Comment by ofTheo** [comment]
@openframeworks/core  would you be okay with this approach?

**Comment by pizthewiz** [comment]
Not speaking for core, but I think this is roughly the same approach discussed during the last [IRC Meetup](http://irclog.perlgeek.de/openframeworks/2015-05-03#i_10540435).

**Comment by danoli3** [comment]
### 135/136 successfully built and ran!!

The one fail related to OSC assert issue with arm64 we can fix later.
The Landscape issue for 8.3 is really annoying though, going to check if that's on master right now.

**Comment by ofTheo** [comment]
okay I think we should merge this in. ping @arturoc  
I'll merge the PR in a few hours if there are no objections

**Comment by danoli3** [comment]
Just had success testing OpenCV examples, sweet arm64 speed!! @kylemcdonald 

Going to push another PR with the core addon changes. (it will have to be added after this one). I have a separate branch that is inclusive of all of it for testing.

**Comment by ofTheo** [comment]
ping @bakercp - could you do a PR for the OS X and linux libs? 
Also feel free to merge it in yourself so we get them in the repo as soon as possible.

**Comment by ofTheo** [comment]
@bakercp I'll do a PR for the OS X libs - used apothecary to build them and it has been a good test of the formulas. Everything seems to work so far. Only had to make sure deployment target was set to 10.8 in the examples due to an issue with pixman.

**Comment by bakercp** [comment]
Sounds good @ofTheo

**Comment by ofTheo** [comment]
@bakercp the OS X libs are in. be great if you could check it out when you have a moment.

**Comment by bakercp** [comment]
@ofTheo will do it now!

**Comment by kylemcdonald** [comment]
@danoli3 that's great to hear. very curious if this changes ofxFaceTracker on iOS.

**Comment by danoli3** [comment]
Fixed Issue 1 with "iOS Orientation Issues Fix #3865"

**Pull request merged**
