### PR TITLE
fix for xcode template file to allow PG to add frameworks

### LINKED ISSUE #6172: XCode 9.2 can't open project after update 7b87f643f
XCode 9.2 can't open project after update 7b87f643f
Project xxx.xcodeproj cannot be opened because the project file cannot be parsed.

### PR DESCRIPTION
**Pull request by ofTheo**
fix for xcode template file to allow PG to add frameworks and fix broken projects. 
closes #6172

### CODE REVIEW

**Comment by roymacdonald** [comment]
Hi, now after this update PG fails to create working projects for xcode 8.3.2 that use frameworks as it is the case of ofxSyphon. In the past I made a fix that was properly adding the frameworks but now xcode simply complains that it can not parse the `project.pbxproj` file. Until which version of Xcode is going to be supported?

**Comment by ofTheo** [comment]
hmm @roymacdonald that is the issue this PR should of fixed. 
could you try the nightly zips and see if that works for you?

**Comment by ofTheo** [comment]
@roymacdonald let me know if you see the issue with: 
https://openframeworks.cc/ci_server/versions/nightly/of_v20181113_osx_nightly.zip

I just tried it on Xcode 9 which was having the same error you mentioned before with ofxSyphon and it works fine for me.

**Comment by roymacdonald** [comment]
Hey @ofTheo I tried of_v20181113_osx_release and indeed it works.
Now I forced the pull from the master branch and it also works. Xcode.....
So, ignore all this.
all the best

**Pull request merged**
