### PR TITLE
Msys2 freeimage fixes

### PR DESCRIPTION
**Pull request by oxillo**
FreeImage package name update in MSYS2 package repository

### CODE REVIEW

**Comment by arturoc** [comment]
is this broken in 0.9.2 then?

**Comment by oxillo** [comment]
I haven't checked but, unfortunaltely,  I would say Yes if you have a clean MSYS2 install or upgraded it duraing the last days. The FreeImage package requires the libraw-10.dll that has been upgraded to libraw-15.dll.

**Comment by arturoc** [comment]
so both things are because of something that has changed in msys it self not a bug on our side?

**Comment by oxillo** [comment]
Not an OF bug !

**Comment by arturoc** [comment]
i've opened a 0.9.3 milestone and created a branch of the same name since there's a couple of critical and regressions that we can fix quickly, can you send this PR to that branch instead? thanks!

**Comment by arturoc** [comment]
this is the same we merged yesterday into 0.9.3 right? in that case we can close it and i'll merge 0.9.3 into 0.10

**Comment by oxillo** [comment]
Yes, they are the same. I close it.

**Comment by arturoc** [comment]
great, thanks!

**Pull request closed without merging**
