### PR TITLE
docs_low_level: ofMaterial.h

### PR DESCRIPTION
**Pull request by danomatika**
doxy commenting for ofMaterial

### CODE REVIEW

**Comment by bakercp** [comment]
Reviewing ...

**Comment by bakercp** [comment]
Is this a duplicate of the ofMaterial work in here: https://github.com/openframeworks/openFrameworks/pull/4892?

**Comment by danomatika** [comment]
Partially, but with added comments for the class itself.

**Comment by danomatika** [comment]
merged #4898 into this PR

**Comment by danomatika** [comment]
merged this into #4892

**Pull request closed without merging**
