### PR TITLE
Feature issue 4600

### PR DESCRIPTION
**Pull request by tpltnt**
Hey,

i renamed ofGetLastFrameTime() to ofGetTimeSinceLastFrame() as suggested in #4600.
Cheers.
tpltnt

### CODE REVIEW

**Comment by tpltnt** [comment]
ping

**Comment by ofTheo** [comment]
looks good to me - thanks!

**Comment by tpltnt** [comment]
Thank you for the fast response @ofTheo

**Comment by arturoc** [comment]
mmh we never agreed on this, the original issue says that the current function is confusingly named and some suggestions but i don't think this one is much better either, i would argue that is even worse.

get time since last frame, strictly speaking would return different values if you called it several times during one frame.

what's really going on is that we meassure the time since we call update until swap buffers returns and then pass that time to the next frame, so really get last frame time is pretty accurate describing what's going on

perhaps we can add a time delta parameter to the update callback in ofApp and update event but i don't think this naming is very correct and i think it's even too long

**Comment by arturoc** [comment]
also this is changing the global c function but not the equivalent method in ofCoreEvents and ofFpsCounter, making the api less unifom.

i'll revert it later unless someone thinks it should stay like this

**Comment by tpltnt** [comment]
@arturoc why haven't you spoken up earlier when you added it to the 0.10.0 milestone on 2015-12-05?  I only mapped the consensus reached in #4600 into code. Since that ticket points out the "original issue (which) says that the current function is confusingly named", wouldn't that be the place to have a meaningful discussion? Others might also attempt at fixing it and probably won't check all discussions in all related PRs. As far as I am aware I also was not "changing the global c function", but only added deprecation warnings. The original code is still there, but the compiler will point out function calls to investigate for compatibility.

**Comment by ofTheo** [comment]
I think the way the PR handles changing the API is totally fine, as it simply makes the old function deprecated. 

However if the naming is not really describing what is going on correctly then that is obviously a problem. If the original describes the value correctly then we should revert it and keep the original.

**Comment by arturoc** [comment]
it's not, because the function calls other methods with the same name in ofCoreEvents and ofFpsCounter which are not renamed so now there's the global c function with one name and the methods in those classes with the old name.

in any case i think the naming is not very accurate anyway.

**Pull request merged**
