### PR TITLE
oF iOS arm64 c++11 support (only merge once iOS apothecary build binaries are in master)

### PR DESCRIPTION
**Pull request by danoli3**
plus
arm64

These new changes allow for arm64 and libc++/c++11 support for iOS for openFrameworks.

---
# Use

Use the updated template found in ```scripts/ios/template/*```
Once the OS X changes go into master, you can use the project generator for OS X for iOS projects.

---

## Changes
- iOS arm64 supported (for oF core and all external dependancies). 
- iOS Simulator x86_64  supported (simulator libraries for arm64 devices and release mode for all)
- c++11 and libstdc++ now the default for iOS (in line with Apple's recommendation and default for iOS).
- Fixes type issues that are not valid in libc++ for iOS related files.

---

# Pre-Requisites (Apothecary library builds)

This works once apothecary has been used to compile out all necessary fat libs: 

    ./apothecary -t ios update openssl
    ./apothecary -t ios update poco
    ./apothecary -t ios update FreeImage
    ./apothecary -t ios update freetype
    ./apothecary -t ios update tess2
    ./apothecary -t ios update ofxAssimpModelLoader
    ./apothecary -t ios update ofxOpenCV
---

# Preview

ss

# Experimental Branch to test

Currently the latest libraries have been built and linked in the following branch, however working for iOS arm64.
https://github.com/danoli3/openFrameworks/tree/Apothecary/OLD/0.9.0-All (changed to OLD until the new one is in a PR).
Do not submit to the AppStore with this branch just yet unless you are sure and test everything your app requires, still very early testing and this is also built with the latest master changes.

### CODE REVIEW

**Comment by abrahamavnisan** [comment]
@danoli3 - It doesn't appear that there is an ofxOpenCV formula, so the ./apothecary -t ios update ofxOpenCV won't run.  Any tips?

**Comment by abrahamavnisan** [comment]
Hi @danoli3!  I've successfully run an empty example on my 64bit iPad air after running all of the apothecary builds.  I did want to report an error I ran into when running ofxOpenCV update.  I'm using cmake version 3.1.2, which I installed via brew. 

Here is my terminal output:

> Abrahams-MacBook-Pro:apothecary abrahamavnisan$ ./apothecary -v -t ios update ofxOpenCV
> Valid build types: osx osx-clang-libc++ linux linux64 linuxarmv6l linuxarmv7l vs win_cb ios android
> Build type: ios
> Architecture: 32
> Build dir: ~/OF_Master/openFrameworks/scripts/apothecary/build
> Libs dest dir: ~/OF_Master/openFrameworks/scripts/apothecary/../../libs
> Running: update ofxOpenCV
>  Detected addon: "ofxOpenCV"
> 
>  ----- OpenCV -----
> 
>  Downloading "OpenCV"
>  Formula dir: ~/OF_Master/openFrameworks/scripts/apothecary/../../addons/ofxOpenCV/scripts/formulas
>  Formula build types: osx ios
>  Build dir: ~/OF_Master/openFrameworks/scripts/apothecary/build
>  Depends formula dir: ~/OF_Master/openFrameworks/scripts/apothecary/formulas/_depends
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   120    0   120    0     0    298      0 --:--:-- --:--:-- --:--:--   297
>   0     0    0 84.9M    0     0   257k      0 --:--:--  0:05:37 --:--:--  501k
> 
>  Preparing "OpenCV"
>  Lib src dir: ~/OF_Master/openFrameworks/scripts/apothecary/build/OpenCV
> 
> 
>  Building "OpenCV"
>  Lib src dir: ~/OF_Master/openFrameworks/scripts/apothecary/build/OpenCV
> 
> CMake Warning at /usr/local/Cellar/cmake/3.1.2/share/cmake/Modules/Platform/Darwin-Initialize.cmake:128 (message):
>   Ignoring CMAKE_OSX_SYSROOT value:
> 
>    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk
> 
>   because the directory does not exist.
> Call Stack (most recent call first):
>   /usr/local/Cellar/cmake/3.1.2/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:18 (include)
>   CMakeLists.txt:56 (project)
> 
> 
> -- The CXX compiler identification is AppleClang 6.0.0.6000056
> -- The C compiler identification is AppleClang 6.0.0.6000056
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - failed
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - failed
> CMake Error at CMakeLists.txt:70 (message):
>   CMake fails to deterimine the bitness of target platform.
> 
>     Please check your CMake and compiler installation. If you are crosscompiling then ensure that your CMake toolchain file correctly sets the compiler details.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "~/OF_Master/openFrameworks/scripts/apothecary/build/OpenCV/CMakeFiles/CMakeOutput.log".
> See also "~/OF_Master/openFrameworks/scripts/apothecary/build/OpenCV/CMakeFiles/CMakeError.log".
> 
>  ^ Received error ^

**Comment by danoli3** [comment]
Yeah currently the openCV iOS portion of this is currently not building.
Also the ofxAssimpModelLoader is not building the old version yet (supported by oF).
So as long as your project doesn't use either of those this branch will work.

**Comment by iniwap** [comment]
this 0.9 brach ofGetWidth can't get right width ,6 and 6p

**Comment by kylemcdonald** [comment]
is it possible for you to add commits for the precompiled binaries as well? then we should be able to merge and work with it immediately, correct?

it would be good to merge this while we're filling all out apothecary / c++11 / 64-bit. the repo will get bigger again, but it's temporary :)

**Comment by danoli3** [comment]
@kylemcdonald better get my potion hat on.

apothecary

I'll do another PR with the iOS libraries as well as source updates.

**Comment by kylemcdonald** [comment]
we need to make a little image generator bot that adds that hat to any avatar that submits pull requests for apothecary!

**Comment by bilderbuchi** [comment]
I'd rather have hats for people reviewing and merging pull requests, to be honest. ;-)

**Comment by ofZach** [comment]
there's a lot of different hat styles :hat: out there...

**Pull request merged**
