### PR TITLE
Unicode flags for Code::Blocks projects

### PR DESCRIPTION
**Pull request by procedural**
See #4103

### CODE REVIEW

**Comment by procedural** [comment]
Anything else? I feel like OF has more than one CB project

**Comment by arturoc** [comment]
i think this: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/win_cb/openFrameworksLib.cbp would need the same flags

**Comment by procedural** [comment]
@arturoc certainly!

**Comment by procedural** [comment]
@arturoc by the way, shouldn't emptyExample have `<Add option="-std=gnu++11" />` as well? It's missing it right now, add it too?

**Comment by arturoc** [comment]
yeah it should, if you want to add it too go for it...

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
