### PR TITLE
Feature Visual Studio 2013 - WIP

### LINKED ISSUE #2570: OF with VS 2013
Is it possible to get it running on Visual Studio 2013 with new .NET 4.5 Compiler?

### PR DESCRIPTION
**Pull request by LeoColomb**
Patch to begin the support of Visual Studio 2013, and Windows 8.1.

* Support full C++11 - #2335   
* Improve compile time   

---
- [x] Projects version `120`
- [x] Improve solutions with VS2013 features
- [x] Scripts
- [x] x64 compatible solutions (#2758)
- [ ] **Recompile libs**
   * Win32
   * x64
- [ ] Check compilation (errors/bugs)
- [ ] Changelog!

---
Resolve #2570

### CODE REVIEW

**Comment by kylemcdonald** [comment]
@LeoColomb is it possible to merge this once we rebuild the libs? it looks like that's the only checkbox left over.

do you need more help with this process? presumably this means updating all the apothecary scripts for windows still? i think we have some interest from people at @localprojects in contributing to windows.

**Comment by LeoColomb** [comment]
> is it possible to merge this once we rebuild the libs?

I don't see any problem, but this PR currently contains solution changes only, not compilation fixes.

> do you need more help with this process?

As I said on [two comments above](https://github.com/openframeworks/openFrameworks/pull/2571#issuecomment-55623665), I'm undergoing a tough year at school, and all my time is taken.
So I don't *need* help, because I can't do anything :wink:

**Comment by chuckleplant** [comment]
Hi there, I want to help compiling libs.. where can I check with versions we should be using for each dependency?

**Comment by LeoColomb** [comment]
@chuckleplant I think you may (must?) use [apothecary](https://github.com/openframeworks/openFrameworks/tree/master/scripts/apothecary).
Ping @openframeworks/windows

**Comment by chuckleplant** [comment]
Thanks! I'll see to it.

**Comment by DomAmato** [comment]
I'd be willing to lend a hand as well since my main dev platform is windows. Did the guys over at MSOpenTech do anything with this? I am pretty sure they forked OF but I havent actually looked at what they did

**Comment by MinaSamy** [comment]
+1 to that, I just downloaded the MS OpenTech fork and can't get the project generator to run, I can't understand how they got it to work in their virtual academy tutorials!

**Comment by kylemcdonald** [comment]
hey @DomAmato we actually need a lot of help building apothecary formulas for windows, to build libraries for the next release, or we won't be able to release a candidate for 0.9.0. would you be interested in helping with this?

**Comment by DomAmato** [comment]
Yeah i would def be interested. I talked to @bakercp about this a little bit about how to get MSVC into the formulas to build for the appropriate visual studio version. I found a few examples and put some effort into it but got side tracked. I think ill open a ticket on MSDN to see if anyone has some tips over there.

**Comment by ofTheo** [comment]
@LeoColomb would be happy if you want to pull in from master and bring this PR up to date. We have new libs for all other platforms so it would be a good time to merge this PR in.

**Comment by LeoColomb** [comment]
Well, merging one year of commits during exams is an interesting challenge! :smile:

**Comment by LeoColomb** [comment]
Wow, so easy!
capture

---
@ofTheo Done.

**Comment by LeoColomb** [comment]
Oh, side note: keep in mind VS2015 will be released *very* soon, already in RC.
So it may be more relevant to work on this newer version...

**Comment by ofTheo** [comment]
@LeoColomb - should we merge this in anyway? 
+1 to VS2015 have you got a chance to use it yet?

**Comment by LeoColomb** [comment]
> should we merge this in anyway?

I think so, some changes are essentials, and nothing will break any progress.
It's just an advice to avoid losing so much time twice.

> VS2015 have you got a chance to use it yet?

Yes, a little bit. As always some changes, as always the problem is third party.
As I said above, I'm currently in exams time, but I plan to work on VS2015 this summer.

**Comment by LeoColomb** [comment]
Just a reminder: the VS upgrade is not complete and moves to #3843.

**Pull request merged**
