### PR TITLE
Fixed the ofSerial::buildDeviceList() method on OS X

### PR DESCRIPTION
**Pull request by smallfly**
See the issue #5221

### CODE REVIEW

**Comment by bakercp** [comment]
This may break Linux and is probably a result of the recent std::filesystem::path updates to the internals of ofDirectory.  Ideally, since we're listing the contents of /dev/ on both Linux / OSX, we shouldn't need this prefix to do matching.  There are a lot of stray /dev/ bits in there so perhaps that just needs to be cleaned up?

**Comment by arturoc** [comment]
the changes to use filesystem path where just to the input arguments for methods not to any internals or return methods so it shouldn't have almost any side effects. in any case i've just tested and the problem was already there.

This probably comes from before that when we swapped ofFileUtils to use std::filesystem instead of poco

it seems that for ofDirectory created with absolute paths the paths of the entries are also absolute which wasn't like that before if that code was working.

I guess the correct fix would be to make ofDirectory  behave the way it did before not to fix ofSerial. I'm going to open a PR request only with the tests to check that the paths returned by ofDirectoy are local

**Comment by smallfly** [comment]
With all the info you both brought to the discussion, it's clear that this should not be fixed in ofSerial, but in ofDirectory instead. Sorry for this PR which is in fact just a quick and dirty fix. Should this PR just be closed and the discussion moved to the issue #5221 ? 

I did test ofSerial on Windows before doing this PR, and it was working properly. The issue is only on OS X. Have not tested it on Linux though.

**Comment by arturoc** [comment]
yes i'm going to close this, in windows, the com port is not a file device so it wouldn't be affected by this problem, in linux it happens the same. 

the weird thing is that in windows the directory doesn't have this problem either. i'll comment more in the issue

**Pull request closed without merging**
