### PR TITLE
Fixed ofxGui save and load.

### PR DESCRIPTION
**Pull request by roymacdonald**
-Added ofSerialize and ofDeserialize methods to ofXml, using the new ofXml api.
-Fixed ofDeserialize in ofJson, as it was not reading the nested groups.

### CODE REVIEW

**Comment by roymacdonald** [comment]
https://github.com/openframeworks/openFrameworks/issues/5344

**Comment by roymacdonald** [comment]
Hi @arturoc did you see the CI results for this PR? it seems that on windows when compiling with VS there are some library linking issues.
Also on linux, if fails only when compiling for armv6 as the SAX lib is not found. 
I have very little experience with OF on both this platforms so I'm not sure how to help on this.
all the best!

**Comment by arturoc** [comment]
yes i'm working on it, linux is fixed now, so if you rebuild it it should be ok, windows needs the debug version for one of the new libraries we use but i'm traveling and my windows partition has somehow expired so it'll be take a while for me to fix it

**Comment by roymacdonald** [comment]
great! I have windows on bootcamp and parallels. I can try to figure it out. Any advice? shouldn't it be done via apothecary?
best!

**Pull request merged**
