### PR TITLE
Cubemap support for Emscripten and pbr cube map caching

### PR DESCRIPTION
**Pull request by NickHardeman**

### CODE REVIEW

**Comment by NickHardeman** [comment]
Examples are here for testing:
[MaterialPBR](https://nickhardeman.com/temp/OFExamples/MaterialPBR/materialPBR.html)
[MaterialPBRAdvanced](https://nickhardeman.com/temp/OFExamples/MaterialPBRAdvanced/materialPBRAdvanced.html)

**Comment by Jonathhhan** [comment]
Very nice. I had to set line 1038 in `ofShadow.cpp` to `#if defined(GL_CLAMP_TO_BORDER) && !defined(TARGET_EMSCRIPTEN)` to remove the last warnings, because it seems `GL_CLAMP_TO_BORDER` is not part of GLES < 3.2 and it was not possible for me to enable the extension: https://gamedev.stackexchange.com/questions/140520/gl-clamp-to-border-opengl-es-3 
Similar with: `GL_TEXTURE_BORDER_COLOR`

**Comment by NickHardeman** [comment]
@Jonathhhan ok thank you for that tip. I have some other gl things I need to clean up to work with iOS and Android and I can add that in as well.

**Comment by ofTheo** [comment]
A few errors here with Linux ARM 

```
ofCubeMap.cpp:1111:129: error: ‘glTexStorage2D’ was not declared in this scope
```

```
ofCubeMap.cpp:941:125: error: ‘glTexStorage2D’ was not declared in this scope
```

And in a similar spot with iOS except maybe a helper solution is available?: 

```
ofCubeMap.cpp:1111:2: error: use of undeclared identifier 'glTexStorage2D'; did you mean 'glTexStorage2DEXT'?
```

**Pull request merged**
