### PR TITLE
Removing Quicktime code - Updates on make template

### PR DESCRIPTION
**Pull request by dimitre**
Removing unexistent file $(OF_LIBS_PATH)/videoInput/ from exclusions
Removing QTKit from frameworks in makefiles

### CODE REVIEW

**Comment by ofTheo** [comment]
Awesome. Wondering if maybe these should just get deleted? 
We still have them in the tagged branches and I can't imagine anyone using them anymore.

**Comment by dimitre** [comment]
yeah I'll delete them. I've moved Quicktime files to another folder in this PR too, or we can remove them totally if you prefer
they are now in $ofw/other/legacy

**Review by ofTheo — CHANGES_REQUESTED** [review]
This looks good @dimitre 
If you can switch it to remove the files instead of moving them I think it is good to go. 👍

**Review by ofTheo — APPROVED** [review]
Looks great! 
Thanks @dimitre 👍

Once it passes the last check I'll merge it in.

**Pull request merged**
