### PR TITLE
add any folder with name prefix apps to gitignore

### PR DESCRIPTION
**Pull request by fred-dev**
From forum post https://forum.openframeworks.cc/t/branches-and-my-of-folder/22277, to allow for folders named apps* in the of directory.

### CODE REVIEW

**Comment by arturoc** [comment]
have you tested if this really works and doesn't ignore other apps* folders in other levels than root? i posted that syntax in the forum but not 100% sure is completely correct

**Comment by fred-dev** [comment]
I tested but not completely- you are correct, it ignores any folder named apps in all folders. The correct functioning (tested by adding folders with various names beginning with apps to **all** subfolders from the root of the repo is actually  "/apps*/" it is in my last commit 

https://github.com/openframeworks/openFrameworks/commit/a8fa38546b4436144f7753358ef7b1263f477133

Now I am unfamiliar with protocol, should I make another PR?

**Comment by arturoc** [comment]
no that's fine any new commit gets added to the current PR

**Comment by arturoc** [comment]
going to merge this then. thanks!

**Comment by fred-dev** [comment]
Cheers

**Comment by arturoc** [comment]
also something that would be really useful if you want to look into it is to update any guides we have about workflow with this kind of info. i'm not sure where they live right now. perhaps @bilderbuchi knows?

**Comment by bilderbuchi** [comment]
I'm not aware of any docs like this. Most stuff that I wrote was concerned with the developer-side of things, and not the user-side, and lives in the Wiki on Github.

Btw, it would probably have made more sense to add that line farther up, where the `apps/*` entry is, and/or add a little explanation what the intent of the change is.

**Pull request merged**
