### PR TITLE
bugfix: segfault on metadata devices

### PR DESCRIPTION
**Pull request by nagyt2**
This bugfix fixes a segmentation fault in case one tries to read the video stream from a device that only provides metadata information (but no video).

The fix is based on filtering out such devices in the 'get_video_devices' function. (In a similar way as non-video-capture devices was already filtered out.)

Tickets related to this issue:

- https://forum.openframeworks.cc/t/ofgstutils-error-on-linux/36870
- https://github.com/openframeworks/openFrameworks/issues/6556

Details:
On linux systems several webcameras are splitted into two (or more) /dev devices: one for the video capture and one for the metadata.
E.g. In my Ubuntu system I have these devices and capabilities:

```
$ v4l2-ctl --device=/dev/video0 --all
Driver Info:
	Driver name      : uvcvideo
	Card type        : HP Wide Vision HD Camera: HP Wi
	Bus info         : usb-0000:00:14.0-5
	Driver version   : 5.8.18
	Capabilities     : 0x84a00001
		Video Capture
		Metadata Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
...

$ v4l2-ctl --device=/dev/video1 --all
Driver Info:
	Driver name      : uvcvideo
	Card type        : HP Wide Vision HD Camera: HP Wi
	Bus info         : usb-0000:00:14.0-5
	Driver version   : 5.8.18
	Capabilities     : 0x84a00001
		**Video Capture**
		Metadata Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04a00000
		Metadata Capture
		Streaming
		Extended Pix Format
...
```

As one can notice, both _/dev/video*_ devices have the "Video Capture" capability, but only the first one has the "Video Capture" Device cap.
These cases were unhandled in the ofGstVideoGrabber::get_video_devices function till now.

### CODE REVIEW

**Comment by ofTheo** [comment]
Hi - this looks good to me though it would be good to target the patch-release and not master branch. 
If you can rebase it to patch-release then we can merge.

**Comment by nagyt2** [comment]
Thank you ofTheo, I just changed the target branch. BTW maybe it's also time to update the CONTRIBUTING.md file, I read there that I am supposed to open my pull request on _master_:

> Submit your pull request to the master branch of openFrameworks (which you branched off from), not the stable branch.

**Comment by nagyt2** [comment]
Hmmm. Changing the base branch screwed up the diff. I have no idea how can I fix it, so it is probably better if I create a new pull request.

**Comment by ofTheo** [comment]
Thanks @nagyt2 !!

**Pull request closed without merging**
