### PR TITLE
use gold linker in linux

### PR DESCRIPTION
**Pull request by arturoc**
makes link times much faster on big projects

### CODE REVIEW

**Comment by arturoc** [comment]
it looks like ld.gold is faster though

with a relatively big project after compiling the full project and touching 1 file recompiling takes:

- ld: 28s
- lld: 14s
- ld.gold: 12s

**Comment by hamoid** [comment]
Nice! Massive improvement :)

**Comment by hamoid** [comment]
With existing projects, is it enough to pull the latest OF changes to benefit from this? Or do we need to use the project generator?

**Comment by arturoc** [comment]
@hamoid, yes the qtcreator project has most of it's code in a common folder in the core no need to recreate the project

**Pull request merged**
