### PR TITLE
Load 16 bit grayscale images downsampled to 8bit

### PR DESCRIPTION
**Pull request by NickHardeman**
Related to #7552

### CODE REVIEW

**Comment by dimitre** [comment]
Great @NickHardeman ! 
idea: how about notifying with ofLogNotice or ofLogWarning when it is downsampled?

**Comment by NickHardeman** [comment]
Maybe ofLogVerbose?

**Comment by ofTheo** [comment]
Ah but wouldn’t this PR break loading 16 bit grayscale images into ofShortPixels ?

**Comment by NickHardeman** [comment]
The added line only executes if it's an ofImage / unsigned char due to this pixel type check in the if statement. So the functionality for images other than ofImage remains the same.
`if(sizeof(PixelType)==1`
Attached is an example for testing with ofImage, ofFloatImage and ofShortImage for the color and gray images.
[sRGB16bit.zip](https://github.com/openframeworks/openFrameworks/files/12894203/sRGB16bit.zip)

**Pull request merged**
