### PR TITLE
macos action cache

### PR DESCRIPTION
**Pull request by dimitre**

### CODE REVIEW

**Comment by ofTheo** [comment]
thanks @dimitre - looks like it needs a line for boost too 
maybe we can merge it in soon so other PRs can run? 

Or I could just kill all the caching in master so you can take your time with this?

**Comment by dimitre** [comment]
sorry I was away from the computer. all ok now

**Comment by ofTheo** [comment]
@NickHardeman now this is merged you'll probably want to pull OF/OF master into your branch

**Comment by NickHardeman** [comment]
@ofTheo ok thanks! Will do, trying to fix linux arm at the moment ;)

**Pull request merged**
