### PR TITLE
Issue #4478 msys2 outdated opencv

### PR DESCRIPTION
**Pull request by oxillo**
update ofxOpenCv (and opencv libs) to work for MSYS2. Not tested on other platforms...

### CODE REVIEW

**Comment by ofTheo** [comment]
Thanks for this PR - curious why you changed files in ofxOpenCv though?
On other platforms these changes aren't required, so it makes me think that you might have built a newer version of OpenCV than is being used on other platforms. Is this version 2.4.9 ?

**Comment by oxillo** [comment]
@ofTheo MSYS2 pacman installs openCV 3.0.0 where some legacy code (I guess from OpenCv 1.x) has been dropped. 
Most changes were just #define in compat.hpp.
The harder one was the unDistortOnce where I just copied the 3 lines content of the function from legacy code...
The good thing is that switching to openCv3 looks pretty easy.

**Comment by ofTheo** [comment]
thanks @oxillo - I figured as much. 
Is there anyway to get pacman to generate 2.4.9? 
I think we could switch to OpenCV 3.0 for OF 0.9.1 but we can't release 0.9.0 with different versions of OpenCv across platforms. 

Thanks!!

**Comment by arturoc** [comment]
in msys2 we use the same system as in linux now, the opencv version as well as other libraries depend on the version installed in the system, in ubuntu right now is 2.4.9 but for next release, which happens in april, it'll be 3.0 surely, in archlinux is probably 3.0 already.

we should just test this changes with 2.4.9 and if they work too just merge them or add a couple of idefs in case they don't.

**Comment by oxillo** [comment]
All the functions are part of 2.4.9 so it should work on platforms with 2.4.9....

**Comment by arturoc** [comment]
oh, yes actually this is compiling in the tests for both linux and osx which compile the allAddonsExample which includes opencv so it seems to be correct. i'm going to merge it then, thanks!

**Pull request merged**
