### PR TITLE
Refactoring ofxGui

### PR DESCRIPTION
**Pull request by frauzufall**
Refactored ofxGui version with new controls, layouts, options..

### CODE REVIEW

**Comment by arturoc** [comment]
thanks!

**Comment by tpltnt** [comment]
@arturoc what is blocking this pull request from being merged?

**Comment by frauzufall** [comment]
@tpltnt I tested this using a pretty complex scenario and found some flaws that had to be addressed. We did this in a Berlin meet-up a few weeks ago and made a plan (~ http://piratepad.net/oWFWVyvdb9) So it might take a little longer to complete this.

@arturoc the json lib isn't part of the core yet, is it?

**Comment by ofZach** [comment]
re: json this library seems promising: 
https://github.com/nlohmann/json

**Comment by frauzufall** [comment]
Jepp, I think that's the one we talked about :)

**Comment by arturoc** [comment]
yes that's the one we are going to include i think the syntax is really nice so we don't even need to wrap it or anything just have it there so we give support for json in the core and addons.

@tpltnt we are on a patch only release cycle right now:

https://github.com/openframeworks/openFrameworks/milestones/0.9.1

once the remaining issues are closed we'll release 0.9.1 and then we can begin to merge the PRs milestoned for 0.10 like this one. in general take a look at the milestoned bugs to see what's scheduled for the current release cycle

**Comment by tpltnt** [comment]
what is left to do to merge this pull request?

**Comment by frauzufall** [comment]
TODO:

- Config classes need to be changed into JSON attributes (I will be working on that)
- the example application in examples/gui/advancedGuiExample freezes on exit and I can't find a way to resolve this (help is very much welcome, I already wrote @arturoc)
- since this PR changes ofxGui quite a bit we also wanted to give it a modern look ( @fx-lange wanted to ask someone with design background)

There are more requests and enhancements but they will not be part of this PR. The aim of this PR is to provide a gui that is highly extensible and to apply this extensibility by adding more controls and containers.

**Comment by brucelane** [comment]
+1

**Pull request closed without merging**
