### PR TITLE
preprocessor fixes for OS X 10.12 for QTKit and QuickTime

### PR DESCRIPTION
**Pull request by ofTheo**
Don't merge just yet. 
Running some checks on 10.11 / Xcode 8

Should address the issue in #5264

### CODE REVIEW

**Comment by ofTheo** [comment]
Okay this branch should build now for the 10.12 SDK. 
( I tested on 10.11 but building against 10.12 SDK which previously didn't work with 0.9.3 download ) 

The video grabber took a bit of work and there are a couple of small things marked in there as TODOs: but it seems to work well with the cameras I had available to test. 

Would be great if others could try this out. 
Ping @danzeeeman @danoli3 @i-n-g-o

**Comment by danoli3** [comment]
I'll have a look! Awesome work Theo!

**Comment by i-n-g-o** [comment]
hi

compiled without problems on 10.11 with XCode Version 8.0 (8A218a) and 10.12 SDK

running the grabber example with internal FaceTime camera crashes in ofAVFoundationGrabber when setting up the device:
```
device.activeVideoMinFrameDuration = CMTimeMake(1, framerate);
device.activeVideoMaxFrameDuration = CMTimeMake(1, framerate);
```

> An uncaught exception was raised
> The activeVideoMinFrameDuration passed is not supported by the device.  Use -activeFormat.videoSupportedFrameRateRange to discover valid ranges.

using one of `device.activeFormat.videoSupportedFrameRateRanges` does not improve the situation...
the only chance to make it run for me is to disable the two lines.

**Comment by ofTheo** [comment]
Thanks for checking! 
Yes, that was the issue I ran into with the orbecc camera too. Had to comment those lines out, even though I was giving valid framerates. 

Going to look into this issue more as well as performance difference between specifying rgb vs bgra capture in the setup.

**Comment by i-n-g-o** [comment]
there is something weird with min/max rates.

i set the framerate to 15, but it tries to set 29.97.
that is, because first entry in `supportedFrameRates` is 30fps. would need to check if desired rate is within min/max.

maybe better then to use `AVFrameRateRange` and set it's `minFrameDuration` and `minFrameDuration`?
this is from an example:
```
device.activeVideoMinFrameDuration = bestFrameRateRange.minFrameDuration;
device.activeVideoMaxFrameDuration = bestFrameRateRange.maxFrameDuration;
```

**Comment by ofTheo** [comment]
Thanks @i-n-g-o ! 
I think I got a fix for the fps stuff based on your comment.  It works for me at least. 

I also fixed some issues where you could get a crash if you specified a capture size that wasn't supported by the device. Now it finds the closest matching dimensions to the size requested.  

I also switch the capture format back to BGRA and am now using the accelerate framework to do conversion to RGB.  This should support more devices, as some won't give you a raw RGB stream. 

I think this should be good to merge for the 0.9.4 hotfix release.  
Would be great if you and others could try it out with their setups. 

Cheers!
Theo

**Comment by i-n-g-o** [comment]
nice. great work!

looks good to me. :)

**Comment by ofTheo** [comment]
Thanks @i-n-g-o 
Does this branch now not crash for you?

Cheers!
Theo

**Comment by i-n-g-o** [comment]
sorry, to have been too unspecific...
yes, the branch now does not crash anymore for me.

but, i had another look to verify that the desired framerate gets set...
it seems it needs a `ceil` instead of a `floor` for `range.maxFrameRate`:

`if( (floor(range.minFrameRate) <= framerate && ceil(range.maxFrameRate) >= framerate) ){`

otherwise e.g. framerate 15 does not get set.
in my case both `minFrameRate` and `maxFrameRate` gives 14.999993 when logging with NSLog. using floor for min/max let's it fail and the framerate does not get set.

cheers
io

**Comment by ofTheo** [comment]
Thanks @i-n-g-o - that changes also worked for my devices too.  
Okay, I think this is in a pretty good place to merge. 
Will merge tomorrow with 0.9.4 branch

**Comment by heaversm** [comment]
This merge should have resolved the issues with the videoGrabber and videoPlayer examples, correct? I am still having a problem building these projects on OSX 10.12 with XCode 8.3:

screen shot 2017-04-06 at 10 42 45 am

**Pull request merged**
