### PR TITLE
Get duration for Sound Players

### PR DESCRIPTION
**Pull request by NickHardeman**
Also added MS MIT license to top of ofMediaFoundationSoundPlayer.h.
Relevant forum post. https://forum.openframeworks.cc/t/ofsoundplayer-length/11560

Has only been tested on OSX using the soundPlayerExample. 

```
tempStr = "click and drag\npct done: "+ofToString(beats.getPosition())+"\nspeed: " +ofToString(beats.getSpeed())+"\n"+ofToString(beats.getPosition()*beats.getDuration(),2)+" / " +ofToString(beats.getDuration(),2);
	ofDrawBitmapString(tempStr, widthDiv+50,ofGetHeight()-50);
```

### CODE REVIEW

**Comment by ofTheo** [comment]
Ahh, the checks point to ofBaseSoundPlayer needs virtual:
`getDurationMS` and `getDuration`

**Comment by NickHardeman** [comment]
Whoops, forgot that file 😊

**Comment by NickHardeman** [comment]
The duration only gets set if the file is not streaming.

**Comment by NickHardeman** [comment]
I couldn't find any documentation regarding this line for the iOS sound player. Just assuming it's milliseconds, but could be frames?
https://github.com/openframeworks/openFrameworks/blob/120c182bbf165f905616a528cd3d56502905b740/addons/ofxiOS/src/sound/ofxOpenALSoundPlayer.cpp#L118

**Pull request merged**
