### PR TITLE
bugfix for drawing wireframe and verts on an assimp model. closes #4553

### LINKED ISSUE #4553: ofxAssimpModelLoader drawVertices drawWireframe doesn't work.
Trying to draw a wireframe or point version of a model draws the model with faces. 
However getting the meshes from the model and calling drawVertices does work. 

It looks like it might be this line:
https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp#L749

The #ifndef should be #ifdef ? 

Changing that fixes the issue on OS X.

### PR DESCRIPTION
**Pull request by ofTheo**
see #4553 
added checks to avoid calling glPolygonMode too many times.

### CODE REVIEW

**Comment by arturoc** [comment]
mmh, doesn't seem correct, if the passed type is wireframe for example, it'll be set to faces at the end but then never set back to wirframe later no?

also i'm just checking and the renderer has a way to do this so just call:

```
ofGetCurrentGLRenderer()->draw(mesh.vbo, renderType);
```

btw, the travis servers we've setup check the PRs in almost every platform so it's good practice to leave it run until it tests every platform to check that nothing is wrong before merging

**Comment by ofTheo** [comment]
@arturoc  thats what I intended. 

I'm assuming here that before the draw call glPolygonMode is set to Faces. 
So the function always restores the state to faces after it finishes drawing all the meshes.  

If you call model.drawWireframe() it should end up restoring it to faces after the end of the drawWireframe() call. 

Thinking about it though - I don't need to be doing the glPolygonMode in the loop. 
All meshes get drawn with the same mode so it could just be set once. 

Happy to push the push/pop attributes back if you think thats a better approach.

**Comment by arturoc** [comment]
i think the best would be to call the renderer which already does the right thing

**Comment by ofTheo** [comment]
@arturoc - sorry somehow missed the ofGetCurrentGLRenderer() part of your reply. 
That makes total sense. Better to have less GL calls in the code too.

**Comment by ofTheo** [comment]
@arturoc - so the issue with `ofGetGLRenderer()->draw(mesh.vbo, renderType, 0, mesh.vbo.getNumVertices());` 
is that you don't get outlines of the triangles as you do with glPolygonMode. 

It looks like this: 
screen shot 2015-11-16 at 12 05 38 pm

vs: 
screen shot 2015-11-16 at 12 06 49 pm

Without using glPolygonMode I think we would need to create a new mesh to draw triangles as outlines. 
As GL_TRIANGLES can't easily be converted to GL_LINE_LOOP ( needs multiple begin / end ) and GL_LINES expects a pair of points per line.

**Comment by julapy** [comment]
in the past ive written helper functions which convert a GL_TRIANGLE_STRIP mesh to a GL_TRIANGLES mesh, which can then be drawn as a wireframe.

i don't think this should be done internally or automatically.
but maybe these ofMesh helper functions should be included inside ofMesh as static functions?

**Pull request merged**
