### PR TITLE
Add PUT request to ofURLFileLoader

### PR DESCRIPTION
**Pull request by chriship**
Add the ability to do a PUT request with ofHttpRequest

### CODE REVIEW

**Comment by arturoc** [comment]
you've based this PR of off master and sent it to patch-release, that's why all this extra commits from other people appear in the PR. Since it's a new feature can you send it against master instead?

thanks!

**Comment by chriship** [comment]
Oops! I've changed the base branch to master - does that work?

**Comment by arturoc** [comment]
I'm not sure it's really necessary but we reset the method on every request so the same way we set GET and POST to 0 when doing PUT. PUT should be reset to 0 when doing POST and GET. can you add that?

**Review by danoli3 — APPROVED** [review]
Yes

**Comment by danoli3** [comment]
Rebased / Merged and added @arturoc 's PUT to 0 change.

**Pull request merged**
