### PR TITLE
ofDocSprint

### PR DESCRIPTION
**Pull request by nicoleyimessier**
Added Readme files & screenshots to the following examples:
graphics >>
imageLoaderExample
imageSaverExample
color

math >>
periodicSignalsExample
noise1dOctaveExample
trigonometryExample
vectorMathExample

### CODE REVIEW

**Comment by bakercp** [comment]
What is the difference between `examples/doc-sprint-example-category/` and `examples/graphics/graphicsExample`?

**Comment by caitlinmorris** [comment]
@bakercp ```examples/doc-sprint-example-category/``` is a template -- ```examples/graphics/graphicsExample``` is the actual example for that folder

**Comment by bakercp** [comment]
Got it, but I'm interested in this directory though:

https://github.com/grayfuse/openFrameworks/tree/nicole/examples/doc-sprint-example-category/graphicsExample

It seems like there is an example inside of the template that is copy of `examples/graphics/graphicsExample`.

**Comment by nicoleyimessier** [comment]
@bakercp @caitlinmorris this was added as an example of a filled out template rather than the empty template (i.e. the template with the kitten example)

**Comment by bakercp** [comment]
@grayfuse please rebase against master

**Comment by bakercp** [comment]
@grayfuse please rebase against master

**Pull request merged**
