### PR TITLE
Apothecary: Poco 1.6 + OpenSSL 1.0.1j - libs, core

### PR DESCRIPTION
**Pull request by bakercp**
This PR supersedes all existing Apothecary Poco PRs.

The Apothecary formulae are now in the master branch.  This PR will only include core code changes and ultimately static libs and new headers.

For now, this branch will serve as the basis for testing the newest Poco formulae and when we're satisfied, we can include the libs and merge this one.

This will also include the libs for openssl 1.0.1j, since Poco is compiled against 1.0.1j.

Built openssl libs

- [x] OSX FAT (@bakercp)

Built poco libs

- [x] OSX FAT (@bakercp)

TO BUILD UPDATED STATIC LIBS AND TEST  PLATFORM:

0. Make a comment below if you are testing a platform.
1. Create and check out a fresh branch off of master.
2. Pull in this branch.
3. Change directories to `openFrameworks/scripts/apothecary`
4. Run `./apothecary update openssl` to update openssl.
5. Run `./apothecary update poco` to update poco.
6. Run test programs.  
7. If successful, create a PR against this branch with _static libs only_.  Don't include the new headers generated by the apothecary scripts.  We'll do that all at once.

This branch is a staging and testing branch:

https://github.com/bakercp/openFrameworks/tree/develop-apothecary

- Currently is synced w/ master, bakercp:apothecary-poco-libs and includes openssl / poco headers generated by apothecary static libs above.

### CODE REVIEW

**Comment by pkmital** [comment]
On OSX Yosemite, I had problems building Poco w/ apothecary for 64-bit.  It finished building 32-bit fine and collapsed on the 64-bit library.  In the log file, it showed that it could not find "wchar.h":

```
openFrameworks/scripts/apothecary/build/poco/build/osx$ cat poco-make-x86_64-1.6.0-release.log

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -Iinclude -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/CppUnit/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/CppUnit/WinTestRunner/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Foundation/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/XML/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/JSON/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Util/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Net/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Crypto/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/NetSSL_OpenSSL/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Data/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Data/SQLite/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Data/ODBC/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Data/MySQL/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Zip/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/PageCompiler/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/PageCompiler/File2Page/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/PDF/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/CppParser/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/MongoDB/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/PocoDoc/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/ProGen/include -arch x86_64 -std=c++11 -stdlib=libc++ -Wall -Wno-sign-compare -Wno-unused-variable -Wno-unused-function -Wno-unneeded-internal-declaration -DPOCO_BUILD_HOST=pkm.local  -DPOCO_HAVE_IPv6 -DPOCO_NO_STAT64  -O0 -g -gdwarf-2 -fasm-blocks -D_DEBUG=   -c src/ArchiveStrategy.cpp -o /Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Foundation/obj/Darwin/x86_64/debug_static/ArchiveStrategy.o
In file included from src/ArchiveStrategy.cpp:17:
In file included from include/Poco/ArchiveStrategy.h:23:
In file included from include/Poco/Foundation.h:148:
In file included from include/Poco/Bugcheck.h:24:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:435:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:90:10: fatal error: 'wchar.h' file not found
#include <wchar.h>  // for mbstate_t
         ^
1 error generated.
make[1]: *** [/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Foundation/obj/Darwin/x86_64/debug_static/ArchiveStrategy.o] Error 1
make: *** [Foundation-libexec] Error 2
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Foundation
** Compiling src/ArchiveStrategy.cpp (debug, static)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -Iinclude -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/CppUnit/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/CppUnit/WinTestRunner/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Foundation/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/XML/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/JSON/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Util/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Net/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Crypto/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/NetSSL_OpenSSL/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Data/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Data/SQLite/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Data/ODBC/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Data/MySQL/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Zip/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/PageCompiler/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/PageCompiler/File2Page/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/PDF/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/CppParser/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/MongoDB/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/PocoDoc/include -I/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/ProGen/include -arch x86_64 -std=c++11 -stdlib=libc++ -Wall -Wno-sign-compare -Wno-unused-variable -Wno-unused-function -Wno-unneeded-internal-declaration -DPOCO_BUILD_HOST=pkm.local  -DPOCO_HAVE_IPv6 -DPOCO_NO_STAT64  -O0 -g -gdwarf-2 -fasm-blocks -D_DEBUG=   -c src/ArchiveStrategy.cpp -o /Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Foundation/obj/Darwin/x86_64/debug_static/ArchiveStrategy.o
In file included from src/ArchiveStrategy.cpp:17:
In file included from include/Poco/ArchiveStrategy.h:23:
In file included from include/Poco/Foundation.h:148:
In file included from include/Poco/Bugcheck.h:24:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:435:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:90:10: fatal error: 'wchar.h' file not found
#include <wchar.h>  // for mbstate_t
         ^
1 error generated.
make[1]: *** [/Users/pkmital/pkm/dev/openFrameworks/scripts/apothecary/build/poco/Foundation/obj/Darwin/x86_64/debug_static/ArchiveStrategy.o] Error 1
make: *** [Foundation-libexec] Error 2
```

After running:

```
$ xcode-select install
```

"./apothecary build poco" finished without any problems.

**Comment by bakercp** [comment]
@arturoc @danoli3 @ofTheo I've been running a branch with these changes (i.e. the new Poco updates) for a few months now and it all seems to be pretty solid.  If it's OK, I'm going to update this PR with the latest OpenSSL, recompile the new Poco libs and upload the latest binaries in the next week or so.  The main reason we're waiting on this is because the headers change slightly with 1.6.0, meaning we can't just recompile libs.  Anyway, as long as there's nothing major that would clash with this, I think we should go for it.

**Comment by ofTheo** [comment]
@bakercp feel free to close this PR if these libs are the same as the ones in the master now ( they were built with the latest formulas )

**Comment by bakercp** [comment]
Yep, I think this is covered.

**Comment by bakercp** [comment]
Oh wait ... there are some windows things in here.  I'm checking on this ...

**Comment by danoli3** [comment]
Hey @bakercp I just cherry picked the changes you had in this PR that are not in the master branch yet.

**Comment by danoli3** [comment]
You may be able to close this PR now in favour of this: https://github.com/openframeworks/openFrameworks/pull/3959

**Comment by bakercp** [comment]
Cool! Thanks for all the work!

**Pull request closed without merging**
