### PR TITLE
Apothecary - FreeType 2.5.0 Core oF changes [Merge after library updates]

### PR DESCRIPTION
**Pull request by danoli3**
Changes for updated FreeType library.

ofTrueTypeFont path fixes for FreeType 2.5.0+
-----------

FreeType changed the library file structure in 2.5.0+ so needed to fix this
Someone had this problem before http://forum.openframeworks.cc/t/missing-of-lib-include-files/14326/3
Fixed in danoli3@12ca5fb

Merge after libraries for FreeType have been built with
https://github.com/openframeworks/openFrameworks/pull/3453

### CODE REVIEW

**Comment by danoli3** [comment]
@arturoc This PR did also include those Android makefile changes for the new libraries. 
As well as the FreeImage location changes. 

Got a bit confusing as this also had the FreeImage cherry-pick merged into this as well.

**Comment by danoli3** [comment]
Maybe git reset --hard ffd7ff44e038f5e07d6f1cbd1241a56794125628 (the oes_patch merge). then reopen this again.

**Comment by danoli3** [comment]
Oh wait I see what your doing :D!

**Comment by arturoc** [comment]
:) yeah sorry i needed the android formulas since android wasn't compiling at the moment with the latest ndk

**Pull request merged**
