### PR TITLE
ofEvent cleanup

### PR DESCRIPTION
**Pull request by tpltnt**
Hi,

i fixed some style issues, added documentation and fixed a missing assignment in ofEvent.h
Cheers,
tpltnt

### CODE REVIEW

**Comment by ofZach** [comment]
thanks for these changes...  just a quick note that we are using tabs as per https://github.com/openframeworks/openFrameworks/wiki/oF-code-style

**Comment by tpltnt** [comment]
@ofZach so the spacing is done with tabs which are 4 colums wide, and not 4 spaces instead of tabs?

**Comment by ofZach** [comment]
In your editors preferences you can set tabs to be 4 spaces wide.  We just don't use spaces for indentation in the code since keeping it as tabs means its configurable for the end user.

**Comment by tpltnt** [comment]
Ok, i also adjusted the style guide to make it more clear, so others aren't as mistaken as i was.

**Comment by bilderbuchi** [comment]
@tpltnt I don't know if you know, but we have a tool that can do style changes automatically, using uncrustify: https://github.com/openframeworks/openFrameworks/tree/master/scripts/dev/style

**Comment by tpltnt** [comment]
@ofZach i fixed the tab issue.
@bilderbuchi thank you for the hint.

**Pull request merged**
