### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by bakercp**
Warnings showing up during linux compile.

### CODE REVIEW

**Comment by bakercp** [comment]
@arturoc thoughts here?

**Comment by arturoc** [comment]
i think i added this because at some point that substraction can return a negative number and that will probably crash the app trying to access a wrong position in memory. perhaps we can just cast the other side to int64_t?

**Comment by bakercp** [comment]
Since `nFrames` and `fromFrame` are both now unsigned, how about:

```
if ((fromFrame + nFrames) >= getNumFrames())
{
      nFramesToCopy = getNumFrames() - fromFrame;
}
```

**Comment by bakercp** [comment]
ping @arturoc -- solution above work?  I'm trying to avoid casts ...

**Comment by bakercp** [comment]
@admsyn does this look ok to you?

**Comment by bakercp** [comment]
If so, I'll update the PR and merge.

**Comment by bakercp** [comment]
@arturoc I implemented the above fix.  Let me know if it looks OK and I'll merge (or feel free to do it yourself).

**Comment by arturoc** [comment]
yeah that looks correct, thanks!

**Comment by bakercp** [comment]
+1.  Thanks @arturoc

**Pull request merged**
