### PR TITLE
GLFW transparent window background touch/click pass through

### PR DESCRIPTION
**Pull request by danoli3**
As mentioned on the forums here:
https://forum.openframeworks.cc/t/transparent-window-app-with-mouse-click-pass-through/43816

# GLFW Window clear transparency - mouse passThrough 
 - GLFW 3.4 + supports click pass through with these commands

Changes additional bools for GLFW settings.
- bool mousePassThrough; // input pass through for transparency window
- bool floating;  // type of window 

Thanks to @artificiel for documenting floating / passThrough info 

usage would be something like in main.cpp:
```
ofGLFWWindowSettings settings;
settings.transparent = true;
settings.mousePassThrough = true;
settings.floating = true;
settings.decorated = false;
```

Example:

transparentWindow

### CODE REVIEW

**Comment by danoli3** [comment]
I made an example as this requires a bit of main.cpp setup and understanding of the limitations and powers of this passThrough.

transparentWindow

**Comment by artificiel** [comment]
I wonder if `.transparentInput` is the correct base name for the click through feature? adopting GLFW naming would make things more auto-documented, so `.mousePassthrough` to shadow `GLFW_MOUSE_PASSTHROUGH`?

likewise, `ofSetWindowMousePassthrough(bool)` instead of `ofSetWindowTransparencyInput(bool)`?

unless "transparent input" is a term commonly used?

**Review by danoli3 — COMMENTED** [review]
Updated with better variables / function names

**Review by danoli3 — COMMENTED** [review]
Awesome this is looking ready, now!

**Comment by danoli3** [comment]
Okay rechecked this bad boi going to merge

**Pull request merged**
