### PR TITLE
apothecary: remove harfbuzz dependency from freetype

### PR DESCRIPTION
**Pull request by tgfrerer**
As @carthach pointed out in #3627, freetype might fail to work in some cases since an optional dependency to harfbuzz (a utility to parse extended OpenType features) has not been met. 

Since we haven't included & compiled harfbuzz in the past (and freetype for homebrew is fine without it) it seems a sensible choice to compile freetype without it.

If we wanted to include Harfbuzz, we'd need to add a dependency for harfbuzz 0.9.19 or newer: <http://sourceforge.net/projects/freetype/files/freetype2/2.5.3/> 

But this would create a catch22 while compiling, because harfbuzz, in turn, depends on Freetype.

We also have had a flag to exclude harfbuzz from android builds for a while. I wonder if we should exclude it from iOS builds, as well... 

ping @bakercp

### CODE REVIEW

**Comment by arturoc** [comment]
hey, yeah we've talked about including harbuzz but will leave it for next release so if you can exclude it from iOS too?

**Comment by tgfrerer** [comment]
done =)

**Comment by arturoc** [comment]
great!

**Comment by bakercp** [comment]
Yep, harfbuzz is an important part of our ofFont future, but we're skipping it for now.

**Pull request merged**
