### PR TITLE
fix c++17 std::filesystem error.

### PR DESCRIPTION
**Pull request by 2bbb**
added process switching with macro about std::filesystem::permissions.

cite:
* TS/experimental API
  * https://en.cppreference.com/w/cpp/experimental/fs/permissions
  * https://en.cppreference.com/w/cpp/experimental/fs/perms
* c++17 API
  * https://en.cppreference.com/w/cpp/filesystem/permissions
  * https://en.cppreference.com/w/cpp/filesystem/perms
  * https://en.cppreference.com/w/cpp/filesystem/perm_options

### CODE REVIEW

**Comment by 2bbb** [comment]
ping @arturoc @bakercp @ofTheo

**Comment by arturoc** [comment]
Can you explain a bit better what this is doing?

**Comment by 2bbb** [comment]
@arturoc
boost::filesystem, std::experimetal::filesystem and std::filesystem have a different API.
this PR absorbs it.

**Comment by arturoc** [comment]
I see, thanks!

**Pull request merged**
