### PR TITLE
Fmod Update to 4.44.59

### PR DESCRIPTION
**Pull request by danoli3**
FMOD Update 

- Fixes part 3 of https://github.com/openframeworks/openFrameworks/issues/4619

### CODE REVIEW

**Comment by arturoc** [comment]
moving the discussion here since the other PR is not related. 

The problem with updating fmod is that it produces this problem:

https://github.com/openframeworks/openFrameworks/issues/3851

there's some workarounds but the ideal would be to not have the problem at all.

if i understand it correctly this would fix some signature problem with fmod in osx, isn't there a different fix for this that would still use the old version of fmod?

**Comment by danoli3** [comment]
No fix other than the new FMOD i'm afraid. 
Can we report this issue to FMOD? FMOD Ex is still maintained and active.

**Comment by arturoc** [comment]
another possible fix by now would be to have soundstream call ofFmodSetRate() in osx whenever a new soundstream is created

**Comment by danoli3** [comment]
That's probably the perfect fix yeah

**Comment by danoli3** [comment]
Okay made that change. Tested it. All good no horrible noise with latest. Tried an assertion of different buffer sizes too. All good.

**Comment by danoli3** [comment]
Okay I update the Apothecary script, yeah we totally forgot the license file before.
Also Added the export directory now.

**Pull request merged**
