### PR TITLE
The Great Android Update - Updated 2024

### PR DESCRIPTION
**Pull request by danoli3**
The Great Android Update [Updated 2024]

2024
- Updated and rebased onto of merge.
- Updated with @tctr changes 

Android Studio Latest and Android Studio Preview working

Most of this work was completed as apart of Super Hexagon Android Port and is active and live (super stable)
Big ups @TerryCavanagh 

2021 / 2022
Gradle Updated Build Gradle 7.0.0 / 7.10.0
- Android X Supported
- NDK 24
- All Architectures Supported = 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
- CMake Build System Support
- Android.mk Build System
- Reduced dependancies with C++17
- Build Tools 31.0.0
- Supports All API's from 18->31 (Android 5 all the way to Android 12/Android 11)
- Gradle Implementation updated to latest android
- Dependancies Updated compiled with NDK via Apothecary and updated for all achitectures
- FreeImage Patched for Android / C++17
- ReLinker for System.Lib Load (Google Recommended)
- Supports different Frame Rates of the device now, returning max by default, configurable) - 90 hz phones, 120 hz, 240 hz, 30 hz etc. Can be dynamically changed in app
- Can Build Android Bundles / Signed Releases
- Compatible now with all external Prefabs/implementations via gradle and newer NDK's
- High performance MSAA options
- GL Surface Rebuildable at any time
- Tested across All API's
- Android Bug Fixes

Performance increased so much (13ms->2ms same code in tests)!

- Life Cycle Fixes - The prior attempts at lifecycle fixes for GL Context and Surface pausing/re-loading all failed across numerous API's for various reasons. These have all been fixed and tested across all API's.
- Fix countless crashes
- Sound Engine Fixes
- SD Card / Reading / Location Fixes
- Permission Fixes
- More to list
- Windowing Fixes
- GL Threaded Key Events / Controller
- Download external built libs here via apothecary https://github.com/openframeworks/apothecary/pull/201 (NDK 23.1 Compiled:)

https://drive.google.com/file/d/1XBKfqZedQOy_UoW3HXCZ21q0-KXN1v77/view?usp=share_link
Extract the libs from zip into openFrameworks/libs/ *

Or download via download_latest_libs.sh in scripts/android/

[ ] Merge issues identified (it was huge rebase merge)

### CODE REVIEW

**Comment by danoli3** [comment]
Okay I see some of the merged contains libs so I'll figure out what happened there with @tctr and redo this one! 
On the path

**Comment by tctr** [comment]
Hey great work ! Yes, sorry for convenience I had added some libs in my fork !

**Comment by tctr** [comment]
yes this is this commit : `c45a85017cca485f7d8ec525c4411` where I added the libs manually and not using `download_libs.sh`. This commit can be easily removed with interactive rebase. I can do it if you prefer.

image

Also I've got a commit `dbf8f55f0fcf666494233bbbe5b` where all the .gitignore are deleted. It should also be removed I guess !

**Comment by danoli3** [comment]
@tctr updating this now, just cherry picking everything since that library! looking good

**Pull request closed without merging**
