### PR TITLE
ofMaterial PBR advanced example

### PR DESCRIPTION
**Pull request by NickHardeman**
Set the shader main functions for the materials without recompiling, PBR material with textures and clear coat. Cube map and a light with shadows.

materialPBRAdvancedExample

### CODE REVIEW

**Comment by NickHardeman** [comment]
> Hey @NickHardeman thanks for all this great work! I'm having an issue on latest, on both examples :
> 
> ```
> Unknown type name 'ofCubeMap'
> ```

Hi @dimitre, what platform are you on? Did you use the project generator?

**Comment by dimitre** [comment]
Yes macOS, command line project generator.

**Comment by dimitre** [comment]
it runs if I add this to ofMain.h
#include "ofCubeMap.h"

**Comment by NickHardeman** [comment]
Do you know what the command line pg compiles against? does it use the make files? 
I updated the openFrameworksCompiled/project/osx/openFrameworksLib.xcodeproj. Is there something else I need to update? I don't have much experience with the pg on the command line
Also, thanks for checking it out!

**Comment by dimitre** [comment]
I think the electron app invokes the command line, so it should be the same output.

**Comment by NickHardeman** [comment]
Thank you for testing and catching this. Submitted a pr that should fix it #7233

**Pull request merged**
