### PR TITLE
Fixes osx ofToDataPath. See openframeworks/projectGenerator#22

### PR DESCRIPTION
**Pull request by arturoc**
In osx when OF starts it sets the current directory to the directory
where the exe is located and then uses a relative path from there to
correctly find the data folder.

This has several problems:

- The current working directory is not correct anymore, mostly for command
line applications is useful to know where the command was run from. This is
for example making the command line PG fail in osx and would require a hack
like https://github.com/openframeworks/projectGenerator/pull/22, in general
people would need to know that OF internally changes the cwd but even with
that the actual cwd is totally lost so there's no way to recover it except
by queryng $PWD which is not multiplatform

- If someone changes the current working directory using setcwd or std::current_path
the data folder won't be found anymore

Instead of that this commit changes the data path to EXE_DIR/../../..data
which always works no matter if the cwd is changed by the application or
where the application is run.

This also changes `ofFilePath::getCurrentWorkingDir` which right now is returning
the exe dir instead of the cwd

### CODE REVIEW

**Comment by ofZach** [comment]
one option would be to add this code we remove in this PR just to ofAppGlutWindow since as I recall this is specific to glut on osx trying to automagically change the CWD and having wonkiness (like the data folder not being found) w/ glut apps because of the app's propensity to guess where you want the CWD to be and change it.  It's also a setting in the app itself: 

screen shot 2015-08-25 at 4 56 43 am

I remember this code was specifically to override what glut is doing.

**Comment by arturoc** [comment]
i don't think we should have the current fix anywhere. this would work for glut too, and the current way is really strange since it even overrides the menu option and sets a cwd which is not even the correct one

**Comment by ofZach** [comment]
sorry there's two conversations happening.  I think IMO the real offender is glut for changing the cwd auto-magically (and often times spuriously), I think even just adding a function in ofAppGlutWindow that has this behavior documented might be enough, so we don't do this cwd fix by default, but if you are using glut and you want to normalize your cwd you can.    I feel like at least having the option around might be good.

**Comment by arturoc** [comment]
:) yes i remember osx being problematic with version changes and ofToDataPath. I've added an ofRestoreWorkingDirectory which restores the working directory to whatever was when the app was started before creating any window so that should solve the problem without explicitly setting it to the exe dir.

I'm not calling it from anywhere but we could call it from the glut window if you think it's better.

**Comment by arturoc** [comment]
i'm merging this, since it fixes a problem with the command line PG and is behaving now the same as before with ofAppGlutWindow

**Comment by armadillu** [comment]
Hey this broke relative paths?

Before this, ofToDataPath("file.txt", false) would return a relative path (i.e. ../../data/file.txt). Now it's always absolute regardless of the provided "bool makeAbsolute" argument...

**Comment by arturoc** [comment]
in which case do you need relative paths? it's more robust this way since it'll always do the right thing no matter where you call the application from

**Comment by bakercp** [comment]
For me, I use relative paths when saving settings and doing configurations, etc.

**Comment by arturoc** [comment]
what do you mean? you can still specify relative paths is just ofToDataPath which would turn the passed path into a canonical absoulte one

**Comment by armadillu** [comment]
yeah loading assets, etc... let's say I have a project with asses specified on the XML... having relative really makes it easy to move binaries from dev to deployment machine, etc. I think it's pretty crucial.

**Comment by arturoc** [comment]
oh you mean when you store the path returned from ofToDataPath?

**Comment by bakercp** [comment]
@arturoc yes

**Comment by armadillu** [comment]
yep, here for example https://github.com/armadillu/ofxTextureAtlas

**Comment by arturoc** [comment]
mmh, ok, i think you should be storing the path before passing it to ofToDataPath(), then when you read it pass it through ofToDataPath that way it'll still work and would be even multiplatform

but let me check if i can make the final path into a relative to data

**Comment by bakercp** [comment]
@arturoc you're probably right.  just backward compat, etc.  MOST of the time I always ask for absolute paths anyway.

**Pull request merged**
