### PR TITLE
fixed 'deprecated-declarations' warnings in soundBufferExample

### PR DESCRIPTION
**Pull request by tpltnt**
yet another letfover from #3855.
Cheers
tpltnt

### CODE REVIEW

**Comment by ofTheo** [comment]
I think from the discussion here ( see: #2581 ) the plan is to use std:: in core files but in examples and ofApp not include std:: as it will still have `using namespace std;` in ofMain.h 

ping @openframeworks/core 
@arturoc @tgfrerer to confirm

**Comment by tgfrerer** [comment]
Yes, that makes sense. We can add `using namespace std` to some core **.cpp** files, especially when it makes code (and git diffs) more readable, but would strive to remove it from any core **header** files, as it  "infects" the global namespace in counter-intuitive ways.

So any use of `STL` elements would eventually need the `std::` prefix in core header files.

**Comment by tpltnt** [comment]
@ofTheo thanks for pointing it out. I will read through it.

**Comment by ofTheo** [comment]
@tgfrerer thanks for the quick reply 
It might be good to get this written up somewhere ( wiki? ) so its clear what our approach will be to the std:: namespace going forward. 

@tpltnt no problem! could you update the PR without the std:: prefix? 
thanks!!!

**Comment by bilderbuchi** [comment]
> It might be good to get this written up somewhere ( wiki? ) so its clear what our approach will be to the std:: namespace going forward. 

"somewhere" should probably be the [code style](https://github.com/openframeworks/openFrameworks/wiki/oF-code-style) wiki page.

**Comment by tpltnt** [comment]
@ofTheo i removed the `std::` prefix as you suggested. I also updated the [oF code style page](https://github.com/openframeworks/openFrameworks/wiki/oF-code-style) with the section "Namespaces (esp. 'std')" @tgfrerer @bilderbuchi.

**Comment by ofTheo** [comment]
thanks @tpltnt !!

**Comment by bilderbuchi** [comment]
@tpltnt unfortunately, you got it the other way round in the wiki page edit - `using namespace std` in core cpp files is OK (as this doesn't propagate via `#include`). In core _header_ files, we should use `std::` forms so the global namespace doesn't get polluted when those headers get included elsewehere, see [this comment](https://github.com/openframeworks/openFrameworks/pull/4012#issuecomment-117204680)

fwiw, I disagree with @tgfrerer a bit in that I think we should use `std::` _everywhere_, just for consistency's sake, so that there is no confusion about what version you can/should use where, etc.

**Comment by tpltnt** [comment]
@bilderbuchi good catch, but the edit was shorter than your comment ;)

**Comment by arturoc** [comment]
let's keep using no std in examples for 0.9. i think for next release moving `using namespace std` from `ofConstants.h` into `ofMain.h` could make it easier to transition for beginners. we could also add group headers per folder so including different modules is easier, like ofUtils.h would include everything in the utils folder. that way it's easier to include only what you need without having to include ofMain.h that way more advanced users have a way of not having all of std imported and still have an easy way to include the parts of OF they need

**Pull request merged**
