### PR TITLE
Replace “wget” with “curl -L --retry 20 -O --progress”.

### LINKED ISSUE #5371: download_libs.sh on OSX requires wget - replace with curl
wget doesn't ship with OSX this needs to be installed via brew or macport

### PR DESCRIPTION
**Pull request by bakercp**
Fixes #5371 

Replace `wget $URL` with `curl -L --retry 20 -O --progress $URL`

`-L` follows redirects (the default for `wget`).
`--retry 20` retries failed connections 20 times (the default for `wget`).
`-O` saves the target file with the name on the server (the default for `wget`).
`--progress` Uses a `wget`-like progress bar rather than default curl "meters".

### CODE REVIEW

**Comment by arturoc** [comment]
curl, doesn't come installed by default in at least ubuntu and msys2 or other windows bash terminals so this is fixing one platform but breaking at least 2 or 3. perhaps we can detect which one is present by checking the return code of `which wget` and `which curl` and use one or the other?

**Comment by danoli3** [comment]
Yeah definitely use which and choose, curl being preferable. I'll fix this up for you @bakercp and PR into your branch

**Comment by danoli3** [comment]
Looks like ```command -v``` is the safest bet. 
https://stackoverflow.com/a/677212 

Which has issues on different platforms. I'll set it up with this and a if statement.

**Comment by danoli3** [comment]
Pull request sent @bakercp  https://github.com/bakercp/openFrameworks/pull/26

**Comment by bakercp** [comment]
I just merged @danoli3's stuff.  Thanks sir!

**Comment by danoli3** [comment]
I've been reviewing the developer download process for the libs, I'll make a new PR for adding some commands similar to PS1 clickable that Windows has, except for OSX related lib downloading using command.
Kinda annoying to have to shell and ./download_libs.sh when for simplicity could just be a click on the command script, and all the command script does is call the ./downloader.sh script.

**Comment by arturoc** [comment]
some tests are now failing aparently cause curl is to verbose. can you perhaps run it in silent mode or default to wget if it's available

**Comment by danoli3** [comment]
Can do silent by default on curl, will fix that.

Isn’t it we want curl priority and fallback on wget.

**Comment by arturoc** [comment]
i replaced curl with wget a while ago cause it was more robust so i'd prefer to leave wget as default if it's present

**Comment by danoli3** [comment]
Yeah okay, I'll switch that around.

**Comment by danoli3** [comment]
I'll start this one again with head

**Comment by bakercp** [comment]
@arturoc So is this a no?

**Comment by ofTheo** [comment]
I have run into some issues using curl instead of wget.
I tried doing some of the above, but just ended up installing wget on osx. 

 I think it might be best to close this.

**Pull request closed without merging**
