### PR TITLE
ofScopedLock and ofMutex deprecation

### PR DESCRIPTION
**Pull request by tpltnt**
Hi,

i replaced all occurences of `ofMutex` and `ofScopedLock` since they are deprecated. The documentation is also updated. This should be merged in conjunction with #4012.
Cheers
tpltnt

### CODE REVIEW

**Comment by bilderbuchi** [comment]
hey! just a minor thing, but there's no need to split logically related changes into one commit per file, like you did here -- that just unnecessarily bloats the commit log. ;-)

**Comment by tpltnt** [comment]
@bilderbuchi ok, i will squash them next time. Thank you for the hint.

**Comment by bilderbuchi** [comment]
thanks

**Comment by tpltnt** [comment]
@bilderbuchi i squashed the commits.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
