### PR TITLE
docs_low_level: ofMaterial.h, ofBaseTypes.h, ofURLFileLoader.h, ofSystemUtils.h 

### PR DESCRIPTION
**Pull request by danomatika**
doxygen comment additions for ofSystemUtils, ofURLFileLoader, ofBaseTypes

Also changed ofMaterial header doxygen commenting to regular `//` comments since it's not really documentation but reference links etc that should be moved to markdown.

### CODE REVIEW

**Comment by bakercp** [comment]
Reviewing ...

**Comment by bakercp** [comment]
Hey @danomatika when you get a moment could you take a pass to bring this into alignment with the doxygen style guide https://github.com/openframeworks/openFrameworks/wiki/openFrameworks-doxygen-documentation-style-guidelines?  If you'd prefer to submit as is, let me know and I'm happy to make a pass on it.

**Comment by bakercp** [comment]
Hey @danomatika when you get a moment could you take a pass to bring this into alignment with the doxygen style guide https://github.com/openframeworks/openFrameworks/wiki/openFrameworks-doxygen-documentation-style-guidelines?  If you'd prefer to submit as is, let me know and I'm happy to make a pass on it.

**Comment by danomatika** [comment]
:blush: should eat my own dog food

**Comment by danomatika** [comment]
Done.

**Comment by danomatika** [comment]
Done.

**Comment by danomatika** [comment]
Ok, actually all updated now.

**Pull request merged**
