### PR TITLE
OSX and iOS unified AVFoundation video player.

### PR DESCRIPTION
**Pull request by julapy**

### CODE REVIEW

**Comment by ofTheo** [comment]
wow - awesome to see this @julapy 
any regressions or possible issues to look out for?

**Comment by julapy** [comment]
@ofTheo, no regressions as far as im aware.
things should work all the same on OSX and iOS.
be good to give it a thorough test though...

**Comment by kylemcdonald** [comment]
just for reference, this would help with #2283 and would close #3242. further description of this PR is in https://github.com/openframeworks/openFrameworks/issues/3242#issuecomment-71353036

i suggest where either:

1. trust @julapy and merge immediately to give as much time to test before 0.9.0 is released :) (my preference)
2. wait for 0.9.0, and include this in 0.9.1 as is currently planned (which could be around 6-8 months...)

**Comment by julapy** [comment]
thats what i was thinking as well... since we are going forward with the unified video player, then its better to switch to it now so we can test it and improve it if any issues arise. it will also ensure that any future developments to the video player work on both osx and ios.

**Comment by kylemcdonald** [comment]
@julapy great, then i'd say give this 2-3 more days, then merge if there are no objections from @openframeworks/video and we will make sure to squash any bugs before the next release :)

**Comment by bilderbuchi** [comment]
tbh, I'd rather we not add more features/PRs/issues and testing debt to 0.9.0, and instead slate this for immediate merge after 0.9.0 release - that way, the testing time is maximised before this hits the "public", and we don't have to allocate yet more time to testing this.
either way, I just wanted to give my 2 cents from a release management p.o.v., and will defer to @openframeworks/video for the final decision.

**Comment by kylemcdonald** [comment]
@bilderbuchi i generally agree, but given that the video player is already in flux and will need testing regardless i don't think this adds any testing debt -- just redirects it. and, ideally, it reduces debt by consolidating two implementations.

**Comment by kylemcdonald** [comment]
thanks @ofTheo!

**Pull request merged**
