### PR TITLE
FPS timing with chrono

### PR DESCRIPTION
**Pull request by dimitre**
This PR has the intent of modernize OF framerate managing. 
The idea is using only std::chrono for two reasons : let std::chrono manage all time divisions in the best way possible, and unifying code across platforms.
it was tested in macOS and reduced FPS drift compared to ofTimer implementation

### CODE REVIEW

**Comment by dimitre** [comment]
cc @artificiel

**Comment by ofTheo** [comment]
@dimitre - Awesome! 
Might be good to test on Windows and Linux before merging.

**Comment by dimitre** [comment]
Great! I'll be testing in the next days and report back here.

**Comment by dimitre** [comment]
@artificiel can you please test this PR with your tests mentioned here?
- https://github.com/openframeworks/openFrameworks/issues/7760#issuecomment-1820046935

I think this PR can be a slight improvement to actual FPS. 
and here is also an alternative way of counting FPS

```c++
#include <chrono>
using namespace std::chrono;
using namespace std::chrono_literals;

struct fpsCounter {
public:
	int nAverages = 20;
	using space = std::chrono::duration<long double, std::nano>;
	time_point<steady_clock> lastTick;
	steady_clock::duration onesec = 1s;
	std::vector <space> intervals;
	space interval;
	space average;
	bool firstTick = true;
	int cursor = 0;

	void tick() {
		if (firstTick) {
			firstTick = false;
			lastTick = steady_clock::now();
			return;
		}

		interval = steady_clock::now() - lastTick;
		lastTick = steady_clock::now();
		if (intervals.size() < nAverages) {
			intervals.emplace_back(interval);
		} else {
			intervals[cursor] = interval;
			cursor = (cursor+1)%nAverages;
		}
	}
	
	double getFps()  {
		average = std::reduce(intervals.begin(), intervals.end());
		return (double)intervals.size() * onesec / average;
	}
	
	float get() {
		average = std::reduce(intervals.begin(), intervals.end());
		return (float)intervals.size() * onesec / average;
	}
};
```

**Comment by dimitre** [comment]
finally a decent way of testing fps drift, measuring with ofGetFrameRate, and with chrono.
you can toggle (pressing key "t") between OF classic FPS control and new one to see differences in drift.
```ofw/apps/devApps/fps```
Screenshot 2024-05-08 at 17 02 29

**Comment by dimitre** [comment]
now alternative fps counter has a subtle low pass filter (average of 4 last results) so both modes can be compared better. 
it is a great improvement in macOS. I'll be testing on Ubuntu soon 
Screenshot 2024-05-09 at 00 36 51

**Comment by dimitre** [comment]
Now finally tested in Windows, Linux and macOS, 
Tests show up to 25x more precision, from 10 milliframes drift to 0.3

The idea is using sleep_until and wake processor early (about 35ms early), 
so processor has time to go from low energy (sleep) to high energy and calculate the remaining time in a while loop.

**Pull request merged**
