### PR TITLE
ofAVFoundationVideoPlayer: simplified setVolume

### PR DESCRIPTION
**Pull request by i-n-g-o**
a redo of #3803 for #3763 due to changes in ofAVFoundationVideoPlayer

### CODE REVIEW

**Comment by i-n-g-o** [comment]
anybody who could test this on iOS?
ping @openframeworks/ios @openframeworks/video

**Comment by danoli3** [comment]
It looks like iOS is still using https://github.com/openframeworks/openFrameworks/tree/master/addons/ofxiOS/src/video so can't test.

**Comment by i-n-g-o** [comment]
well... then we can safely pull it in ;)

**Comment by i-n-g-o** [comment]
here the PR for the iOS_addon:
https://github.com/openframeworks/openFrameworks/pull/4681

**Pull request merged**
