### PR TITLE
Doxygen sections ofTexture & ofUtils

### PR DESCRIPTION
**Pull request by HalfdanJ**
just like #4955 changed sections syntax.

### CODE REVIEW

**Comment by bakercp** [comment]
Cool.  The only thing I'd add is that I think we should consistently apply "Title Case" to the section names (e.g. "Size and Coordinates").  Currently it is not consistent.  I'll update the doxygen style guide.

**Comment by HalfdanJ** [comment]
Good point. Like this?

**Comment by bakercp** [comment]
@HalfdanJ looks perfect to me!

**Comment by HalfdanJ** [comment]
Ok to merge?

**Comment by bakercp** [comment]
Looks good to me.  @arturoc can we merge this?

**Comment by arturoc** [comment]
let me check all of these against the glm branch before merging, don't want to have to merge them all at once later

**Comment by bakercp** [comment]
+1

**Pull request merged**
