### PR TITLE
#1741 of av foundation player adding video streaming

### PR DESCRIPTION
**Pull request by i-n-g-o**
`ofBaseVideoPlayer` only offers `setPosition` which needs the duration of the media.
in case of a stream we do not have a duration, therefore setting the position (or frame) will fail.

### CODE REVIEW

**Comment by i-n-g-o** [comment]
referencing issue: https://github.com/openframeworks/openFrameworks/issues/1741

**Comment by i-n-g-o** [comment]
as a reminder. using streams may need this in your Info.plist

<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>

**Comment by jvcleave** [comment]
I haven't tested this yet but couple I streams I often use:

Nasa stream (sometimes stream switches resolution on the fly)
http://iphone-streaming.ustream.tv/uhls/17074538/streams/live/iphone/playlist.m3u8

Stream with sound:
http://devimages.apple.com/iphone/samples/bipbop/gear1/prog_index.m3u8

Test stream from Apple:
https://devimages.apple.com.edgekey.net/samplecode/avfoundationMedia/AVFoundationQueuePlayer_HLS2/master.m3u8

**Comment by jvcleave** [comment]
@i-n-g-o 

I tried to run with this

```
#pragma once

#include "ofMain.h"

class ofApp : public ofBaseApp{

	public:
    ofVideoPlayer 		videoPlayer;

    void setup(){
        
        string fileStream="https://devimages.apple.com.edgekey.net/samplecode/avfoundationMedia/AVFoundationQueuePlayer_HLS2/master.m3u8";
        string liveStream = "http://iphone-streaming.ustream.tv/uhls/17074538/streams/live/iphone/playlist.m3u8";
        
        videoPlayer.loadAsync(liveStream);
        videoPlayer.play();
    }
    
    void update(){
        videoPlayer.update();
    }
    
    void draw(){
        
        videoPlayer.draw(0, 0);
    }

};
```

but no video played. Do you have a working example?

**Comment by i-n-g-o** [comment]
hi.
your example works for me. (on 10.11.6)
do you get any error-output?

**Comment by i-n-g-o** [comment]
any update on this?
can anybody verify the drawing problem?

**Comment by jvcleave** [comment]
@i-n-g-o I tried on 10.12.3. I didn't see any errors and tried using the same plist from ofxAvFoundationHLSPlayer (ofxAvFoundationHLSPlayer still worked)

**Comment by arturoc** [comment]
not sure what's going on since i don't understand very well which classes are involved in this but it would seem like bStream is never initialized? could that be why it works for you @i-n-g-o  but not for @jvcleave ?

**Comment by i-n-g-o** [comment]
hm. when initializing ofAVFoundationVideoPlayer the flag is set, so i think it should not lead to different behaviour. (a potential bug here if re-using the player and loading a file after loading a stream... i will fix that.)
will also init the bStream flag...

**Comment by jvcleave** [comment]
Thanks @i-n-g-o, all of these worked

```#include "ofMain.h"

class ofApp : public ofBaseApp{

	public:
    ofVideoPlayer 		videoPlayer;

    void setup(){
        
        string fileStream="https://devimages.apple.com.edgekey.net/samplecode/avfoundationMedia/AVFoundationQueuePlayer_HLS2/master.m3u8";
        string liveStream = "http://iphone-streaming.ustream.tv/uhls/17074538/streams/live/iphone/playlist.m3u8";
        string streamWithSound = "http://devimages.apple.com/iphone/samples/bipbop/gear1/prog_index.m3u8";
        videoPlayer.loadAsync(fileStream);
        videoPlayer.play(); 
        videoPlayer.setLoopState(OF_LOOP_NORMAL);
    }
    
    void update(){
        videoPlayer.update();
    }
    
    void draw(){
        
        if(videoPlayer.getTexture().isAllocated())
        {
            videoPlayer.draw(0, 0);
        }
    }

};
```

+1 to merge

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
