### PR TITLE
Deprecate ofFbo::destroy() in favor of clear()

### PR DESCRIPTION
**Pull request by mattfelsen**
A different approach to issue #3051

### CODE REVIEW

**Comment by kylemcdonald** [comment]
looks good! i'm going to wait for one more person to sign off before merging.

**Comment by bilderbuchi** [comment]
looks like a straightforward-enough replacement.

**Comment by kylemcdonald** [comment]
this got a few eyes on it from discussion in another PR, so i'm merging.

**Comment by arturoc** [comment]
the only problem i see with this is that some legacy ofFbo implementations used to have a clear which cleared the background, even if we are not going that route having a clear method might be confusing for some people

**Comment by mattfelsen** [comment]
How about an ofLogWarning() if you call begin() with an unallocated FBO?

**Comment by kylemcdonald** [comment]
@arturoc good point. i think the best solution could be to add a brief line of doxygen documentation above `clear()` that explains exactly what it does (maybe explicitly mentions that you should use `ofClear()` if you want to clear the background) and then also add the error message (i think it's an error, not a warning) if you call begin() unallocated.

**Pull request merged**
