### PR TITLE
iOS Template Project Update - Icon / Splash / iPhone6 / iPad Pro

### PR DESCRIPTION
**Pull request by danoli3**
Fixes issues related to iPhone6 and greater not being supported by template project out of the box.
Fixes: https://github.com/openframeworks/openFrameworks/issues/4566

- Adds Launch Screen
- Adds ImageAssets for Icons / SplashScreen
- New and updated Icon and SlashScreen for iOS
- iOS 7 Minimum for Project.
screen shot 2015-11-17 at 4 38 10 am

### CODE REVIEW

**Comment by julapy** [comment]
hey @danoli3,
one small quirk ive noticed with media assets,
sometimes it unnecessarily makes a copy of files, even though they are the same resolution.
so you may notice that you have some files ending with `-1`, like `Icon-Small@2x-1.png`
its basically duplicated `Icon-Small@2x.png` twice

so what i usually do to fix this is go into the media assets json file,
and change `Icon-Small@2x-1.png` => `Icon-Small@2x.png` (for example) where ever there is a duplicate. and then delete `Icon-Small@2x-1.png` (the duplicate file)

can see that it has happened a few time in this PR.

**Comment by danoli3** [comment]
@julapy Ah, Good call! I noticed the icons were way too big as well. Fixed that too!

**Comment by danoli3** [comment]
Yeah to support iOS 9 devices, iPad Pro, iPhone 6s, iPhone 6s Plus and all devices running iOS 9 we need to set Minimum Xcode version to 7.0 (which is fine as you need it to submit to the AppStore, and it is free upgrade for all platforms that Xcode 6 ran on).

**Comment by HalfdanJ** [comment]
Seems like two of the images are changed, but the resolution is the same (`scripts/templates/ios/mediaAssets/Images.xcassets/AppIcon.appiconset/Icon-76.png` and `scripts/templates/ios/mediaAssets/Images.xcassets/AppIcon.appiconset/Icon-76x2.png`) 
They are lower quality now (look more fuzzy). Is that on purpose?

**Comment by danoli3** [comment]
Probably a bug with my exporter I'll have a look thanks

**Comment by danoli3** [comment]
Going to re-pr this one. Squash commits. Ah yes @HalfdanJ the quality changed on those icons as those original images were like 400kb for a 76x76... compressed versions still looking great on devices with current.

**Comment by danoli3** [comment]
Closing in favour of new PR.

**Pull request closed without merging**
