### PR TITLE
Add first version of oF CMake config (for use in external CMake proje…

### PR DESCRIPTION
**Pull request by flv0**
Works for me, tried adding VS/osx configs, but things need to be tested by someone else, don't know if the actual library names are identical for example.

### CODE REVIEW

**Comment by pizthewiz** [comment]
Building via `make` on OS X does use the _libopenFrameworksDebug.a_ naming scheme, #2882 has a few details.

**Comment by procedural** [comment]
Shouldn't it search for other libraries on which openFrameworks depends? The project from your forum post:

```
set(PROJECT etudes)

project(${PROJECT})
cmake_minimum_required(VERSION 3.0)

set(openFrameworks_DIR $ENV{OPENFRAMEWORKS_ROOT}/cmake)
find_package(openFrameworks REQUIRED)

add_executable(${PROJECT} src/main.cpp)

target_include_directories(${PROJECT}
    PUBLIC ${openFrameworks_INCLUDES})

target_link_libraries(${PROJECT}
    PUBLIC ${openFrameworks_LIBRARIES})
```

Won't build the application since no OF dependencies is given to the linker...

**Comment by flvi0** [comment]
@pizthewiz Ok expected that somehow, will look into getting stuff straightened out tomorrow.
@procedural Well, as of now, libopenFrameworks is linked as a static lib which simplifies stuff. It will link against the static versions of the dependant libraries, so no problem with that. When using shared objects, LD_LIBRARY_PATH will need to be set accordingly before building in order for the linker to find the dynamically linked objects. Providing a convenience script or something for that is another issue, which we might look into when it becomes necessary. The application builds and runs just fine here.

**Comment by procedural** [comment]
>It will link against the static versions of the dependant libraries

No it won't. How the linker supposed to know that the application needs to be linked against libGL.so, for example?

**Comment by procedural** [comment]
@flvi0 are you on Linux? Could you post here a link to a ofApp binary that runs fine for you?

**Comment by flvi0** [comment]
I haven't got to that point yet, I was concerning with getting the build set up until now and it was a long day. I will keep you updated!

**Comment by flvi0** [comment]
@procedural You are of course right regarding the static libraries. All resolution of symbols is performed by the loader.. Hence my initial question about the shared object build, is there a reason we are using static libraries at all? Since with a shared object build you don't need this kind of information since symbols only required as transitive dependencies (and not the application itself) will be resolved at link time of the library.

**Comment by flvi0** [comment]
Either way it is possible to just pass the respective paths via the CMake config. I will see tomorrow if I find time during the day to look further at this!

**Comment by flvi0** [comment]
Updated, linux only now. Have a mac available an i'm improving, just for people to test it on Linux (@procedural)

**Comment by bilderbuchi** [comment]
Is the `cmake` base directory where this resides mandatory somehow? Otherwise I think it would be better _not_ to add another OF-root-level directory, and put this somewhere more appropriate. E.g. most of the makefile stuff lives in `libs/openFrameworksCompiled/project`.

**Comment by flvi0** [comment]
by no means mandatory. it is placed commonly in that cmake toplevel dir by many projects, but I see it kinda makes sense to put in in libs/openFrameworksCompiled/project. will adapt accordingly, thanks.

**Comment by flvi0** [comment]
updated. other wishes/complaints/ideas?

**Comment by bilderbuchi** [comment]
ping @arturoc

**Comment by flvi0** [comment]
where do i get libkiss from on osx?

**Comment by flvi0** [comment]
Ok, works on mac os now. Not runtime tested since I'm remotely working on my mac system at work and have trouble with X11 forwarding (which I'm about to fix), don't see a reason why it should not run however. Maybe you want to give this some testing. I don't have a windows platform at my disposal.

**Comment by flvi0** [comment]
It seems that the name of the openFrameworks library on mac os depends on wether I type make in the project directory of go to osx/ subfolder and build using the xcode project. Typing make names the library libopenFrameworks.so, while the xcode config misses the lib prefix. I could account for that in the config file, however I would prefer to have this straightened in the xcode project to use lib prefix as well.

**Comment by pizthewiz** [comment]
Yup, that's tracked by the issue #2882 I [linked](https://github.com/openframeworks/openFrameworks/pull/4430#issuecomment-147803579) above ;0)

**Comment by flvi0** [comment]
So pull request for #2882 is open as well, with a (temporary) symlink solution to account for the name change, which should be removed in some upcoming release. is there still interest in this?

**Pull request closed without merging**
