### PR TITLE
Making sure json file exists before reading from it

### PR DESCRIPTION
**Pull request by prisonerjohn**
otherwise it crashes

### CODE REVIEW

**Comment by bakercp** [comment]
Perhaps just use `ofLoadJson()` to keep things consistent?

https://github.com/openframeworks/openFrameworks/blob/d7fd67ea348ed05e7a7c52d50d0a85d129a7bc42/addons/ofxGui/src/ofxBaseGui.cpp#L194

**Comment by prisonerjohn** [comment]
Good call, just updated it.

**Comment by arturoc** [comment]
hey sorry just saw this, i think this was done without using ofLoadJson cause that would log an error message if trying to load a .json that doesn't exist but in this case it shouldn't be an error

**Comment by prisonerjohn** [comment]
How come it shouldn't be an error, if the file we're trying to load doesn't exist?

**Comment by arturoc** [comment]
oh sorry, i though this was when trying to load before saving not on the load method itself.

**Pull request merged**
