### PR TITLE
ofXml cleanup

### PR DESCRIPTION
**Pull request by bakercp**
Lots of cleanup for ofXml.

No functional changes.

### CODE REVIEW

**Comment by arturoc** [comment]
great, thanks, i think we should wait until post 0.9 to merge this. we should do this with every class in the core so it would be weird to have one class using one style and the rest another.

we should change at least all the headers to use std::, we can discuss also if we want to use std::string... in the cpp's too or instead use `using namespace std;` there

**Comment by bakercp** [comment]
Agreed. I was basically trying to understand ofXml better and was cleaning up as I went.

**Comment by joshuajnoble** [comment]
Like it!

**Comment by arturoc** [comment]
@bakercp if you want to clean this i'll merge it, we've been merging stuff like this already so no need to wait to do all classes at once

**Comment by bakercp** [comment]
@arturoc ok.

**Comment by bakercp** [comment]
Closing this because it's crazy.  Using #4159.

**Pull request closed without merging**
