### PR TITLE
0.9.3 osx freeimage fix

### PR DESCRIPTION
**Pull request by bakercp**
Fixes https://github.com/openframeworks/openFrameworks/issues/4812

### CODE REVIEW

**Comment by arturoc** [comment]
is it ok to remove the undefs? i think they were there to solve some other problem but the FT headers are not exposed globally any more, only included in the cpp, so it might not be necessary any more

**Comment by bakercp** [comment]
@danoli3? 

I just ran the apothecary scripts in the 0.9.3 branch.

**Comment by danoli3** [comment]
@arturoc removing the undefs, I think it should be fine, I originally put them in to be sure it wasn't an issue in the old code, especially when they were in the headers, however it should be totally fine it is not exposed anymore. +1 merge

**Comment by arturoc** [comment]
ok, great!

**Comment by ofTheo** [comment]
I think this PR introduced a bug with OS X 32bit in the 0.9.3 release. 
Opening an issue for this but I was able to reproduce with the current download.

**Pull request merged**
