### PR TITLE
Msys2 opencv4

### PR DESCRIPTION
**Pull request by oxillo**
Update ofxOpenCv addon to use openCv 4 if available.
Some methods (especially HaarDetectObejct converted to their C++ equivalent)
Should correct #6202

### CODE REVIEW

**Comment by arturoc** [comment]
Thanks so much for looking into this, it's really useful.

Couple of things.

- You've added to the PR your vs code config, can you remove it?
- The way you are doing the addons config is only compatible with the makefiles but won't work with the PG or the qtcreator wizard. What i did recently for another addon is to add an exception in the install_dependencies script that detects the version of the library and modifies addon_config.mk to change the file with whatever is needed. in this case changing opencv -> opencv4

**Comment by oxillo** [comment]
Cleaned up VS code config; 
Added the ofxOpenCv addon_config.mk modification in msys2 install_dependencies.
I was also thinking of having a script in the addon so people upgrading their system can upgrade the script.

**Comment by arturoc** [comment]
i've just compiled opencv 4 for the platforms that use local libraries, can you change the script to instead fix it if you are using and old version? we could also just not have any fix and assume people need to have an up to date install of msys

**Comment by arturoc** [comment]
going to merge this since msys is working fine now and keep working on the other platforms on a different PR.

Thanks!

**Pull request merged**
