### PR TITLE
Refactoring ofBuffer::Lines/RLines

### PR DESCRIPTION
**Pull request by 2bbb**
* remove `std::iterator` with writing type alias directly
* implement `Lines::rbegin` and `Lines::rend` are not implemented (!!)
* add some `const` qualitifiers (and `cbegin`, `cend`, etc...)
* fix logic on RLine:
  * first line (i.e., last line in buffer) was wrong.
* fix edge case on Line/RLine: 
  * empty line was ignored when line break appears at last/first of text (e.g. `"\na\nb\n"`)
    * is this not correct?

related: #6926

### CODE REVIEW

**Comment by 2bbb** [comment]
@arturoc

I have a question.

The specification of iteration `Lines` is what the last line break will be ignored?
i.e. "A\nB\n" will be `"A", "B"`, not `"A", "B", ""`

Test case is so. Is this what you intended?
https://github.com/openframeworks/openFrameworks/blob/073f17d1bc8cf77407234cabf58fa37ad0b22b53/tests/utils/buffer/src/main.cpp#L165

**Comment by dimitre** [comment]
@2bbb thanks for the PR. I've just checked out and tested. everything working here!

**Comment by dimitre** [comment]
Great one! I've noticed the builds using make are generating an error
```c++
/Users/z/Desktop/src/ofw/libs/openFrameworks/utils/ofFileUtils.cpp:439:20: error: no member named 'make_reverse_iterator' in namespace 'std'
        return RLine(std::make_reverse_iterator(_begin), std::make_reverse_iterator(_begin));
```


I think it can be solved by a template here or bumping gcc version
https://stackoverflow.com/questions/50161210/error-make-reverse-iterator-is-not-a-member-of-std#50162394

**Comment by ofTheo** [comment]
Hmm, I think there are more issues as the tests are failing too. 
Going to revert this @2bbb until the tests / checks pass the CI ( sorry I missed that ) 

```
[ notice ] lines iterator
[ notice ] all lines are correct passed
[  error ] lines iterator correct numLines failed 
[  error ] test_eq(numLines, lines.size())
[  error ] value1: numLines is 18
[  error ] value2: lines.size() is 17
[  error ] /Users/runner/work/openFrameworks/openFrameworks/tests/utils/buffer/src/main.cpp: 176
[ notice ] -------------------
[ notice ] lines reverse iterator
[  error ] all lines are correct failed 
[  error ] /Users/runner/work/openFrameworks/openFrameworks/tests/utils/buffer/src/main.cpp: 212
[  error ] lines iterator correct numLines failed 
[  error ] test_eq(numLines, lines.size())
[  error ] value1: numLines is 18
[  error ] value2: lines.size() is 17
[  error ] /Users/runner/work/openFrameworks/openFrameworks/tests/utils/buffer/src/main.cpp: 213
[  error ] 3/31 tests failed
[ notice ] took 2ms
```

**Comment by dimitre** [comment]
Hey @ofTheo this test failing is related to the second @2bbb post where he asks about appending "\n" so it returns one more line. If the \n is unneeded we can update the test itself too

**Comment by 2bbb** [comment]
@dimitre @ofTheo 
Hi. sorry for the late response.

at first, `make_reverse_iterator` is from C++14. if we need backward compatibility, I will rewrite with another way.

----

second, I know the test is failed now. and I want to know is the current test really correct.
I think fine result is the using getLines with iteration is same as result of split by "\n" (or "\r\n").

so, e.g. when content of ofBuffer is `"\n\nabc\ndef\n\n"`, current results of getLines and getRevrseLines are:

```
[notice ] lines: 0 
[notice ] lines: 1 
[notice ] lines: 2 abc
[notice ] lines: 3 def
[notice ] lines: 4 

[notice ] rlines: 0 
[notice ] rlines: 1 def
[notice ] rlines: 2 abc
[notice ] rlines: 3 
[notice ] rlines: 4 
```

I think doesn't this makes confuse?
and, if we want to ignore last empty line, then "\n\n" isn't needed to ignored too? or "\n\n\n"?

thanks

**Comment by oxillo** [comment]
I would really prefer the option of having the last line included i.e.

```
[notice ] lines: 0 
[notice ] lines: 1 
[notice ] lines: 2 abc
[notice ] lines: 3 def
[notice ] lines: 4 
[notice ] lines: 5
```

That would be consistent with the number of lines shown in most text editors (`"\n\nabc\ndef\n\n"` has 6 lines in VS Code, Notepad++ and nano but vim has 5...) .
Also, I would expect that `getLines()` on `"\n\ndef\nabc\n\n"` would return the same as `getReverseLines()` on `"\n\nabc\ndef\n\n"`

**Pull request merged**
