### PR TITLE
add install scripts for openSUSE in scripts/linux/opensuse

### PR DESCRIPTION
**Pull request by prusnak**
I created install scripts for openSUSE distribution by modifying the ones for Fedora.

### CODE REVIEW

**Comment by lakehanne** [comment]
Hey prusnak, how do you suggest I add the install scripts? Do you have the folder somewhere to pull it from?

**Comment by prusnak** [comment]
Click on the commit link above your comment.

**Comment by lakehanne** [comment]
Thanks! I have indeed downloaded and installed it.  But when I try to compile any of the examples, I get errors such the one below:

./compileOF.sh
makefileCommon/config.shared.mk:259: *** couldn't find some pkg-config packages, did you run the latest install_dependencies.sh?.  Stop.
there has been a problem compiling Debug OF library
please report this problem in the forums
chown: cannot access '../lib/linux64/*': No such file or directory

**Comment by lakehanne** [comment]
BTW, I ran the install_dependencies.sh that ships with your ZIP code

**Pull request closed without merging**
