### PR TITLE
docs_low_level: ofTimer.h

### PR DESCRIPTION
**Pull request by workergnome**
@bakercp, please review?

### CODE REVIEW

**Comment by bakercp** [comment]
Reviewing ...

**Comment by bakercp** [comment]
```c++
	/// \warning This will crash your application if you haven't called setPeriodicEvent().
```

true fact?  seems like this should be reported as a bug?

**Comment by bakercp** [comment]
Related https://github.com/openframeworks/openFrameworks/issues/4883

**Comment by bakercp** [comment]
Would like to see https://github.com/openframeworks/openFrameworks/issues/4883 fixed and the \warning removed from these docs :)

**Comment by arturoc** [comment]
yes @workergnome can you remove the warning and instead open an issue? thanks!

**Comment by workergnome** [comment]
It looks like issue #4883 already exists, and it references this pull request, so should we leave the warning in until that issue's resolved?

**Comment by arturoc** [comment]
ah, ok, no better remove the warning.

**Comment by workergnome** [comment]
Fair enough.  It's removed.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
