### PR TITLE
add double quotes to allow for folder names with spaces

### PR DESCRIPTION
**Pull request by kkshmz**
Pull request for 
#6372

### CODE REVIEW

**Comment by kkshmz** [comment]
@arturoc Hey, it seems to be working most of the time, is there a way I could debug the one that didn't pass? (linuxarmv7)

**Comment by arturoc** [comment]
That it's not related to your change which surely works on linux arm7 if it works on other linus platforms. it just failed cause of a timeout downloading some packages, i've just restarted that job and hopefully it'll work this time. thankS1

**Comment by kkshmz** [comment]
Thanks for the reply, seems like the IL server is the only one down, but should work if we tried later.

**Comment by kkshmz** [comment]
IL Server now seems to be up, when you have time!

**Pull request merged**
