### PR TITLE
Fix rpi for arm7

### LINKED ISSUE #4710: PLATFORM_VARIANT detection?
So, on a fresh raspbian image, `./compileOF.sh` failed. I had to `cd libs/openFrameworksCompiled/project && PLATFORM_VARIANT=raspberry2 make` and it seems to be working.

Should PLATFORM_VARIANT be detected automatically? And should it be in compileOF.sh or the Makefiles themselves? Or should this have worked from the beginning and we gotta track down why the 'wrong' platform was being selected / why ofArduino failed to compile with just a plain `./compileOF.sh` on the raspberry pi?

### PR DESCRIPTION
**Pull request by jvcleave**
This should fix #4710 

RPI2/arm7 will have to do
`make RPI=1`

RPI2/arm7/cross compilers will have to do
`make RPI=1 CROSS_COMPILING=1`

Would be nice to just merge this so I can test on the nightlies. Cloning master on the RPI is problematic due to the repo size

### CODE REVIEW

**Comment by bakercp** [comment]
Why the new RPI variable?

Shouldn't the `PLATFORM_ARCH=armv6l` and `HOST_ARCH = armv6l` just be defined in the platform variant?

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/linuxarmv7l/config.linuxarmv7l.raspberry2.mk

?

**Comment by jvcleave** [comment]
@bakercp config.shared.mk comes in before that and causes PLATFORM_VARIANT to fail (unless I am getting something wrong)

**Comment by arturoc** [comment]
perhaps it's better to have this in the platform detection code in config.shared? that way we don't need any new variable. we should be able to detect the raspbian looking for some common file and then just define arm6 instead of arm7 if we are on it.

also this shouldn't affect other distributions since arm7 should be the default in them on the rpi2

**Comment by jvcleave** [comment]
`cat /etc/*-release`

returns

```
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

We would still need to be careful about providing a way to override for cross-compiling

**Comment by arturoc** [comment]
that should do, for cross compiling we just need to pass the OS and ARCH
like:

make PLATFORM_OS=Linux PLATFORM_ARCH=armv6l

and the variant in case we are compiling for other board and it should
do the right thing

**Comment by jedahan** [comment]
Setting PLATFORM_ARCH, PLATFORM_ARCH and PLATFORM_OS, or HOST_ARCH didn't work for me. What did work is setting HOST_ARCH and PLATFORM_ARCH:

#### setting  PLATFORM_ARCH only
```bash
pi@raspberrypi:~ $ make PLATFORM_ARCH=armv6l -C /home/pi/openFrameworks/libs/openFrameworksCompiled/project/
make: Entering directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
HOST_OS=Linux
HOST_ARCH=armv7l
GSTVERSION=0.10
1
checking pkg-config libraries:   cairo zlib gstreamer-app-0.10 gstreamer-0.10 gstreamer-video-0.10 gstreamer-base-0.10 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa
makefileCommon/config.shared.mk:278: *** couldn't find some pkg-config packages, did you run the latest install_dependencies.sh?.  Stop.
make: Leaving directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
```

#### setting  PLATFORM_OS and PLATFORM_ARCH
```bash
pi@raspberrypi:~ $ make PLATFORM_OS=Linux PLATFORM_ARCH=armv6l -C /home/pi/openFrameworks/libs/openFrameworksCompiled/project/
make: Entering directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
HOST_OS=Linux
HOST_ARCH=armv7l
GSTVERSION=0.10
1
checking pkg-config libraries:   cairo zlib gstreamer-app-0.10 gstreamer-0.10 gstreamer-video-0.10 gstreamer-base-0.10 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa
makefileCommon/config.shared.mk:278: *** couldn't find some pkg-config packages, did you run the latest install_dependencies.sh?.  Stop.
make: Leaving directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
```
#### setting HOST_ARCH only
```bash
pi@raspberrypi:~ $ make HOST_ARCH=armv6l -C /home/pi/openFrameworks/libs/openFrameworksCompiled/project/
make: Entering directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
HOST_OS=Linux
HOST_ARCH=armv6l
GSTVERSION=0.10
1
checking pkg-config libraries:   cairo zlib gstreamer-app-0.10 gstreamer-0.10 gstreamer-video-0.10 gstreamer-base-0.10 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa glesv1_cm glesv2 egl
makefileCommon/config.shared.mk:278: *** couldn't find some pkg-config packages, did you run the latest install_dependencies.sh?.  Stop.
make: Leaving directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
```

#### setting HOST_ARCH and PLATFORM_ARCH worked fine
```bash
pi@raspberrypi:~ $ make HOST_ARCH=armv6l PLATFORM_ARCH=armv6l -C /home/pi/openFrameworks/libs/openFrameworksCompiled/project/
make: Entering directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 libmpg123
HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 libmpg123
HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gst
...snip...
```

**Comment by jvcleave** [comment]
I think what is happening If you skip setting HOST_ARCH the config.shared.mk then assumes you are cross-compiling as HOST_ARCH(arm7) != PLATFORM_ARCH(arm6)

I am also wondering if config.linuxarmv7l.raspberry2.mk even needs to exist now?

**Comment by jedahan** [comment]
Well, now I get errors linking on emptyExample, using the Makefile from /home/pi/openFrameworks/scripts/tempaltes/linuxarmv6l/Makefile:

```bash
pi@raspberrypi:~/openFrameworks/examples/empty/emptyExample $ make PLATFORM_ARCH=armv6l HOST
_ARCH=armv6l > build.log
/home/pi/openFrameworks/libs/openFrameworksCompiled/lib/linuxarmv6l/libopenFrameworks.a(ofAppRunner.o): In function `ofSetupOpenGL(std::shared_ptr<ofAppGLFWWindow>, int, int, ofWindowMode)':
ofAppRunner.cpp:(.text+0x61c8): undefined reference to `ofAppGLFWWindow::setup(ofGLFWWindowSettings const&)'
/home/pi/openFrameworks/libs/openFrameworksCompiled/lib/linuxarmv6l/libopenFrameworks.a(ofAppRunner.o): In function `ofAppGLFWWindow::pollEvents()':
ofAppRunner.cpp:(.text._ZN15ofAppGLFWWindow10pollEventsEv[_ZN15ofAppGLFWWindow10pollEventsEv]+0x0): undefined reference to `glfwPollEvents'
collect2: error: ld returned 1 exit status
make[1]: *** [bin/emptyExample] Error 1
make: *** [Release] Error 2
```
build.log:
```bash
HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 libmpg123 
Compiling OF library for Release
make[1]: Entering directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 libmpg123 
HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 libmpg123 
HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 libmpg123 
Done!
make[1]: Leaving directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'


Compiling emptyExample for Release
make[1]: Entering directory '/home/pi/openFrameworks/examples/empty/emptyExample'
HOST_OS=Linux
HOST_ARCH=armv6l
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gtk+-3.0 libmpg123 
Linking bin/emptyExample for linuxarmv6l
g++ -o bin/emptyExample  obj/linuxarmv6l/Release/src/main.o obj/linuxarmv6l/Release/src/ofApp.o  /home/pi/openFrameworks/libs/openFrameworksCompiled/lib/linuxarmv6l/libopenFrameworks.a   -Wl,-rpath=./libs:./bin/libs -Wl,--as-needed -Wl,--gc-sections -pthread -L/opt/vc/lib /home/pi/openFrameworks/libs/kiss/lib/linuxarmv6l/libkiss.a /home/pi/openFrameworks/libs/tess2/lib/linuxarmv6l/libtess2.a  /home/pi/openFrameworks/libs/poco/lib/linuxarmv6l/libPocoNetSSL.a /home/pi/openFrameworks/libs/poco/lib/linuxarmv6l/libPocoNet.a /home/pi/openFrameworks/libs/poco/lib/linuxarmv6l/libPocoCrypto.a /home/pi/openFrameworks/libs/poco/lib/linuxarmv6l/libPocoUtil.a /home/pi/openFrameworks/libs/poco/lib/linuxarmv6l/libPocoJSON.a /home/pi/openFrameworks/libs/poco/lib/linuxarmv6l/libPocoXML.a /home/pi/openFrameworks/libs/poco/lib/linuxarmv6l/libPocoFoundation.a  -L/usr/lib/arm-linux-gnueabihf -lz -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -ludev -lfontconfig -lfreetype -lsndfile -lopenal -lssl -lcrypto -lpulse-simple -lpulse -lasound -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lmpg123  -lfreeimage -lrtaudio -lboost_filesystem -lboost_system -lGLESv2 -lGLESv1_CM -lEGL -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpcre -lrt -lX11 -ldl
/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:381: recipe for target 'bin/emptyExample' failed
make[1]: Leaving directory '/home/pi/openFrameworks/examples/empty/emptyExample'
/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:126: recipe for target 'Release' failed
```

**Comment by jvcleave** [comment]
@jedahan if you are using my branch try with just `make`

**Comment by jvcleave** [comment]
@jedahan nevermind - seeing the same issue but think it may be unrelated to this PR

**Comment by jvcleave** [comment]
`& !defined(TARGET_RASPBERRY_PI)` needs to be re-added to
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppRunner.cpp#L22

**Comment by jvcleave** [comment]
ok - I have tested this against
RPI2/arm7
RPI2/arm7 with cross-compiler
RPI1/arm6 with cross-compiler
RPI1/arm6 (currently compiling - going to be a while)

One thing that could be done is

```
ifdef RPI_ROOT
CROSS_COMPILING=1
```

otherwise I am currently having to pass in `CROSS_COMPILING=1`

**Comment by jedahan** [comment]
@jvcleave when you say arm7 with cross-compiler, you mean from your local laptop/desktop right?
I'm just a bit confused if compiling armv6l is considered 'cross compiling' when the userspace of raspbian is armv6l even though the architecture supports armv7l...

For that matter, would archlinux/armv7l userspace on the pi, be considered 'cross-compiling' if it was creating an armv6l version of oF?

I will test your latest branch, first with `make`, then with `CROSS_COMPILING=1 make`

Thanks for helping out

**Comment by jvcleave** [comment]
@jedahan - right - I am cross compiling with a VM on my Mac

I haven't tried Arch/Arm7 but then no - that wouldn't be cross-compiling (unless you were also using a VM, etc)

In theory, Arch/Arm7 should work as usual as this PR is explicitly looking for Raspbian

**Comment by jvcleave** [comment]
So maybe `config.linuxarmv7l.raspberry2.mk` does still have a use in the case of Arch/Arm7

**Comment by arturoc** [comment]
@jvcleave yes config.linuxarmv7l.raspberry2.mk is useful in case you are using anything else than raspbian. every other distro is usually compiled with the correct settings for arm7, it's only raspbian (for compatibility with the rpi1) that still compiles everything for armv6

**Comment by jvcleave** [comment]
Just finished - RPI1/arm6 is compiling natively on the board as well

**Comment by jedahan** [comment]
working well for me!

**Comment by jvcleave** [comment]
ok, `CROSS_COMPILING=1` is no longer required as it is now looking to see if RPI_ROOT is defined (required for cross-compiling)

@arturoc ok to merge?

**Comment by jvcleave** [comment]
tagged it as 0.9.1 so it's not forgotten for it - feel free to untag if this intended for later

**Comment by arturoc** [comment]
thanks!

**Comment by 01010101** [comment]
Tried to compile (not cross-compiling) v0.9.1 armv6l on a RPi2/Jessie
"make -j4 -C /home/pi/openFrameworks/libs/openFrameworksCompiled/project/"
It fails with the following message :
makefileCommon/config.shared.mk:227: *** This package doesn't support your platform, probably you downloaded the wrong package?.  Stop.
make: Leaving directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'

Uncommenting the $(info...) in config.shared.mk gives me this
_HOST_OS=Linux
PLATFORM_ARCH=armv7l
PLATFORM_OS=Linux
HOST_ARCH=armv7l
HOST_OS=Linux
CROSS_COMPILING=0
PLATFORM_VARIANT=default
IS_RASPBIAN=_

I think the ifdef RPI_ROOT check is not needed here, considering we force all Raspbians to compile against armv6l. Whether $(RPI_ROOT) is defined or not, it will point to the right place.

I tried with this and it worked well
_#ifdef RPI_ROOT
     ifeq ($(shell grep ID=raspbian $(RPI_ROOT)/etc/*-release),ID=raspbian)
       IS_RASPBIAN=1
     endif
#endif_

**Pull request merged**
