### PR TITLE
Add script verifying NDK install

### PR DESCRIPTION
**Pull request by HalfdanJ**
Added a script that is verifying the NDK version, and giving better errors when wrong version is installed. Making it more user friendly.

### CODE REVIEW

**Comment by danzeeeman** [comment]
I want to see how much work it is to update to the latest NDK so we can just use the one from Android Studio.  But this looks interesting

**Comment by HalfdanJ** [comment]
Yeah, I agree, but we will have this issue all the time, so thought it was good to make a user friendly error

**Comment by HalfdanJ** [comment]
Okay, need to work some more on this. It works in android studio that creates the local.properties file, but not from commandline (and CI).

**Comment by HalfdanJ** [comment]
Ok, fixed it

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
