### PR TITLE
Update ofxOSC to support double.

### PR DESCRIPTION
**Pull request by bakercp**
I needed double support to send gps coordinates over OSC.

But this brings up a potentially larger issue -- why are we only supporting a limited subset of the tag types:

``` c++
enum TypeTagValues {
    TRUE_TYPE_TAG = 'T',
    FALSE_TYPE_TAG = 'F',
    NIL_TYPE_TAG = 'N',
    INFINITUM_TYPE_TAG = 'I',
    INT32_TYPE_TAG = 'i',
    FLOAT_TYPE_TAG = 'f',
    CHAR_TYPE_TAG = 'c',
    RGBA_COLOR_TYPE_TAG = 'r',
    MIDI_MESSAGE_TYPE_TAG = 'm',
    INT64_TYPE_TAG = 'h',
    TIME_TAG_TYPE_TAG = 't',
    DOUBLE_TYPE_TAG = 'd',
    STRING_TYPE_TAG = 's',
    SYMBOL_TYPE_TAG = 'S',
    BLOB_TYPE_TAG = 'b',
    ARRAY_BEGIN_TYPE_TAG = '[',
    ARRAY_END_TYPE_TAG = ']'
};
```

Our support (including the double I am adding):

``` c++
typedef enum _ofxOscArgType
{
    OFXOSC_TYPE_NONE,
    OFXOSC_TYPE_INT32,
    OFXOSC_TYPE_INT64,
    OFXOSC_TYPE_FLOAT,
    OFXOSC_TYPE_DOUBLE,
    OFXOSC_TYPE_STRING,
    OFXOSC_TYPE_BLOB,
    OFXOSC_TYPE_BUNDLE,
    OFXOSC_TYPE_INDEXOUTOFBOUNDS
} ofxOscArgType;
```

### CODE REVIEW

**Comment by groolot** [comment]
I've proposed some addons for boolean. See #3534 and the fix #3535

**Comment by pizthewiz** [comment]
Sorry for the confusion, is this one being considered for 0.9.0 then given the bool report in #3534 and PR in #3535?

**Comment by bilderbuchi** [comment]
I don't think we should add this to the 0.9 milestone

**Comment by pizthewiz** [comment]
Works for me, I just wasn't sure given the movement on the `bool` front.

**Pull request closed without merging**
