### PR TITLE
ofMesh of index type fixes

### PR DESCRIPTION
**Pull request by bakercp**
@arturoc here are the rest to remove the warnings.

I'm not exactly sure why we have ofIndexType (it resolves to a tess index which resolves to an unsigned int).  Would be better to use use `std::size_t` for indices throughout (don't have to check < 0, etc) and guaranteed to be correct bit-width for the platform.  Anyway ...

Check it!

### CODE REVIEW

**Comment by arturoc** [comment]
we use ofIndexType cause GLES only supports unsigned short while GL supports unsigned int so we need a type that is the correct size for each platform

**Comment by arturoc** [comment]
thanks!

**Comment by bakercp** [comment]
Got it.  Thanks!

**Comment by bilderbuchi** [comment]
> we use ofIndexType cause GLES only supports unsigned short while GL supports unsigned int so we need a type that is the correct size for each platform

but wouldn't std::size_t correctly reflect this for each platform?

**Comment by arturoc** [comment]
no, siize_t might be different in different platforms according to the cpu or os architecture but this is a GPU limitation

**Comment by bilderbuchi** [comment]
okay, but `TESSindex`, which is what ofindexType boils down to, is also [only switched according to platform, not GPU](https://github.com/openframeworks/openFrameworks/blob/ef44006cf219a1aed09e9891e3997a724386fd36/libs/tess2/include/tesselator.h#L123-L127)?

**Comment by arturoc** [comment]
yeah sorry is not a limitation of the GPU itself but of the version of openGL used, openGL vs openGL ES

until now we know which version of openGL we are using from detecting the platform. we've been adding the different types of TESSindex as we added new platforms, it's not in the original code.

there is the posibility of runnning openGL ES on plain linux and some arm linux support plain openGL for example but until now we haven't had support for those

**Comment by bilderbuchi** [comment]
so, just for clarity, wouldn't it  be better to do this selection right where ofindextype is defined, and not hidden somewhere in a manually patched Tess header?

**Comment by bakercp** [comment]
+1 for more clarity around how / where / why ofIndexType is defined.

**Comment by arturoc** [comment]
tess also needs the same type to work well with openGL ES so we rely on that. that way we also avoid that they could get out of sync. perhaps we can add some comments but the way it's done by typedefing one from another is correct in my opinion

**Pull request merged**
