### PR TITLE
deprecating ofxXmlsettings

### PR DESCRIPTION
**Pull request by tpltnt**
Hi,

this PR removes the 'ofxXmlSettings' addon (source and references) as suggested in #2113.
Cheers,
tpltnt

### CODE REVIEW

**Comment by bakercp** [comment]
Should we actually deprecate it before we remove it completely?  I'm not sure if we ever formally deprecated it in favor of ofXml, and now that Poco is no longer part of the core, ofXml is a bit in limbo until we choose another 3rd part xml lib (I'd vote for Pugi as that's what we're using for project generator, etc).

**Comment by ofZach** [comment]
+1 to deprecating ofxXmlSettings and note removing -- I also think that ofxXmlSettings is kind of a staple of so many projects that including it in the core for at least some release cycles would be useful / warranted with some advice about how to transition.  It will definitely break thousands of projects and dozens of addons if it is removed completely and I feel like some capability layer (like how ofDirectory took on some of the key features of ofxDirList) would also be worthwhile to consider.

**Comment by bakercp** [comment]
By the way @tpltnt you are rocking it with all the code contributions lately.  Keep up the good work.  I hope you don't read push-back on a PR like this as criticism of your extremely helpful contributions! :+1:  I just closed one of my old PRs (https://github.com/openframeworks/openFrameworks/pull/2773), so I know how it goes!

**Comment by tpltnt** [comment]
@bakercp thank you. I don't regard the push-back(s) as criticism. Your points are valid and you are the ones steering the project. I am just contributing where i see fit.

**Comment by bilderbuchi** [comment]
so, close this then? @tpltnt "_deprecation_" of code means adding some kind of warning to it, so that users using it will be made aware that they should nor use it any more, and what they should use instead (and how). after a couple of releases the users should be aware of that and have migrated, at which time we can _remove_ it. you can search the codebase for `OF_DEPRECATE` if you want to know how this is handled currently.

**Comment by tpltnt** [comment]
@bilderbuchi I am closing. I opened #4152 to handle the deprecation and i am going to open this PR again with the explicit intention of removing ofxXmlSettings. This could be merged after 0.9 when appropriate.

**Pull request closed without merging**
