### PR TITLE
XCode - openFrameworks files by reference (blue folder)

### PR DESCRIPTION
**Pull request by dimitre**
so we don't need to edit the template if we add / remove files from the core.
other advantage is the template folder gets a little bit lighter if we have to edit it

Screen Shot 2023-03-31 at 14 13 55

### CODE REVIEW

**Comment by dimitre** [comment]
Any opinion on this one @ofTheo @artificiel ?

**Comment by artificiel** [comment]
don't see a problem with that.

thinking about it: is it even required since the CoreOF.xcconfig is included? it's nice to be able to fish in the directory for reference, but maybe not so for beginners? (and "jump to definition" will still work, which is the better way to fish). if it can be omitted it should.

**Comment by dimitre** [comment]
I think it is nice to browse .h files in the project when working with OF projects.

**Comment by ofTheo** [comment]
looks great! thanks @dimitre

**Comment by dimitre** [comment]
I'm wondering about making the "src" folder a reference too, and alter PG so it doesn't handle the code adding anymore.
PG is great to add another sources in  "src" folder, but having ofApp.h and ofApp.cpp hardcoded is not a good idea since some tests only use main.cpp. It also simplify the way PG handles ios / macOS differences.

**Comment by ofTheo** [comment]
yeah - I think that makes sense too @dimitre !

**Pull request merged**
