### PR TITLE
WIP: Travis improvements 3

### PR DESCRIPTION
**Pull request by bilderbuchi**
Let's see if this works.

* [x] move secure env vars out of `global`
* [x] ~~see if we can get a linux docker build to run~~. This works, but a large list of packages we need are not [whitelisted](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise) for use: 
    * libraw1394-dev
    * libassimp-dev
    * librtaudio-dev
    * libgstreamer-plugins-base1.0-dev
    * gstreamer1.0-libav
    * gstreamer1.0-pulseaudio
    * gstreamer1.0-x
    * gstreamer1.0-plugins-bad
    * gstreamer1.0-alsa
    * gstreamer1.0-plugins-base
    * gstreamer1.0-plugins-good

* [x] check if dist: trusty for the `linux` build is an option. -> This works but is hit by https://github.com/travis-ci/travis-ci/issues/1228
* [x] See if on trusty we can run the allAddonsExample.

This works towards stuff in #4162

### CODE REVIEW

**Comment by bilderbuchi** [comment]
@arturoc on Linux this is running 14.04 now, and includes the AllAddonsExample, see [here](https://travis-ci.org/openframeworks/openFrameworks/jobs/76333213#L2905) (search for `****` to quickly jump between the build stages in the log - I suggest we keep this convention)
:-)

**Comment by bilderbuchi** [comment]
As far as I'm concerned, this is ready to merge. Ping @arturoc @danoli3 for review.

**Comment by bilderbuchi** [comment]
ah yeah, we should update the AllAddonsExample to the current set of addons sometime, I think. ^^

**Comment by arturoc** [comment]
looks great, thanks!!

**Pull request merged**
