### PR TITLE
cpp 17 / std::filesystem wip 

### PR DESCRIPTION
**Pull request by ofTheo**
This PR is for addressing the last things from #6585 

The code changes needed for OF are all done from previous PRs. 
This PR is to simplify the process of enabling cpp 17 ( or newer ) for a project. 

~~One common theme is that we need to both set the cpp version to c++17 but also define OF_USING_STD_FS=1. 
I am wondering maybe could we just detect  c++17 in ofConstants.h and auto enable OF_USING_STD_FS if not defined~~  
Edit: going with auto detect as it makes everything cleaner. 

Status: 
- [x] macOS Xcode ( [see notes here](https://github.com/openframeworks/openFrameworks/issues/6585#issuecomment-- 1018168686) )
- [x] macOS makefile ( [see notes/questions here](https://github.com/openframeworks/openFrameworks/issues/6585#issuecomment-1018763792) ) 
- [x] windows visual studio 
- [x] windows msys2 
- [x] linux 
- [x] linux arm 
- [x] emscripten
- [ ] android 
- [x] iOS/tvOS

### CODE REVIEW

**Comment by dimitre** [comment]
Great work @ofTheo ! What do you think we could use to opt for different Project.xcconfig versions? 
Maybe something in project generator or a duplicate template for osx?

**Comment by ofTheo** [comment]
Yeah I think maybe the default could be C++17 and then using the PG template system for macOS 10.14 which can't handle C++17 - that should be fairly easy. 

I don't think there are other platforms which couldn't just be C++17 going forward ( will see as we get the rest of the platforms in this PR ).

**Comment by arturoc** [comment]
I think most platforms should support c++17 without problem. I would even remove boost at some point once we deprecate whatever version of macos is the latest that doesn't support c++17. boost was always a temporary thing to get rid of poco until there was support for std::fs

**Comment by ofTheo** [comment]
@arturoc great! sounds good. 
Yeah, I think we could probably keep boost for one more release and then remove. 
macOS 10.14 is now 4 versions behind, so maybe even by the time we get to the next release it could be safe to remove :)

**Comment by ofTheo** [comment]
So msys2 is finally working. Although it is not passing the CI. 
Getting linker errors right now but I _think_ this could be fixed by building msys2 libs with C++17 

```
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/a/openFrameworks/openFrameworks/addons/obj/msys2/Debug/ofxOpenCv/src/ofxCvHaarFinder.o: in function `ofxCvHaarFinder::setup(std::string)':
1287
D:/a/openFrameworks/openFrameworks/addons/ofxOpenCv/src/ofxCvHaarFinder.cpp:76: undefined reference to `cv::CascadeClassifier::load(std::string const&)'
1288
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/a/openFrameworks/openFrameworks/addons/obj/msys2/Debug/ofxOpenCv/src/ofxCvImage.o: in function `ofxCvImage::undistort(float, float, float, float, float, float, float, float)':
1289
D:/a/openFrameworks/openFrameworks/addons/ofxOpenCv/src/ofxCvImage.cpp:660: undefined reference to `cv::error(int, std::string const&, char const*, char const*, int)'
1290
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/a/openFrameworks/openFrameworks/addons/obj/msys2/Debug/ofxPoco/src/ofxXmlPoco.o: in function `ofxXmlPoco::addChild(std::string const&)':
1291
```

You can see more here: https://github.com/openframeworks/openFrameworks/runs/4955173444?check_suite_focus=true 

@oxillo if you have any insight here would be awesome!
Definitely taking a stab at things with msys2 / mingw 🙂

**Comment by ofTheo** [comment]
Thanks @danoli3! 
I _think_ it can work without recompiling libs.
At least managed to do so for most platforms so far - now just trying to get all the platform changes in without breaking others. :P

**Comment by chilina** [comment]
Hey Theo (and others) thank you so much for working on this!  I'm always in awe of how the development team keeps oF current and relevant on so many different platforms.  Looking forward to using the TBB library on macOS with c++17.  I'd help if my skills were better; I'd be completely lost trying to do this.  So many many thanks and excited to see these kinds of projects in process!

**Comment by ofTheo** [comment]
@chilina you're welcome - thanks for the note! 
Hoping to get this finished and merged in soon so people can test with the nightly builds.

**Comment by ofTheo** [comment]
So looks like Android will have to wait till the NDK update from @danoli3 
( see error message at bottom ) 

Everything else is working just need to clean it up a bit and do a couple more tests. 

```
error: invalid value 'c++17' in '-std=c++17'
[376](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:376)
note: use 'c++98' for 'ISO C++ 1998 with amendments' standard
[377](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:377)
note: use 'c++03' for 'ISO C++ 1998 with amendments' standard
[378](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:378)
note: use 'gnu++98' for 'ISO C++ 1998 with amendments and GNU extensions' standard
[379](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:379)
note: use 'c++0x' for 'ISO C++ 2011 with amendments' standard
[380](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:380)
note: use 'c++11' for 'ISO C++ 2011 with amendments' standard
[381](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:381)
note: use 'gnu++0x' for 'ISO C++ 2011 with amendments and GNU extensions' standard
[382](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:382)
note: use 'gnu++11' for 'ISO C++ 2011 with amendments and GNU extensions' standard
[383](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:383)
note: use 'c++1y' for 'ISO C++ 2014 with amendments' standard
[384](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:384)
note: use 'c++14' for 'ISO C++ 2014 with amendments' standard
[385](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:385)
note: use 'gnu++1y' for 'ISO C++ 2014 with amendments and GNU extensions' standard
[386](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:386)
note: use 'gnu++14' for 'ISO C++ 2014 with amendments and GNU extensions' standard
[387](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:387)
note: use 'c++1z' for 'Working draft for ISO C++ 2017' standard
[388](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:388)
note: use 'gnu++1z' for 'Working draft for ISO C++ 2017 with GNU extensions' standard
[389](https://github.com/openframeworks/openFrameworks/runs/5468543091?check_suite_focus=true#step:7:389)
note: use 'cuda' for 'NVIDIA CUDA(tm)' standard
```

**Comment by stungeye** [comment]
I've tested cpp17 and std::filesystem in the night build with Visual Studio 2022. Works great! [Results here](https://github.com/openframeworks/openFrameworks/issues/6488#issuecomment-1141477978).

**Pull request merged**
