### PR TITLE
update assimp addon to support multiple textures, normal map,  new c++ api

### PR DESCRIPTION
**Pull request by ofTheo**
- now loads embedded textures from model files
- supports new 3d formats like gltf, fbx and blender 
- loads all textures that models include ( normal map, emission, occlusion etc ) 
- some robustness fixes 

wip still needs cleanup

### CODE REVIEW

**Comment by ofTheo** [comment]
ahh this is failing due to the libs not being updated from apothecary to the server. 
so fixing the download_libs sooner would be amazing @dimitre . 

I forgot I commented the upload out when I got it publishing to releases:
https://github.com/openframeworks/apothecary/blob/master/scripts/build.sh#L318-L332 

going to manually update the libs now.

**Comment by ofTheo** [comment]
@dimitre  - looks like the libs caching is stopping the new libs getting pulled in. 
Is there a way to disable the cache easily?

**Comment by dimitre** [comment]
Yes I'll do that now

**Comment by dimitre** [comment]
Hey @ofTheo just readd this missing lines on macos
```
      - name: Download libs
         run: ./scripts/$TARGET/download_libs.sh
```

**Comment by ofTheo** [comment]
thanks @dimitre ! missed that :) 

looks like this PR needs a bit more work. 
have to figure out if we can install assimp 5.2 on linux as some of the features requires that.

**Comment by dimitre** [comment]
not sure if it helps anything but in this PR I was experimenting with Ubuntu 20.04, and had to fix one dependency that was wrong on build scripts

https://github.com/openframeworks/openFrameworks/blob/1e80a09af751f4c4500a9ef7760b2016a69e7a75/.github/workflows/build-linux.yml

I installed missing dependencies using an action from github
```
    - uses: awalsh128/cache-apt-pkgs-action@latest
      id: cache-apt    
      with:
        packages: libjack-jackd2-0 libjack-jackd2-dev freeglut3-dev libasound2-dev libxmu-dev libxxf86vm-dev g++ libgl1-mesa-dev libglu1-mesa-dev libraw1394-dev libudev-dev libdrm-dev libglew-dev libopenal-dev libsndfile1-dev libfreeimage-dev libcairo2-dev libfreetype6-dev libssl-dev libpulse-dev libusb-1.0-0-dev libgtk-3-dev libopencv-dev libassimp-dev librtaudio-dev libboost-filesystem-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-libav gstreamer1.0-pulseaudio gstreamer1.0-x gstreamer1.0-plugins-bad gstreamer1.0-alsa gstreamer1.0-plugins-base gstreamer1.0-plugins-good gdb libglfw3-dev liburiparser-dev libcurl4-openssl-dev libpugixml-dev libgconf-2-4 libgtk2.0-0 libpoco-dev libxcursor-dev libxi-dev libxinerama-dev
        version: 1.0
```
and it worked.

**Comment by dimitre** [comment]
I've noticed Linux packages are very light, so uncompressing them shows only partial libraries compiled

Screen Shot 2022-10-06 at 21 18 37

**Comment by ofTheo** [comment]
thanks @dimitre  - but it was unrelated to assimp right?

**Comment by ofTheo** [comment]
Note: older linux installs will still have assimp 3 but 20.04 and newer should have modern assimp 5.1+ with FBX and gltf goodness. All the changes are backwards compatible to asismp 3 but will make some examples that show off assimp 5

**Pull request merged**
