### PR TITLE
ofxiOSVideoPlayer is now using ofAVFoundationPlayer

### PR DESCRIPTION
**Pull request by julapy**
- removed old AVFoundationVideoPlayer classes.
- created a typedef for ofxiOSVideoPlayer to point to ofAVFoundationPlayer
- updated ios/moviePlayerExample

### CODE REVIEW

**Comment by ofTheo** [comment]
would love to get this in. maybe its already been merged with the more recent PRs?

**Comment by pizthewiz** [comment]
It might just need a rebase - in case it is helpful, I've found this guide from the edX team helpful: [How to Rebase a Pull Request](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request).

**Comment by ofTheo** [comment]
can we close this @julapy @danoli3 - or do we still need to get this in? 
thanks!!

**Comment by julapy** [comment]
this is done now

**Comment by bilderbuchi** [comment]
thanks!

**Comment by danoli3** [comment]
Awesome!

**Pull request closed without merging**
