### PR TITLE
Fix #3537

### LINKED ISSUE #3537: ofxOsc doesn't make use of OSC 1.1 types specifications
The OSC 1.1 specifications are not correctly implemented in ofxOsc and the oscpack extra library.
By now, the following message will not be interpreted:
`/to/my/boolean/path T`
nor this one:
`/to/my/boolean/path F`

By the way, oF developers seems to have choosen the `int`, `float` and `string` replacement like that:
`/to/my/path i 0` or `/to/my/path f 0` or `/to/my/path s true` interpreted as **TRUE** and `/to/my/path i 1` or `/to/my/path f 1` or `/to/my/path s false` interpreted as **FALSE**, but that's not enough and NOT according specifications.

### PR DESCRIPTION
**Pull request by groolot**

### CODE REVIEW

**Comment by ofTheo** [comment]
This looks pretty good to me. 
Thanks for working on all the 1.1 types @groolot 

ping @bilderbuchi @openframeworks/core @arturoc for a double check.

**Comment by bilderbuchi** [comment]
Unfortunately, I've been out of ofxOsc too long to do a meaningful review of this.

**Comment by bilderbuchi** [comment]
one thing: has this been tested? with our OSC examples, too?

**Comment by arturoc** [comment]
the only thing i see that might break old code is how the type names have changed from int to i, int64 to h....

i guess most people would be using the enum so it should not be so problematic.

**Comment by groolot** [comment]
@arturoc Indeed, I arbitrary change the string value returned according to what is most relevant to return while waiting for a representation of the type.
I based on the OSC 1.1. specifications to set correctly the values.
It may be preferable to return directly the OFX_OSC_TYPE from the enum, but couldn't be used with this kind of enum: should use a ``std::map``

**Comment by groolot** [comment]
@bilderbuchi : I tested this code with the examples shipped with 0.8.4 = works well
because of no test suite, everything is done manually : not perfect.

BTW, I use this code since 3 months in a project (see https://github.com/PMO-Ecluse/mallarmeGenerateur3D) and it work great without any issue.
It is also connected with the ``ofxOscRouter`` addons by @bakercp and works like a charm :)

**Comment by ofTheo** [comment]
great - thanks for the look over. 
I think it would be fine to get this merged then - @groolot you'll need to pull in master to get the PR to merge though.

**Comment by bilderbuchi** [comment]
Closing this as @groolot has opened another PR for this.

**Pull request closed without merging**
