### PR TITLE
Shadows!

### PR DESCRIPTION
**Pull request by NickHardeman**
Supports point light, directional and spot light shadows.
Only works with programmable renderer. 

### Notes:
Where should the shader start setting the shadow texture locations?
Currently it starts at 10, but I just chose it arbitrarily. 
[ofSetShadowShaderData( shader, 10 );](https://github.com/NickHardeman/openFrameworks/blob/d57f771e6f339ece10b37a4dfeccfc1bbc8d367a/libs/openFrameworks/gl/ofMaterial.cpp#L333)

### TODO:
- [x] Shadow example
- [ ] Add material receive shadows function
- [ ] Add material casts shadows function
- [ ] Area lights?
- [x] More checks and output messages when trying to use with non-programmable renderer
- [ ] Shadows with instanced rendering
- [x] Clean up commented out code
- [x] Comment code better
- [ ] Test with project generator, these shader files have been added [shadow shaders](https://github.com/NickHardeman/openFrameworks/tree/core-shadows/libs/openFrameworks/gl/shaders)
 and [ofShadow.h and .cpp](https://github.com/NickHardeman/openFrameworks/blob/core-shadows/libs/openFrameworks/gl/ofShadow.h) 
- [x] samplerCubeArray requires OpenGL 4+, does not work with OpenGL 3. I changed it so openGL < 4 supports a single point light that uses CUBE_MAP instead of cube map array 
- [x] Currently not going to support GLES. OpenGL ES supports one of each light (needs to be tested).

### Platforms to test:
- [x] OSX xcode
- [x] OSX make
- [x] Linux 64
- [x] Linux arm6
- [x] Linux arm 7
- [x] Visual Studio
- [x] msys2
- [x] Emscripten
- [x] iOS-tvos
- [x] Android

Example:
shadowsExample

Screen Shot 2022-10-10 at 10 27 11 AM

### CODE REVIEW

**Comment by dimitre** [comment]
this is great news @NickHardeman 

You can edit the osx template directly on XCode if you want. 
you only need to install jq (brew install jq)
So after make the changes you can run this
```
plutil -convert json $ofw/scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj 
cd $ofw/scripts/templates/osx/emptyExample.xcodeproj
jq --tab . project.pbxproj > project2.pbxproj
rm project.pbxproj
mv project2.pbxproj project.pbxproj
```
cheers!

**Comment by NickHardeman** [comment]
> this is great news @NickHardeman
> 
> You can edit the osx template directly on XCode if you want. you only need to install jq (brew install jq) So after make the changes you can run this
> 
> ```
> plutil -convert json $ofw/scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj 
> cd $ofw/scripts/templates/osx/emptyExample.xcodeproj
> jq --tab . project.pbxproj > project2.pbxproj
> rm project.pbxproj
> mv project2.pbxproj project.pbxproj
> ```
> 
> cheers!

Yes thank you! I was editing it via TextEdit and it was unpleasant to say the least. Do you know if I can run the tests locally on OSX? I tried running scripts/ci/osx/run_tests.sh but am getting different errors than when it's run on git. Any ideas?

**Comment by ofTheo** [comment]
I think it might be the caching of the OF lib. 
Try commenting these lines out from the workflow: 

https://github.com/openframeworks/openFrameworks/blob/master/.github/workflows/build-macos.yml#L27-L36

**Comment by NickHardeman** [comment]
> I think it might be the caching of the OF lib. Try commenting these lines out from the workflow:
> 
> https://github.com/openframeworks/openFrameworks/blob/master/.github/workflows/build-macos.yml#L27-L36

Hmm, I tried that but it still fails.

**Comment by ofTheo** [comment]
Awesome!! 
Good to merge?

**Comment by NickHardeman** [comment]
Trying to address the issue of shadows showing up on the non light facing side
Screen Shot 2022-10-13 at 10 41 56 AM

**Pull request merged**
