### PR TITLE
Fix #3603 Solves OF:master build errors in CB

### LINKED ISSUE #3603: OF:Master fails to build on CB
When trying to build the current openframeworks:master in Code:Blocks, you get the following errors:

1. ofSoundStream.h => error: 'UINT_MAX' was not declared in this scope (7 times)
2. ..\..\..\libs\glew\lib\win_cb\glew32s.lib||No such file or directory
3. Several undefined references to 'ofMainLoop' and 'ofSoundBuffer'

I will send a pull request shortly with fixes that helped me solve these three issues.

### PR DESCRIPTION
**Pull request by AmnonOwed**
Fixes the three problems in issue #3603 which resulted in errors when building openframeworks:master in Code:Blocks. The solutions are respectively:

1. Add #include <climits> to ofSoundStream.h
2. Copy glew32s.lib from libs\glew\lib\vs\ to libs\glew\lib\win_cb\
3. Add references to 'ofMainLoop' and 'ofSoundBuffer' in openFrameworksLib.cbp

### CODE REVIEW

**Comment by arturoc** [comment]
thanks!

**Comment by bilderbuchi** [comment]
@bakercp will we need an apothecary update for that additional glew binary?
btw, an openframeworks apothecary team would be practical!

**Comment by kylemcdonald** [comment]
@bilderbuchi i created @openframeworks/apothecary

**Comment by bilderbuchi** [comment]
@kylemcdonald great, thanks!

**Pull request merged**
