### PR TITLE
Implement flatNormals() for polyhedrons and low-poly meshes

### PR DESCRIPTION
**Pull request by hamoid**
Implement mesh.flatNormals(); to give it a flat look.

Works only when mode = OF_PRIMITIVE_TRIANGLES, same as existing smoothNormals() method.

```cpp
ofLight light;
ofMaterial material;
vector<ofMesh> meshes;

//--------------------------------------------------------------
void ofApp::setup() {
    ofSetBackgroundColor(10, 10, 10);
    ofEnableDepthTest();

    //directional light
    light.setDirectional();
    light.setSpecularColor(ofColor(255));
    light.setDiffuseColor(ofColor(255));
    light.setAmbientColor(ofColor(100));
    light.setOrientation(ofVec3f(0, 180, 0));

    //material
    material.setShininess(120);
    material.setSpecularColor(ofColor(0));
    material.setDiffuseColor(ofColor(200));
    material.setAmbientColor(ofColor(0));

    //mesh
    meshes.push_back(ofMesh::sphere(100, 12, OF_PRIMITIVE_TRIANGLES));
    meshes.push_back(ofMesh::sphere(100, 12, OF_PRIMITIVE_TRIANGLES));
    meshes.push_back(ofMesh::icosphere(100));
    meshes.push_back(ofMesh::icosphere(100));
    meshes.push_back(ofMesh::icosahedron(100));
    meshes.push_back(ofMesh::icosahedron(100));

    meshes[0].flatNormals();
    meshes[2].flatNormals();
    meshes[4].flatNormals();
}

//--------------------------------------------------------------
void ofApp::draw() {
    ofEnableLighting();
    light.enable();
    material.begin();

    for(size_t i = 0; i < meshes.size(); i++) {
        ofPushMatrix();
        ofTranslate(
            ofMap(i / 2, 0, 2, ofGetWidth() * 0.25f, ofGetWidth() * 0.75f),
            ofMap(i % 2, 0, 1, ofGetHeight() * 0.25f, ofGetHeight() * 0.75f)
        );
        ofRotateDeg(ofGetFrameNum(), 1, 1, 1);
        meshes[i].draw();
        ofPopMatrix();
    }

    material.end();
    light.disable();
    ofDisableLighting();
}

```

2017-06-08-113913_1024x768_scrot

Screenshot taken after applying both this pull request and https://github.com/openframeworks/openFrameworks/pull/5650

### CODE REVIEW

**Comment by arturoc** [comment]
thath's great! the name is a little strange though, perhaps something like?

```
ofMesh::smoothNormals();
ofMesh::flatNormals();
```

**Comment by hamoid** [comment]
Yeah I wasn't sure about the name. I'll use flatNormals() if no one complains :)

**Comment by hamoid** [comment]
Ok I renamed noSmoothNormals() to flatNormals() :)

**Comment by arturoc** [comment]
thanks!!

**Pull request merged**
