### PR TITLE
.serialize() appears to be deprecated

### PR DESCRIPTION
**Pull request by agoodney**

### CODE REVIEW

**Comment by arturoc** [comment]
hey, thanks, the problem with this PR is that it removes the serialization completely. the correct fix would be to use:

```
ofSerialize(settings, parameters)
```

and ofDeserialize. can you add those?

**Comment by agoodney** [comment]
So I'm pretty sure my change doesn't fix this. At least in Xcode it seems like the right header file to find the XML version of ofSerialize/ofDeserialize isn't being included. The JSON version is found though.

Any advice?

**Comment by arturoc** [comment]
i think the problem is that you are not up to date with latest master where those functions are already there

**Comment by arturoc** [comment]
going to merge this anyway since it seems to have passed the tests

**Pull request merged**
