### PR TITLE
critical bugfix for ofReadOnlyParameter and isReferenceTo

### PR DESCRIPTION
**Pull request by underdoeg**
Sorry, I introduced a compiler error with read only parameters. This fixes it.

### CODE REVIEW

**Comment by arturoc** [comment]
can we instead friend ofReadOnlyPArameter with ofParameter so it returns the correct value?

**Comment by underdoeg** [comment]
I'd love to do this. But I didn't know how since ofReadOnlyParameter has not only the PArameterType but also the friend class Type. And afaik you cannot just go ```friend class ofReadOnlyParameter<>```. Or am I forgetting something?

We could have an ofAbstractReadOnlyParameter but it struck me as a little bit of an overkill...

**Comment by underdoeg** [comment]
oh right... I got it now. Did not know about templated friend classes. Nice feature though. This should do it.

**Comment by arturoc** [comment]
thanks, this now contains some changes that are in master already, i think it should be fine but if you can try to merge master into this branch to see if those changes go away?

**Comment by underdoeg** [comment]
yes. I pulled before commiting and then it got merged automatically. I can clean it up but I think it should be fine.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
