### PR TITLE
Raspberrypi uinput fallback

### PR DESCRIPTION
**Pull request by jedahan**
Let us enjoy dev-ing with vnc instead of hardware screens
More descriptions in the commit messages

### CODE REVIEW

**Comment by tpltnt** [comment]
@jedahan can you resolve the conflicts with the current master branch? I would do the review then.

**Comment by jedahan** [comment]
Working on it this weekend.

**Comment by tpltnt** [comment]
looks good to me. ping @openframeworks/core

**Comment by arturoc** [comment]
can this be merged?

**Comment by jedahan** [comment]
Yeah it is ready to be merged.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
