### PR TITLE
iOS Template Project Update - Icon / Splash / iPhone6

### PR DESCRIPTION
**Pull request by danoli3**
Previous PR: https://github.com/openframeworks/openFrameworks/pull/4591

Fixes issues related to iPhone6 and greater not being supported by template project out of the box.
Fixes: https://github.com/openframeworks/openFrameworks/issues/4566

- Adds Launch Screen
- Adds ImageAssets for Icons / SplashScreen
- New and updated Icon and SlashScreen for iOS
- iOS 7 Minimum for Project.
screen shot 2015-11-17 at 4 38 10 am

### CODE REVIEW

**Comment by danoli3** [comment]
This is good to merge now.

**Comment by bakercp** [comment]
So just to be, the iOS min version is being incremented based on our support `latest_OS - 2` formula?

**Comment by danoli3** [comment]
@bakercp Mainly this: https://github.com/openframeworks/openFrameworks/issues/3977#issuecomment-114569430

**Comment by bakercp** [comment]
We're reviewing!

**Comment by grayfuse** [comment]
Oooo, having the LaunchScreen is going to be very useful for newer iOS 9 builds, not to mention having a storyboard with proper constraints in it. Looks good!

**Comment by bakercp** [comment]
Thanks @grayfuse !  Merging.

**Comment by bakercp** [comment]
Thanks @danoli3 exciting stuff!

**Comment by danoli3** [comment]
It's also the only way to support the iPhone6 and iPhone6S / iPad Pro

**Comment by ofZach** [comment]
@danoli3 as a result of this PR maybe the PG needs to be updated?  it seems some assets don't live in bin/data anymore.  can you check?  

associated issue (I tried to flag the lines I think are relevant): 

https://github.com/openframeworks/projectGenerator/issues/118

**Pull request merged**
