### PR TITLE
remove external dependencies from main repo

### PR DESCRIPTION
**Pull request by arturoc**
This removes all external dependencies from the main repo and adds download scripts to download them from the ci server where the compiled libraries are uploaded from the travis and appveyor test servers.

The folder structure is left as it was by now

### CODE REVIEW

**Comment by bakercp** [comment]
This is great.  Could you add a quick bit of documentation on how to use the download scripts?  They may be in this PR ... there's just a lot of changes :)

**Comment by arturoc** [comment]
This is working now fine for all platforms. Every library is being automatically built in the test servers and uploaded to http://ci.openframeworks.cc/libs There's scripts in the particular platform folder inside scripts to download the libraries automatically.

I've removed some libraries that were outdated:

- glut
- glu
- quicktime

I guess we can move them with the respective source code to addons in case people need them to make old projects work or similar.

Also osx is now at 10.9 as min sdk version.

If nobody has any problem i'll merge it tomorrow or so

**Comment by danoli3** [comment]
😄👍👍👍👍

**Comment by bilderbuchi** [comment]
at last, this happened! great job! :100: :+1: :tada: :shipit:

**Pull request merged**
