### PR TITLE
Fix shadow variable warnings.

### PR DESCRIPTION
**Pull request by bakercp**

### CODE REVIEW

**Comment by arturoc** [comment]
where is this warning happening?

**Comment by bakercp** [comment]
It happens during compiling on these files.  Honestly I'm not sure why -- c++ is obviously able to infer the correct variables from context, but I guess that's why it's a warning and not an error.  Basically it's happening when the name of the parameter is the same as the name of the variable being set.  I think style-wise, we should avoid shadowed variables because it can be more difficult to spot errors.

**Comment by arturoc** [comment]
sorry i meant in which platform. i've never seen this warning and i've used this pattern in several compilers, including visual studio, without problem

**Comment by bakercp** [comment]
I'm getting them on Xcode 6.4 -- that said, I did modify the project file to emit more warnings.

**Comment by arturoc** [comment]
mmh, that's really strange, we use this in lots of places, addons... i wonder if it's a bug in a specific version of clang

**Comment by bilderbuchi** [comment]
I'd also expect this to work correctly as-is. I don't know the exact error message, is it possible that it can be misinterpreted, and the collision is with a variable name in an _outside_ scope? i.e. 
```
int value = 5;
myfunc(value); //where the declaration is myfunc(int value)
```

**Comment by bakercp** [comment]
Yeah, I'm not going to defend conservative compilers :) If you want to check it out, you can just compile with `-Wshadow`.  Here's a sample of the whole output ...


```
In file included from src/ofApp.h:29:
In file included from ../../../libs/openFrameworks/ofMain.h:9:
In file included from ../../../libs/openFrameworks/utils/ofURLFileLoader.h:2:
In file included from ../../../libs/openFrameworks/events/ofEvents.h:5:
In file included from ../../../libs/openFrameworks/events/ofEventUtils.h:4:
../../../libs/openFrameworks/events/ofEvent.h:141:16: warning: declaration shadows a field of 'Function<T>' [-Wshadow]
                Function(int priority, std::function<bool(const void*,T&)> function,  std::unique_ptr<BaseFunctionId>&& id )
                             ^
../../../libs/openFrameworks/events/ofEvent.h:150:7: note: previous declaration is here
                int priority;
                    ^
../../../libs/openFrameworks/events/ofEvent.h:141:62: warning: declaration shadows a field of 'Function<T>' [-Wshadow]
                Function(int priority, std::function<bool(const void*,T&)> function,  std::unique_ptr<BaseFunctionId>&& id )
                                                                           ^
../../../libs/openFrameworks/events/ofEvent.h:151:39: note: previous declaration is here
                std::function<bool(const void*,T&)> function;
                                                    ^
../../../libs/openFrameworks/events/ofEvent.h:141:107: warning: declaration shadows a field of 'Function<T>' [-Wshadow]
                Function(int priority, std::function<bool(const void*,T&)> function,  std::unique_ptr<BaseFunctionId>&& id )
                                                                                                                        ^
../../../libs/openFrameworks/events/ofEvent.h:152:29: note: previous declaration is here
                clone_ptr<BaseFunctionId> id;
                                          ^
../../../libs/openFrameworks/events/ofEvent.h:158:16: warning: declaration shadows a field of 'of::priv::Function<void>' [-Wshadow]
                Function(int priority, std::function<bool(const void*)> function,  std::unique_ptr<BaseFunctionId> && id )
                             ^
../../../libs/openFrameworks/events/ofEvent.h:167:7: note: previous declaration is here
                int priority;
                    ^
../../../libs/openFrameworks/events/ofEvent.h:158:59: warning: declaration shadows a field of 'of::priv::Function<void>' [-Wshadow]
                Function(int priority, std::function<bool(const void*)> function,  std::unique_ptr<BaseFunctionId> && id )
                                                                        ^
../../../libs/openFrameworks/events/ofEvent.h:168:36: note: previous declaration is here
                std::function<bool(const void*)> function;
                                                 ^
../../../libs/openFrameworks/events/ofEvent.h:158:105: warning: declaration shadows a field of 'of::priv::Function<void>' [-Wshadow]
                Function(int priority, std::function<bool(const void*)> function,  std::unique_ptr<BaseFunctionId> && id )
                                                                                                                      ^
../../../libs/openFrameworks/events/ofEvent.h:169:29: note: previous declaration is here
                clone_ptr<BaseFunctionId> id;
                                          ^
../../../libs/openFrameworks/events/ofEvent.h:185:21: warning: declaration shadows a field of 'FunctionId<TObj, TMethod>' [-Wshadow]
                FunctionId(TObj * listener, TMethod method)
                                  ^
../../../libs/openFrameworks/events/ofEvent.h:182:10: note: previous declaration is here
                TObj * listener;
                       ^
../../../libs/openFrameworks/events/ofEvent.h:185:39: warning: declaration shadows a field of 'FunctionId<TObj, TMethod>' [-Wshadow]
                FunctionId(TObj * listener, TMethod method)
                                                    ^
../../../libs/openFrameworks/events/ofEvent.h:183:11: note: previous declaration is here
                TMethod method;
                        ^
../../../libs/openFrameworks/events/ofEvent.h:307:21: warning: declaration shadows a field of 'FunctionId<TObj, TMethod>' [-Wshadow]
                FunctionId(TObj * listener, TMethod method)
                                  ^
../../../libs/openFrameworks/events/ofEvent.h:304:10: note: previous declaration is here
                TObj * listener;
                       ^
../../../libs/openFrameworks/events/ofEvent.h:307:39: warning: declaration shadows a field of 'FunctionId<TObj, TMethod>' [-Wshadow]
                FunctionId(TObj * listener, TMethod method)
                                                    ^
../../../libs/openFrameworks/events/ofEvent.h:305:11: note: previous declaration is here
                TMethod method;
                        ^
```

**Comment by bakercp** [comment]
If you want to quickly modify an existing xcode project, just enable "Hidden Local Variables" in warnings.

**Comment by arturoc** [comment]
googling a bit it seems that clang is specially conservative about this flag. the only case in which this can be a problem is because one could get confused by the variable being the parameter or the instance variable but doesn't suppose any problem at memory level or anything like that. since the current code is fine i think we should leave it as it is and perhaps discuss in general if we want to enable this warning in xcode and fix the warnings everywhere.

**Comment by bakercp** [comment]
I agree.  I'll close this and we can talk about this level of detail after
0.9.0.


---
http://christopherbaker.net

**Pull request closed without merging**
