### PR TITLE
Missing texCoordVarying in vert shader example

### PR DESCRIPTION
**Pull request by MatillaMartin**
Added the copy from vert to frag for clarification of use in the example

### CODE REVIEW

**Comment by arturoc** [comment]
i think the correct thing would be to remove that variable from the fragment since it's not use at all?

**Comment by MatillaMartin** [comment]
true, is there another shader example that shows how to send the variable
from the vertex to the fragment?

**Comment by MatillaMartin** [comment]
ok yep, there are many examples in examples/shader! Modifying pull request

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
