### PR TITLE
Feature : Freeimage flags on ofImageLoadSettings

### PR DESCRIPTION
**Pull request by elliotwoods**
Allow the user to load RAW photo images (e.g. CR2, etc) without processing/debayering.
This is useful when they will perform this processing themselves in a custom way

### CODE REVIEW

**Comment by elliotwoods** [comment]
Ah - i see that 2 other changes creeped in here:

1. A fix for overflow when taking the lightness value (if you add r, g, b then divide by 3, then you will have an overflow. Whereas if you divide first you can loose accuracy with int types).
2. Re-introduce the `size()` getter for ofThreadChannel (not sure where that disappeared to)

**Comment by ofTheo** [comment]
@elliotwoods - thanks for this! 
I found a good workflow for doing clean PRs to OF after having similar issues over and over again. 

Just posted this in [another thread](https://github.com/openframeworks/openFrameworks/pull/6764#issuecomment-1097289689) for someone else, but maybe it is helpful? 
Essentially the TLDR is just to never use your own repo locally for doing PRs. Have a local OF repo which is upstream and then make branches off of that which you push to your repo. 

Here are the steps: 

```
mkdir ofMainRepo 
cd ofMainRepo
git clone -–depth 1 https://github.com/openframeworks/openFrameworks 
```

Anytime you want to do a PR: 
```
//1 - update your OF clone master branch to be up to date 
git pull https://github.com/openframeworks/openFrameworks master 

//2 - make a new branch for your fix
git checkout -b bugfix-ttf 

//3 - copy over the changes just for the PR into this location  

//4 - git add the file(s) and commit 

//5 - push your changes for just the PR to your repo ( it will create the branch bugfix-ttf  automatically ) 
git push https://github.com/YOURUSERNAME/openFrameworks 

//6 - go to https://github.com/YOURUSERNAME/openFrameworks and it should suggest you might want to make a PR with the new branch

//7 - Once you are done go back to master so you don't make changes on the wrong branch 
git checkout master 

//7 - repeat :) 
```

**Comment by ofTheo** [comment]
Hey @elliotwoods I can delete the two additional commits if your cool with that ( it might get pushed to your freeimage flags branch ). Otherwise, you could cherry pick the commit into a new PR?

**Comment by danoli3** [comment]
@ofTheo if you upstream their fork you can just re-base it and push a new branch to your repo and PR the fixed head and ref this PR in comments, retains the changes

**Comment by elliotwoods** [comment]
Thank you all! 
Apologies for the other changes being in there. To be honest those changes should have been inside oF anyway (and thanks @danoli3 for merging them in the other PR)

**Comment by ofTheo** [comment]
Thanks all and @elliotwoods!! 

Definitely please send more PRs - always helpful. 
If you do the approach shown above it makes it super easy not to include unwanted commits.

**Pull request closed without merging**
