### PR TITLE
Doxygen sections ofRectangle & ofVec2f

### PR DESCRIPTION
**Pull request by HalfdanJ**
Changed sections to  `\section` syntax and internal functions to `\internal` syntax

@bakercp

### CODE REVIEW

**Comment by arturoc** [comment]
i'm changing these 2 classes a lot right now in the glm branch so i'll wait until that's settled to merge this

**Comment by HalfdanJ** [comment]
Oh okay.. Bad pick.

**Comment by bakercp** [comment]
Hi @arturoc if I get these merge-ready can we merge them (documentation would be nice for a course I'm teaching).

**Comment by arturoc** [comment]
sure but some files are not mergeable anymore cause there's some conflicts, if you can rebase them we can merge all the documentation PR's already

**Comment by bakercp** [comment]
@arturoc ping @HalfdanJ  Would like to get these docs merged.

**Pull request closed without merging**
