### PR TITLE
Fix windowMode not affecting some functions

### PR DESCRIPTION
**Pull request by PTS93**
See this issue for more details: https://github.com/openframeworks/openFrameworks/issues/5861

### CODE REVIEW

**Comment by arturoc** [comment]
thanks! please be sure to check that everything works after this change. this has been like that for a while and i'm concerned that some logic might be depending on having 2 copies of this value. Perhaps check that all 3 modes still work correctly and that values like the window size from ofGetWindowSize are returned correctly in all 2 modes and after calling ofToggleFullscreen back and forth

**Comment by PTS93** [comment]
I compiled and tested it on Linux. As I removed the declaration of the local variable as well it should have thrown an error on compile time.
I also went through every use of the variable and it only ever checked what mode it was in by only using either way but never both of them.
I can't test on other platforms atm unfortunately.

**Comment by PTS93** [comment]
So turns out I tested with an old version..
In the latest master compilation failed because the static function resize_cb is acessing the local var:
https://github.com/openframeworks/openFrameworks/blob/7e62212d5845ac521ce4302b10c6b0a08060b78b/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L1510

I know fixed it by adding the local var again and assigning it the value from the settings in setup.
I will add this commit here but let me know if this is how you want to proceed. It seems it makes sense to do the reverse by using the local var everywhere if the other window classes do the same aswell. Or we need to refactor a bit more to fix functions like resize_cb as well.

**Comment by arturoc** [comment]
I'm going to close this since it's currently breaking some things and there's been no answer from the @PTS93 

PR #5875 should fix the original issue

**Comment by PTS93** [comment]
Oh I didn't see that the the last commit still caused build errors. Thats odd, it was compiling fine with a fresh Master clone.

**Pull request closed without merging**
