### PR TITLE
added note to ofEasyCam

### PR DESCRIPTION
**Pull request by tpltnt**
Hi,
I added a note to ofEasyCam in order to address #618.
Cheers,
tpltnt

### CODE REVIEW

**Comment by bilderbuchi** [comment]
shouldn't this also be documented for setPosition() (which is the function that does not work everywhere)?

**Comment by arturoc** [comment]
this sounds more like a bug rather than something we want to document

**Comment by tpltnt** [comment]
@arturoc fair call. My proposal just followed @bilderbuchi statement.

**Comment by bilderbuchi** [comment]
The relevant bug is #618. I'm going to close this, but leave the branch alive for now.

**Pull request closed without merging**
