### PR TITLE
Fix video emscripten

### LINKED ISSUE #7627: emscripten - regression from #7617 - video files are not found
I think we have a regression from this #7617 
Not sure why but since #7617 ( cc @artificiel  ) moving the html to a directory and not copying the data/ folder videos now don't load. 

```
emrun bin/opencvExample 

Now listening at http://0.0.0.0:6931/
 ofxEmscriptenVideoPlayer::load 
127.0.0.1 - - [01/Sep/2023 10:04:41] code 404, message File not found: /Users/theo/Downloads/of_v0.12.0_osx_release/examples/computer_vision/opencvExample/bin/opencvExample/data/fingers.mp4
127.0.0.1 - - [01/Sep/2023 10:04:41] "GET /data/fingers.mp4 HTTP/1.1" 404 -

```

copying `data/` into `opencvExample/` fixes the issue. 

@Jonathhhan as he has some insight into how file loading is working from index.data 

but this might warrant a patch-release.

### PR DESCRIPTION
**Pull request by ofTheo**
add in auto muting for emscripten 
switch in mp4 for opencvPeopleDetection example to make compatible with emscripten 

with these changes we should be good to 
close #7627 #7626

### CODE REVIEW

**Comment by Jonathhhan** [comment]
@ofTheo first I thought exactly that is the solution, but then I saw it works for Safari only (deleted my comment because of that):
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/audioTracks

**Comment by ofTheo** [comment]
ahh thanks @Jonathhhan - I can make it so it detects just for safari.

**Comment by Jonathhhan** [comment]
I have another Idea, to check it with the audio context. I will have a try...

**Comment by ofTheo** [comment]
awesome - thanks @Jonathhhan. feel free to do a PR for it if it works :)

**Pull request merged**
