### PR TITLE
Revert "ofUtils.cpp warning  [-Wmisleading-indentation]"

### PR DESCRIPTION
**Pull request by ofTheo**
Reverts openframeworks/openFrameworks#6891

### CODE REVIEW

**Comment by ofTheo** [comment]
undoing #6891 as fixed in @2bbb 's PR

**Comment by 2bbb** [comment]
If my PR is involved, I'll fix it so, please point it out.

**Comment by ofTheo** [comment]
yeah the issue is #6891 caused conflicts with your PR #6893 
figured it would be better to merge yours first and then fix the warning after ( or have you fix it in your PR )

**Comment by 2bbb** [comment]
oh, I see!

**Pull request merged**
