### PR TITLE
ios ofxOpenALSoundPlayer compiler bug fix.

### PR DESCRIPTION
**Pull request by julapy**

### CODE REVIEW

**Comment by bilderbuchi** [comment]
Why remove the `const` from a getter method, this looks weird?

**Comment by julapy** [comment]
have added some reasoning in #3789
not the best solution but it is the safest for a quick patch.

**Comment by danoli3** [comment]
Sounds good for now, we can open an issue to fix the const ideas later.

We just can't compile without this fix, lets get this on master now.

**Comment by danoli3** [comment]
I'll merge this into the iOS Changes 0.9 PR, as those compiler settings seems to be having the biggest issue with it and just continue from there.

**Comment by julapy** [comment]
that sounds like a good plan.
i'll merge this and open up an issue to change the `isPlaying` back to `const` and update that function internally to work as a const function.

**Comment by danoli3** [comment]
Nice!

**Pull request merged**
