### PR TITLE
+ ofSoundDevice

### LINKED ISSUE #2785: make ofSoundStream::listDevices return vector of ofSoundDevice
ofSoundStream listDevices should return a vector of ofSoundDevice similar as it's with ofVideoGrabber

### PR DESCRIPTION
**Pull request by admsyn**
This closes #2785

It adds a new struct `ofSoundDevice`, which represents a sound device with a numeric ID, name, number of i/o channels and vector of sample rates, modeled after the `RtAudio::DeviceInfo` struct.

This PR changes `ofSoundStreamListDevices()` into a function which returns a `vector<ofSoundDevice>` and now *optionally* logs to the console. It also adds a function `ofSoundStreamGetMatchingDevices(...)` which lets you find a device by partial name, and optionally with an i/o channel count. You can also set an ofSoundStream's device with an ofSoundDevice directly (instead of just via ID). Does this fit your use-case @kylemcdonald ?

On my OSX laptop I get the following:

**ofSoundStreamGetMatchingDevices("Soundflower")**
```
(std::vector<ofSoundDevice, std::allocator<ofSoundDevice> >) $0 = size=2 {
  [0] = {
    name = "ma++ ingalls for Cycling '74: Soundflower (2ch)"
    deviceID = 2
    inputChannels = 2
    outputChannels = 2
    isDefaultInput = false
    isDefaultOutput = false
    sampleRates = size=6 {
      [0] = 44100
      [1] = 48000
      [2] = 88200
      [3] = 96000
      [4] = 176400
      [5] = 192000
    }
  }
  [1] = {
    name = "ma++ ingalls for Cycling '74: Soundflower (64ch)"
    deviceID = 3
    inputChannels = 64
    outputChannels = 64
    isDefaultInput = false
    isDefaultOutput = false
    sampleRates = size=6 {
      [0] = 44100
      [1] = 48000
      [2] = 88200
      [3] = 96000
      [4] = 176400
      [5] = 192000
    }
  }
}
```

**ofSoundStreamGetMatchingDevices("Apple", 0, 2)**
```
(std::vector<ofSoundDevice, std::allocator<ofSoundDevice> >) $0 = size=1 {
  [0] = {
    name = "Apple Inc.: Built-in Output"
    deviceID = 1
    inputChannels = 0
    outputChannels = 2
    isDefaultInput = false
    isDefaultOutput = true
    sampleRates = size=4 {
      [0] = 44100
      [1] = 48000
      [2] = 88200
      [3] = 96000
    }
  }
}
```

Tested on OSX, iOS and Windows, but the change touches all platforms due to the function signature change. The Android and Emscripten changes are a shot in the dark, pinging @arturoc

### CODE REVIEW

**Comment by admsyn** [comment]
@kylemcdonald yes it's basically it's own thing. Now that #3479 is merged I'll finish this up and tackle the related #3509 as well.

**Comment by kylemcdonald** [comment]
just spoke with @ofZach about this and he's in favor of `printDeviceList()` and `getDeviceList()` (which both do what you expect them to do).

i like encouraging people to say `ofLog() << object.getDeviceList()` but there's no problem with a helper method :)

**Comment by admsyn** [comment]
Alright I think this PR covers the concerns brought up by @arturoc and @kylemcdonald :
- `operator<<` for `ofSoundDevice` and `std::vector<ofSoundDevice>`, no `getDescription()`
- separated `listDevices()` into `printDeviceList()` and `getDeviceList()` functions
- deprecated `listDevices()` and removed the bool param from earlier in this PR
- updated examples accordingly

**Comment by kylemcdonald** [comment]
awesome! this looks perfect to me now.

if one more person can check it out briefly, let's merge it.

**Comment by admsyn** [comment]
Thanks, @bilderbuchi fixed it (it did work correctly in Xcode fwiw).

**Pull request merged**
