### PR TITLE
Emscripten float textures

### PR DESCRIPTION
**Pull request by Jonathhhan**
This makes float textures work with Emscripten.

### CODE REVIEW

**Comment by ofTheo** [comment]
Thanks @Jonathhhan! 
( cc @NickHardeman - not sure if you needed float textures for some of the emscripten fixes you were doing )

**Comment by Jonathhhan** [comment]
@ofTheo this enables also allocating fbos with GL_RGBA32F, I needed that for a case where I need pixel accuracy in a shader.
First I wanted to use GL_RGB32F which I am using for desktop, but somehow only GL_RGBA32F works for Emscripten (I guess, thats changeble with the right settings).

**Comment by ofTheo** [comment]
Awesome!
Thanks @Jonathhhan 👍

**Comment by Jonathhhan** [comment]
@ofTheo maybe they work for GLES in general (if so, my change needs to be adjusted)?

**Comment by NickHardeman** [comment]
@Jonathhhan float fbo textures is exactly what I need right now. Any ideas about how to get GL_RGB32F?

**Comment by Jonathhhan** [comment]
@NickHardeman sadly not, I tried it, but without luck (which is probably because my lack of knowledge). Actually the flag for RGB32F seems to be set, if I am not wrong, but without effect.

**Comment by Jonathhhan** [comment]
@NickHardeman @ofTheo Maybe you just need to change line 173 to: `#if not defined TARGET_OPENGLES || defined TARGET_EMSCRIPTEN`?
I will try that this weekend.

**Comment by NickHardeman** [comment]
Hi @Jonathhhan, I've tried a bunch of combinations and tried just using straight gl calls to create a frame buffer and attach a texture. That also only works with _GL_RGBA32F_. According to this document, seems like only _GL_GRBA32F_ is required for both render buffers and textures. And _GL_RGB32F_ is only required for textures.
https://www.khronos.org/opengl/wiki/Image_Format

**Comment by Jonathhhan** [comment]
Hi @NickHardeman. Thanks, then it seems not to be available. But I think the only downside is that RGBA32F takes a quarter more space than RGB32F?

**Comment by NickHardeman** [comment]
Yes agreed. What's kind of odd is that RGBA, RG, RED are supported. 🤷

**Comment by Jonathhhan** [comment]
And if it works for GLES in general (did not test that), you can just leave the `#if not defined TARGET_OPENGLES || defined TARGET_EMSCRIPTEN` ifdefs that I made away...

**Pull request merged**
