### PR TITLE
WIP PR for Github Actions

### PR DESCRIPTION
**Pull request by ofTheo**
Don't merge yet. 
Got all [platforms working](https://github.com/ofTheo/openFrameworks/actions/runs/460238391).   

Currently Working:
- macOS Xcode 
- macOS Makefile 
- Linux 64 
- Linux Arm 
- Emscripten 
- Android 
- upload step with `./scripts/ci/upload_of_lib.sh;` 

See the progress here:
https://github.com/ofTheo/openFrameworks/actions

### CODE REVIEW

**Comment by oxillo** [comment]
I have MSYS2 et VS working in GHA. Need to  cleanup my attmpt to have MacOS/Linux  working...

**Comment by ofTheo** [comment]
@oxillo oh cool! 
I have macOS / Linux / Emscripten all working fine. If you wanted to do a yml file for MSYS2 and one for VS you could PR to:
https://github.com/ofTheo/openFrameworks/tree/github-actions/ I will merge it in. 

Pretty much only have Android left to figure out and its kind of annoying, because the prebuilt linux pg won't run on 16.04 due to linking issues. I tried installing the missing libs but getting a segfault, so looking at either running 14.04 on Github Actions via Docker ( which is supported ) or building the linux pg on 16.04 so it doesn't segfault.

**Comment by ofTheo** [comment]
Android is working now too 🎉:
https://github.com/ofTheo/openFrameworks/runs/1640606770?check_suite_focus=true 

Going to do some cleanup and caching so that it only builds the PG if needed. 
Probably could go back to the old approach too once the PG scripts are moved over to Github Actions

**Comment by ofTheo** [comment]
Okay pretty much everything is working except tvOS. I got VS and Msys2 from @oxillo !
For tvOS I just need to fix a legacy Xcode issue with the way projects link to the dependency then it should be all good to go.

**Comment by ofTheo** [comment]
@oxillo thanks for the PR!

I just noticed the msys2 is missing the run_tests.sh that AppVeyor has in `scripts/ci/msys2/run_tests.sh` 
And VS is missing the `run_tests.bat` call. 

Feel free to send another PR to my branch or I can take a stab too if you prefer?

**Comment by danoli3** [comment]
Amazing!!!!!!!!

**Comment by ofTheo** [comment]
hey @danoli3 def do a new PR if that's okay for the curl/wget stuff?
This PR should be merged soon. So once the CI is all passing it will be easy to PR against OF main repo. 

Feel free to PR to my [github-actions](https://github.com/ofTheo/openFrameworks) branch in the meantime for testing purposes. 
A PR on that branch will trigger the Github Actions CI etc.

**Pull request merged**
