### PR TITLE
[macOS] fix c++23 issue using make

### PR DESCRIPTION
**Pull request by dimitre**
closes https://github.com/openframeworks/openFrameworks/issues/8111

### CODE REVIEW

**Comment by danoli3** [comment]
Still confusing since c++23 is available in Xcode 15. 

Did you make sure you have run xcode-select --install

**Comment by danoli3** [comment]
sudo softwareupdate --all --install --force

**Comment by dimitre** [comment]
I've run it again by editing config.make
```
export MAC_OS_CPP_VER = -std=c++23
```
and the full error is
```
error: error: invalid value 'c++23' in '-std=c++23'
invalid value 'c++23' in '-std=c++23'
note: use 'c++98' or 'c++03' for 'ISO C++ 1998 with amendments' standardnote: 
use 'c++98' or 'c++03' for 'ISO C++ 1998 with amendments' standard
note: use 'gnu++98' or 'gnu++03' for 'ISO C++ 1998 with amendments and GNU extensions' standard
note: use 'c++11' for 'ISO C++ 2011 with amendments' standard
note: use 'gnu++11' for 'ISO C++ 2011 with amendments and GNU extensions' standardnote: 
use 'gnu++98' or 'gnu++03' for 'ISO C++ 1998 with amendments and GNU extensions' standardnote: 
use 'c++14' for 'ISO C++ 2014 with amendments' standard
note: note: use 'c++11' for 'ISO C++ 2011 with amendments' standarduse 'gnu++14' for 'ISO C++ 2014 with amendments and GNU extensions' standard

note: note: use 'gnu++11' for 'ISO C++ 2011 with amendments and GNU extensions' standarduse 'c++17' for 'ISO C++ 2017 with amendments' standard

note: use 'gnu++17' for 'ISO C++ 2017 with amendments and GNU extensions' standardnote: 
use 'c++14' for 'ISO C++ 2014 with amendments' standard
note: note: use 'gnu++14' for 'ISO C++ 2014 with amendments and GNU extensions' standarduse 'c++20' for 'ISO C++ 2020 DIS' standard

note: note: use 'c++17' for 'ISO C++ 2017 with amendments' standarduse 'gnu++20' for 'ISO C++ 2020 DIS with GNU extensions' standard

note: note: use 'gnu++17' for 'ISO C++ 2017 with amendments and GNU extensions' standarduse 'c++2b' for 'Working draft for ISO C++ 2023 DIS' standard

note: note: use 'c++20' for 'ISO C++ 2020 DIS' standarduse 'gnu++2b' for 'Working draft for ISO C++ 2023 DIS with GNU extensions' standard

note: use 'gnu++20' for 'ISO C++ 2020 DIS with GNU extensions' standard
note: use 'c++2b' for 'Working draft for ISO C++ 2023 DIS' standard
note: use 'gnu++2b' for 'Working draft for ISO C++ 2023 DIS with GNU extensions' standard
```

**Comment by dimitre** [comment]
so maybe ```c++2b``` is the parameter you want to enable 'Working draft for ISO C++ 2023 DIS' standard

**Comment by danoli3** [comment]
Yeah 2B I used originally not sure why it changed to 23!

I think maybe when had some issues with windows using that

**Comment by dimitre** [comment]
it was hard to debug because platform templates were overriding with c++17
and in some cases when we use "vscode" and "osx" templates it copies config.make twice, so the last added template will count.

**Pull request merged**
