### PR TITLE
VS2022 FreeType Fix

### PR DESCRIPTION
**Pull request by danoli3**
Fixes VS2022 issues 
Links in Brotli for FreeType

### CODE REVIEW

**Comment by danoli3** [comment]
Might need to wait for the Apothecary result on bleeding actions though for this CI to work. Feel free to merge after then

**Comment by dimitre** [comment]
Thank you @danoli3 it solved the issue here in the project.
I've helped a friend today remotely via anydesk and bleeding libs script failed. 
we had to manually download and extract the bleeding zip files to make it work

**Comment by dimitre** [comment]
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - A fun▒▒o de revoga▒▒o n▒o p▒de verificar a revoga▒▒o do certificado.

**Comment by dimitre** [comment]
solved by adding the curl parameter ```  --ssl-no-revoke```

**Comment by danoli3** [comment]
I wouldnt put on --ssl-no-revoke, means someone in between is compromising the HTTPS. 
Likely the party has incorrect Date time for their system leading to failed encryption keys where are sensitive to real time EPOCH 
Update / Sync system time 

image

Might need to add brotli to download libs

**Pull request merged**
