### PR TITLE
PG custom templates

### PR DESCRIPTION
**Pull request by arturoc**
needed for this PR: https://github.com/openframeworks/projectGenerator/pull/26#issuecomment-136132617

### CODE REVIEW

**Comment by bilderbuchi** [comment]
what's the purpose of this additional "standard" directory level in the template directories?

**Comment by arturoc** [comment]
there can be other templates check the PG discussion, but mostly for osx for example, there's now a `nofmod` template which creates a project without fmod. there's some templates that are common to every platform which live in scripts/pgtemplates like gl3.2, gl3.3... but then every platform can have it's own templates too.

**Comment by ofZach** [comment]
@bilderbuchi see also this conversation https://github.com/openframeworks/projectGenerator/pull/26 I had made changes to the command line project to remove fmod, this makes a template out of those changes.  (I think it def. may be helpful down the line for different types of apps)

**Comment by bilderbuchi** [comment]
I see, thank you. I must have read over that part (the link arturo posted above pointed to a comment by mattfelsen, so that created some confusion).
While modifying the templates, might be good to look at #2791 again.

**Pull request merged**
