### PR TITLE
fix "Webaudio crashes if heap resizes"

### PR DESCRIPTION
**Pull request by Jonathhhan**
It does not crash if I put those two lines to the call back, so that the arrayBuffer is created every time a new sound file is loaded:

```
var inbufferArray = Module.HEAPF32.subarray(inbuffer>>2,(inbuffer>>2)+bufferSize*inputChannels);
var outbufferArray = Module.HEAPF32.subarray(outbuffer>>2,(outbuffer>>2)+bufferSize*outputChannels);
```
https://github.com/Jonathhhan/openFrameworks/blob/patch-release/addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js
https://github.com/openframeworks/openFrameworks/issues/6547

### CODE REVIEW

**Comment by bakercp** [comment]
There are quite a few changes in this PR and it is difficult to tell what you are proposing at a glance.  Can you clean up and submit a new PR?

**Comment by Jonathhhan** [comment]
I am sorry. I need to check out how the whole PR thing works. Until then it is perhaps more helpful if I just open an issue instead of a PR (if it is helpful at all). Just wanted to mention that it does not crash for me anymore with the change from above...

**Comment by bakercp** [comment]
Definitely appreciate it -- an issue would probably make more sense.

**Comment by Jonathhhan** [comment]
I already opened an issue before the PR, but then I thought the right way to submit would be a PR. Next time I know it better: https://github.com/openframeworks/openFrameworks/issues/6547

**Pull request closed without merging**
