### PR TITLE
Addon - ofxAssimp

### PR DESCRIPTION
**Pull request by NickHardeman**
Discussion about this add-on here: https://github.com/openframeworks/openFrameworks/discussions/7722

https://nickhardeman.com/temp/OFExamples/ofxAssimpExample2/

https://nickhardeman.com/temp/OFExamples/ofxAssimpBoneControlExample/

https://nickhardeman.com/temp/OFExamples/ofxAssimpAdvancedExample/

### CODE REVIEW

**Comment by NickHardeman** [comment]
> I think the file that puts the libraries in place is $ofw/scripts/dev/download_libs.sh

Thank you. :) As per @ofTheo 's suggestion, I ended up linking the libs to ofxAssimpModelLoader. Which does save duplicate libs in different directories.

**Comment by NickHardeman** [comment]
Yay!

**Comment by moebiussurfing** [comment]
Hey @NickHardeman,
I am getting these errors in Windows:
https://forum.openframeworks.cc/t/new-ofxassimp-add-on/42864/3?u=moebiussurfing

**Comment by NickHardeman** [comment]
@moebiussurfing can you open a new issue related to the Windows libs not getting linked properly for ofxAssimp?

**Comment by moebiussurfing** [comment]
https://github.com/openframeworks/openFrameworks/issues/7816

**Pull request merged**
