### PR TITLE
Added scroll feature in Addons Project Generator #2898

### PR DESCRIPTION
**Pull request by Daandelange**
This implements the same scroll code from the simple PG to the full PG.

### CODE REVIEW

**Comment by bilderbuchi** [comment]
ping @ofZach

**Comment by Daandelange** [comment]
(oops, sorry, don't care about that last 2 commits, I'm still discovering git...)

**Comment by arturoc** [comment]
merging this, the change seems correct and pretty minimal and PR it brings poco libs for armv6 which we need for 0.9. please open different branches another time. thanks!

**Comment by Daandelange** [comment]
I will, thanks a lot :)

**Comment by kylemcdonald** [comment]
hey @Daandelange are you interested in contributing more to the project generator? there's actually a lot of help needed, and it would be great to get another hand! if you're interested, sign up for http://dev.openframeworks.cc/listinfo.cgi/of-dev-openframeworks.cc and we can chat more.

**Pull request merged**
