### PR TITLE
Bugfix libs for 10.8

### PR DESCRIPTION
**Pull request by NickHardeman**
Recompiled the libs against the 10.8 SDK. Cairo and dependencies, freetype, assimp and opencv. 
Resolves: https://github.com/openframeworks/openFrameworks/issues/4481#issuecomment-151406337 and https://github.com/openframeworks/openFrameworks/issues/4412

### CODE REVIEW

**Comment by danoli3** [comment]
Nice! 0.9 close now!

**Comment by ofTheo** [comment]
@danoli3 does iOS feel pretty solid at the moment? or does it need some heavy testing?
were you going to wait to 0.9.1 to do AppleTV or try and get it in?

**Comment by danoli3** [comment]
All the examples work on the devices / simulators I've tested. 
I think it is good to go. Always could use more testing though :D! 

AppleTV and other future changes definitely 0.9.1 (we going to push iOS 7.0 minimum then as well). So be good to get 0.9.0 released, stable with support for iOS 5.1.1. 
Anyone wanting to keep up to date, like all the iOS openFrameworks users currently, will just keep up with master (post 0.9.0 release).

**Comment by ofTheo** [comment]
@danoli3 - thats awesome!
yes - think thats a solid plan. 

Also want to work on cleaning up the iOS keyboard and image picker code for for 0.9.1 
But will worry about that after 0.9.0 is out! :)

**Pull request merged**
