### PR TITLE
update text color to changing bg colour to ofxGui as well

### PR DESCRIPTION
**Pull request by sourya-sen**
Update to #6381 #6423 to update text colour based on the brightness of the background colour.

### CODE REVIEW

**Comment by sourya-sen** [comment]
@roymacdonald will you take a look?

**Comment by roymacdonald** [comment]
Ha. I see you figured that out as I was writing. :)

**Comment by sourya-sen** [comment]
@roymacdonald Yup! 

All Travis CI passes now and also tested with ofFloatColor with the following app. (apart from general ofColor usage).

```
//.h
    ofParameter<ofFloatColor> color;
    ofxPanel gui;

//.cpp
void ofApp::setup(){
    
    gui.setup();
    gui.add(color.set("Hello", 1.0));
}

//--------------------------------------------------------------
void ofApp::update(){
    
    color = fabs(sin(ofDegToRad(ofGetFrameNum()/1.0)));

}

//--------------------------------------------------------------
void ofApp::draw(){
    ofSetColor(ofFloatColor(color));
    ofDrawCircle(ofGetWidth()/2, ofGetHeight()/2, 100);
        
    gui.draw();
}
```

and it takes care of what @moebiussurfing brought up.

**Comment by roymacdonald** [comment]
Super! I tested it too and works. @arturoc @ofTheo please merge this.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
