### PR TITLE
fix macOS issue where fullscreen activation is broken after maximizing with green button

### PR DESCRIPTION
**Pull request by dimitre**
more description on this issue
closes - https://github.com/openframeworks/openFrameworks/issues/6895

### CODE REVIEW

**Comment by ofTheo** [comment]
cool! 
don't merge just yet - found some edge cases where this fails.

**Comment by ofTheo** [comment]
So for me this doesn't work going from green + fullscreen to window via setFullscreen(false)

(  using this code in ofApp ) 

```

//--------------------------------------------------------------
void ofApp::keyPressed(int key){
    if(key == 'f'){
        ofSetFullscreen(true);
    }else if( key == 'w'){
        ofSetFullscreen(false);
    }else if( key =='t' ){
        ofToggleFullscreen();
    }
}
``` 


An approach which accounts for all situations that seems to work well is: 

make the top of setFullscreen this instead ( removing it from lower down ) 

```
//------------------------------------------------------------
void ofAppGLFWWindow::setFullscreen(bool fullscreen){
	if (fullscreen){
		targetWindowMode = OF_FULLSCREEN;
	}else{
		targetWindowMode = OF_WINDOW;
	}
 
    #if defined(TARGET_OSX)
	NSWindow * cocoaWindow = glfwGetCocoaWindow(windowP);
 	if (([cocoaWindow styleMask] & NSWindowStyleMaskFullScreen) == NSWindowStyleMaskFullScreen) {
                settings.windowMode = OF_FULLSCREEN;
 		if (targetWindowMode == OF_WINDOW) {
                    targetWindowMode = OF_WINDOW;
                    [cocoaWindow toggleFullScreen:nil];
 		}
 	}
    #endif
```

and 

Add this to the end of: `void ofAppGLFWWindow::resize_cb(GLFWwindow* windowP_, int w, int h) {` 
```
     #if defined(TARGET_OSX)
	NSWindow * cocoaWindow = glfwGetCocoaWindow(windowP_);
 	if (([cocoaWindow styleMask] & NSWindowStyleMaskFullScreen) == NSWindowStyleMaskFullScreen) {
            instance->settings.windowMode = OF_FULLSCREEN;
 	}else{
            instance->settings.windowMode = OF_WINDOW;
        }
    #endif
```

This accounts for even getting out of fullscreen using the green + - by using the resize callback to figure out if we are still in Apple fullscreen mode or not. 

It also stays in Apple fullscreen if you call setFullscreen(true) which I think is the desired behavior

**Comment by dimitre** [comment]
Thanks @ofTheo! I'll re-run one test that fails often. tested here working great

**Comment by ofTheo** [comment]
Thanks @dimitre for finding this issue and getting it resolved!

**Pull request merged**
