### PR TITLE
Media Foundation Player for Windows

### PR DESCRIPTION
**Pull request by NickHardeman**
Adding a Media Foundation Video Player for Windows. 
It is possible to revert back to ofDirectShowPlayer by setting `#define OF_VIDEO_PLAYER_DIRECTSHOW`
Ability to play videos from urls. The first two in the image below are from disk and the rest are from urls.
Supports hardware accelerated and software decoding.

image

### CODE REVIEW

**Comment by NickHardeman** [comment]
How do I only include the openframeworks / video / ofMediaFoundationPlayer.h and .cpp in the VS and msys2 builds?

**Comment by dimitre** [comment]
I vote a big #ifdef like in ofDirectShowGrabber
#ifdef TARGET_WIN32
So it doesn't bother compiling in other OSes

**Comment by dimitre** [comment]
Here I'm discussing a more appropriate define to the platform windows.
https://github.com/openframeworks/openFrameworks/discussions/7450

**Comment by NickHardeman** [comment]
I have the following in ofVideoPlayer. But the code inside ofDirectShowPlayer and ofMediaFoundationPlayer is not wrapped in any defines. So some of the platforms are trying to compile it when they shouldn't. @dimitre are you suggesting to wrap the entirety of ofMediaFoundationPlayer in some defines to limit to _WIN32?
```
#ifdef OF_VIDEO_PLAYER_DIRECTSHOW
    #include "ofDirectShowPlayer.h"
    #define OF_VID_PLAYER_TYPE ofDirectShowPlayer
#endif

#if defined(OF_VIDEO_PLAYER_MEDIA_FOUNDATION) 
	#include "ofMediaFoundationPlayer.h"
	#define OF_VID_PLAYER_TYPE ofMediaFoundationPlayer
#endif
```

**Comment by dimitre** [comment]
Yes but maybe it is unneded. for some reason it is including in macOS and failing tests there

**Comment by NickHardeman** [comment]
@dimitre yeah not sure why it's included in OSX, I need to edit the make files for Emscripten, linux, etc.

**Comment by NickHardeman** [comment]
MSYS2 is failing because it can't seem to find the media foundation header / library. Not really sure how to fix it, I added the following to the make file.
https://github.com/openframeworks/openFrameworks/pull/7477/files#diff-80390bbb935e3f9db7650ca7262c5b3cc374cd72d66bed751df3c6b66a265b77R241
```
D:/a/openFrameworks/openFrameworks/libs/openFrameworks/video/ofMediaFoundationPlayer.h:3:10: fatal error: mfmediaengine.h: No such file or directory
[155](https://github.com/openframeworks/openFrameworks/actions/runs/4648013074/jobs/8225414915?pr=7477#step:5:156)
    3 | #include "mfmediaengine.h"
[156](https://github.com/openframeworks/openFrameworks/actions/runs/4648013074/jobs/8225414915?pr=7477#step:5:157)
      |          ^
```
Any ideas? pinging @dimitre @oxillo @ofTheo

**Comment by ofTheo** [comment]
hmm I see some of the MF files in mingw-w64-x86_64-headers package. 
can be installed by: `pacman -Su --noconfirm mingw-w64-x86_64-headers` 

for this PR maybe try adding: `mingw-w64-x86_64-headers` to: 
https://github.com/openframeworks/openFrameworks/blob/master/scripts/msys2/install_dependencies.sh#L42

**Comment by ofTheo** [comment]
One other thing in the logs I see: 

```
warning: ignoring '#pragma include_alias ' [-Wunknown-pragmas]
#pragma include_alias( "dxtrans.h", "qedit.h" )
```

So maybe trying a 
`#include <dxtrans.h>`

might also be needed?

**Comment by ofTheo** [comment]
tried both of the above and no luck. 
I see mfapi.h but not mfmediaengine.h - I wonder if the API is too new for the version of Mingw64. 

Definitely might need some insight from @oxillo on this one.

**Comment by ofTheo** [comment]
maybe relevant?: 
https://gitlab.winehq.org/wine/wine/-/blob/master/dlls/mfmediaengine/Makefile.in#L2

**Comment by NickHardeman** [comment]
> One other thing in the logs I see:
> 
> ```
> warning: ignoring '#pragma include_alias ' [-Wunknown-pragmas]
> #pragma include_alias( "dxtrans.h", "qedit.h" )
> ```
> 
> So maybe trying a `#include <dxtrans.h>`
> 
> might also be needed?

This one is in ofDirectShowPlayer.cpp. 
https://github.com/openframeworks/openFrameworks/blob/d7da2ebfcc1e8847882723f485dc6e4788ce3388/libs/openFrameworks/video/ofDirectShowPlayer.cpp#L17

**Comment by ofTheo** [comment]
good reference too: 
https://gitlab.winehq.org/wine/wine/-/blob/2d525783875372cfa5e35b5b80a82c45f0f3306e/include/mfmediaengine.idl

**Comment by dimitre** [comment]
Great work @NickHardeman ! it seems to be passing all tests ⚙️🔨

**Comment by ofTheo** [comment]
yeah - going to merge this so we can test on VS at least. 
it def doesn't work on msys2 / mingw64 - everything I have been reading points to it needing the Windows SDK to compile which is annoying as I was hoping we could drop k-lite / directshow all together.

**Comment by NickHardeman** [comment]
> Great work @NickHardeman ! it seems to be passing all tests ⚙️🔨

Thanks! Though I lost the battle with msys2 and just reverted back to DirectShowPlayer 😬 Works great in VS though

**Pull request merged**
