### PR TITLE
Fix missing pg commit.

### PR DESCRIPTION
**Pull request by bakercp**
Points the submodule to the latest commit.

### CODE REVIEW

**Comment by bakercp** [comment]
@arturoc @ofTheo

**Comment by arturoc** [comment]
i think @ofTheo just forgot to push the PG repo, let's wait for him to fix it.

**Comment by bakercp** [comment]
@memo @ofTheo ping.

**Comment by arturoc** [comment]
i'm going to merge this until @ofTheo uploads his changes otherwise the repo is broken right now

**Comment by ofTheo** [comment]
arggggg - I hate submodules so much!
If we want to move PG submodule into the main repo. 
Can I simply do that - or do we want to try and preserve history?

I want to shoot myself everytime I look at a submodule :(

**Comment by ofZach** [comment]
hating submodules in the first stage on the path to eventual enlightenment... :)     once you get a workflow down they are super handy

I'm sure there's a way to merge it in with it's history, see for example: 
http://stackoverflow.com/questions/1759587/un-submodule-a-git-submodule

**Comment by memo** [comment]
@ofTheo if you don't like submodules, don't look here https://github.com/memo/ofxmsalibs :)
Really helpful when I want to pull down all of my addons onto a new computer or folder (though I still don't have the workflow nailed 100%)

**Comment by ofZach** [comment]
or if you are a teacher and you want to have a way for accessing all your students work / repos easily: 
https://github.com/ofZach/algo2012_students

**Pull request merged**
