### PR TITLE
fix area lights for programmable renderer

### LINKED ISSUE #4495: shader error with programmable renderer in AreaLightExample on Windows / VS
It seems like it doesn't like the:
#define MAX_LIGHTS 
#define USE_TEXTURE

The shader doesn't compile, but the app runs. 
Going to paste the print out.

### PR DESCRIPTION
**Pull request by tgfrerer**
Because the old implementation of `ofMaterial.cpp` mixed the `STRINGIFY`preprocessor macro with GLSL preprocessor directives, the behaviour of the c preprocessor for this file was undefined.

This lead to strange GLSL code in VS2015 builds, and `ofMaterial` may have been considered broken on this platform(s).

To close #4495, this PR suggests & implements the following:

* Using **Raw String Literals** for inline GLSL code instead of `STRINGIFY`. This allows us to
  concat different cpp constants based on the cpp build environment. Raw String Literals are a C++11 feature. See: http://en.cppreference.com/w/cpp/language/string_literal

* Anything within Raw String Literals is not interpreted by the preprocessor, also escapes are not scanned. It is literally a literal.

Tested on XCode 7.1 / clang 7.0.0 and VS2015; Raw string literals are advertised as supported by GCC from 4.5 onwards. https://gcc.gnu.org/projects/cxx0x.html

### CODE REVIEW

**Comment by ofTheo** [comment]
Nice fix! 
Just tested this on Windows 8 and it works perfectly. 
Also tested on OS X 10.9 with Xcode and it works fine too. 

@danoli3 / @julapy - could you check on iOS?

**Comment by arturoc** [comment]
yes much better than the stringify macro. btw, TARGET_OPENGLES is also defined in shaders so there's no need to put that out of the shader string.

**Comment by danoli3** [comment]
iOS Working with above. Tested iosES2ShaderExample

**Comment by tgfrerer** [comment]
Thanks @danoli3! 
@arturoc - makes sense =) I've removed the redundant check.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
