### PR TITLE
ios sound player to allow bluetooth audio

### PR DESCRIPTION
**Pull request by sadmb**
Here's a pull request to allow your iOS app to use a bluetooth headphone.

### CODE REVIEW

**Comment by ofTheo** [comment]
@sadmb I'm pretty sure you are seeing the Github Actions errors, but just incase it seems to be erring on this PR. 

eg: 

```
/Users/runner/work/openFrameworks/openFrameworks/addons/ofxiOS/src/sound/AVSoundPlayer.m:53:52: error: 'AVAudioSessionCategoryOptionAllowBluetooth' is unavailable: not available on tvOS
2164
                                                   AVAudioSessionCategoryOptionAllowBluetooth |
2165
```

**Comment by sadmb** [comment]
@ofTheo Thanks! Yes, I know it is not available on tvOS, can you let me know how to include ofConstants.h on AVSoundPlayer.m?

I've found it happened because it didn't include definition of TARGET_OF_TVOS, but I got an error when I try to include ofConstants.h because it's objective-c style file and got an error like this.

```
../libs/openFrameworks/utils/ofConstants.h:277:10: 'cstdio' file not found
```

**Comment by sadmb** [comment]
Maybe I have to create C++ style class for solve this?

**Comment by sadmb** [comment]
Ah, I've found TargetConditionals.h is alternative file. I'll try this.

**Comment by sadmb** [comment]
@ofTheo mmm... I don't know why it happens...
Can you tell me what is wrong here?

```
#include <TargetConditionals.h>
....

#if defined (TARGET_OF_OS_TV) || defined (TARGET_OF_OS_WATCH)
        if(![audioSession setCategory:playbackCategory
                                       withOptions:(AVAudioSessionCategoryOptionMixWithOthers)
                                error:&err]) { err = nil; }
#else
        if(![audioSession setCategory:playbackCategory
             						  withOptions:(AVAudioSessionCategoryOptionMixWithOthers |
                                                   AVAudioSessionCategoryOptionAllowAirPlay |
                                                   AVAudioSessionCategoryOptionAllowBluetooth |
                                                   AVAudioSessionCategoryOptionAllowBluetoothA2DP)
                                        error:&err]) { err = nil; }
#endif
```

**Comment by 2bbb** [comment]
@sadmb 
AVSoundaPlayer.h and AVSoundPlayer.mm doesn't include ofConstants.h, only TargetConditionals.h is included.
.
and, TARGET_OF_OS_TV  and TARGET_OF_OS_WATCH are defined on ofConstants.h.

**Comment by 2bbb** [comment]
@sadmb 

so, maybe you need to use TARGET_OS_WATCH and TARGET_OS_TV directly? like:

```
#if TARGET_OS_WATCH || TARGET_OS_TV
...
#endif
```

**Comment by sadmb** [comment]
@2bbb Ahh, got it.
I was going to use TARGET_OS_TV... maybe OF version is TARGET_OF_TVOS instead of TARGET_OF_OS_TV...
I'll try.
Thanks!

**Comment by ofTheo** [comment]
Thanks @sadmb @2bbb !!

**Pull request merged**
