### PR TITLE
ofxAndroidUtils - added helper method ofCallStaticVoidJavaMethod

### PR DESCRIPTION
**Pull request by tallavi**
It allows me to call static void methods in JAVA with only one line. 

I use it in my new ofxGPS cross platform plugin.

### CODE REVIEW

**Comment by tallavi** [comment]
Right you are, @arturoc.

Fixed + I deleted all local refs I'm creating, since they are not released automatically when using JNI from a native worker thread (which I do). Tested, all good.

**Comment by arturoc** [comment]
it won't merge cleanly any more with master, can you rebase it? i think it must be the changes in the android window

**Comment by tallavi** [comment]
Yeah, just two lines that were deleted in master in the exact same place. I merged master into this branch and resolved the simple conflict. It says above: "this branch has failed checks, but can be merged". Is it ok?

**Comment by arturoc** [comment]
yes it's fine not sure why there's an instance of travis checking our repo but it's failing so it shows an error but the merge is correct. thanks!

**Comment by tallavi** [comment]
Thank you!

**Comment by kylemcdonald** [comment]
the travis stuff is a work in progress from @halfdanj. i'll email him directly since this is the second time it's tripped someone up.

**Pull request merged**
