### PR TITLE
ofxSVG to ofxSvg

### PR DESCRIPTION
**Pull request by dimitre**
according to https://github.com/openframeworks/openFrameworks/issues/6866#issuecomment-1081904974

### CODE REVIEW

**Comment by dimitre** [comment]
Now I've updated the allAddonsExample and it is passing all checks

**Comment by dimitre** [comment]
Hey @ofZach what is your opinion on this one?

**Comment by ofTheo** [comment]
Hmm - to avoid breaking old projects / addons ( I know @NickHardeman's ofxSvgLoader uses ofxSVG ), should we add a typedef at the bottom of the class? 

`typedef ofxSvg ofxSVG;`

**Comment by dimitre** [comment]
Good idea!

**Comment by dimitre** [comment]
Done and tested here, like:
```
    ofxSVG svg;
    ofxSvg svg2;    
```
compiles and runs well.

**Pull request merged**
