### PR TITLE
iOS header includes cleanup

### PR DESCRIPTION
**Pull request by julapy**
ofxiOS has been plagued by messy and inconsistent header includes,
and creating a spider web of cross-referencing classes.
its been bugging me for ages!

this PR addresses this issue,
making sure that each ofxiOS class (and examples) only include classes that they need.

previously it was common to see `ofMain.h` being included everywhere,
now more specific core classes like `ofConstants.h` or `ofBaseTypes.h` are included when needed.

also added missing `pragma once` statements, for consistency.

have gone through and tested with all ios examples and all looking good...

### CODE REVIEW

**Comment by danoli3** [comment]
Dude this is huge! Nice work! I'll base any tvOS stuff off this one.

**Comment by julapy** [comment]
@danoli3, yeah i think you'll need to create your own ofxtvOS.h which includes all the tvOS classes, and that will include references to ofxtvOSAppDelegate.h, etc.
but yeah if you follow the same structure, it will save you including classes that you don't need.

**Comment by julapy** [comment]
btw, this PR is just a internal ofxiOS refactor which won't have any effect on external code afaik.
would like to merge this if theres no objections...

**Comment by danoli3** [comment]
:+1: Better for oF 9.0 anyway!

**Comment by bilderbuchi** [comment]
I'd rather prefer if we'd concentrate on knocking out the rest of the [0.9.0 issues](https://github.com/openframeworks/openFrameworks/milestones/0.9.0) first, to get a release out the door.

**Comment by arturoc** [comment]
@bilderbuchi getting iOS completely ironed out was one of the remaining issues even if it's not explicitly said in an issue

@julapy if you consider this is stable feel free to merge it

**Comment by bilderbuchi** [comment]
> getting iOS completely ironed out was one of the remaining issues

what does that mean? there are [11 labeled iOS bugs](https://github.com/openframeworks/openFrameworks/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3AiOS+label%3Abug+) in the tracker, are you saying we want to fix them all for 0.9.0?

**Comment by arturoc** [comment]
no, no, but iOS wasn't ready when we did the RC1. i'm not sure what is missing but this seems to clean the addon quite a bit, and since it's done it's probably better to merge it than leave it for later since it's the kind of change that will bit rot easily.

**Comment by bilderbuchi** [comment]
"clean the addon" yes, but it's not working towards a fix for a (critical) bug, which is what would be desirable to get the last push together to fix the last O(10) outstanding bugs in 0.9. We have been at ~10 open bugs for a long time and I don't get the feeling we made much progress lately.

In any case, I'm not opposed to merging, as the work is already done, I'd only love a bit more focus on the 0.9-blocking bugs. :-) :relaxed:

**Comment by arturoc** [comment]
:)

**Comment by julapy** [comment]
yeah agree, its just easy to get side tracked sometimes :)
in any case, this PR has been tested with all ios examples and theres no issues.
so i'll merge this now and next on the list will be those remaining ios bugs.

**Pull request merged**
