### PR TITLE
Apothecary: OpenCv 2.4.9

### PR DESCRIPTION
**Pull request by ofTheo**
Static libs, headers and apothecary formulas for architectures included:
- [x] OSX FAT (32 bit w/ libstdc++ and 64 bit w/ libc++)
- [x] iOS FAT (armv7, armv7s, arm64, i386, x86_64 all with libc++)
- [x] Linux (32 bit)
- [x] Linux (64 bit)
- [x] Linux Armv6l
- [x] Linux Armv7l
- [x] Android - armeabi (@arturoc ?) 
- [x] Android - armeabi-v7a (@arturoc ?)
- [x] Android - x86 (@arturoc ?)
- [ ] VS (?)
- [ ] win_cb (?)

----

Creates a single FAT opencv.a lib with O3 optimization and 64bit libc++ and 32bit libstdc++

don't merge yet. 
still to do. 

- [ ] don't use build root - use build folder. 
- [x] find a better way to keep _buildroot folder clean ( right now lipo will suck up any lib in _buildroot/lib/)
- [x] remove libtiff lib 

ping @pizthewiz 

changes
- removed OpenCL as it was causing errors 
- removed some other libs not needed ( CUDA etc ) 
- lipo for loop wasn't working - fixed. 
- error suppression for lipo incase lib is already FAT 
- libtool into a single opencv.a 

formula based off of @pizthewiz gist - addresses #3039

### CODE REVIEW

**Comment by ofTheo** [comment]
closed for #3635

**Comment by arturoc** [comment]
i'm reopening this since it seems the changes for android weren't included in the new PR. @ofTheo can you take a look and merge this with your version?

**Comment by ofTheo** [comment]
Thats fine - sorry I missed those commits. 
The other PR I merged was just for the apothecary formula - I was going to wait before bringing in the libs. But happy if you think we should just get all the libs in now!!

**Comment by bilderbuchi** [comment]
just leaving a note, this probably solves #2081

**Comment by kylemcdonald** [comment]
with everything but windows solved, should we close this in favor of a windows-specific checklist issue?

**Comment by ofTheo** [comment]
yup def should close. thanks!

**Pull request closed without merging**
