### PR TITLE
Emscripten 3.1.65 fix

### PR DESCRIPTION
**Pull request by Jonathhhan**
Not sure, if this is backward compatible, but it works wit the current Emscripten version.
Also, the apothecary libs need to be rebuild with the current Emscripten version.

### CODE REVIEW

**Comment by danoli3** [comment]
You were able to build and test in browser this working ?

**Comment by Jonathhhan** [comment]
@danoli3 actually I need to test it a little more. A lot of errors are resolved, but there is an issue with emrun. Similar to this one: https://github.com/emscripten-core/emscripten/issues/14128 which was not there before. But it should work, if uploaded to a webserver (did not test that, yet).

**Comment by danoli3** [comment]
Please test, I might also, as I've been chasing my tail to find the right settings to work in Site. 

I was crashing on getGLError before that using just updated EM_BOOL stuff as above, but ended up finding a MAIN function in the old freeimage library on the old version so thats now fixed 
https://github.com/openframeworks/openFrameworks/pull/8056

Anyways I believe the old binding ways maybe causing something to break bad. I opted to just port us to GLFW and have working code to fix up but multi-window stuff was really, exciting 

I'm happy to merge this first on old libs if it's working as is with, as EM_SDK it kinda forces latest in most example scripts to download it or run it. 

I also was looking at your other PR's with the audio stuff, lets get those in once isolate issues with workers, might be a good idea to just create template project makes for each unique feature like that, as it does become a core change requirement... however we could define somewhere, not exactly sure how the ```config.emscripten.default.mk```

**Comment by danoli3** [comment]
@Jonathhhan how did you go any working test? I might checkout your PR and see myself

**Comment by Jonathhhan** [comment]
I am sorry. I am away from my computer for a good week, and did not manage to test it before. Will definitely come back to this. Until then it is still possible to use older Emscripten versions...

**Comment by Jonathhhan** [comment]
I am sorry. I am away from my computer for a good week now, and did not manage to test it before. Will definitely come back to this. Until then it is still possible to use older Emscripten versions...

**Pull request merged**
