### PR TITLE
ofAppRunner unneeded .h files

### PR DESCRIPTION
**Pull request by dimitre**
this is a draft to see how it builds in all systems. 
I suspect there are some unneded .h files here, like ofURLFileLoader.h and maybe others.

### CODE REVIEW

**Comment by dimitre** [comment]
it seems to build well in all platforms. build-vs didn't complete but it seems it is another issue there

**Comment by ofTheo** [comment]
yeah I need to update the CI as they dropped the older Windows build image. 
will work on getting that fixed. then if it passes all the checks you could remove the commented includes. Thanks!

**Comment by dimitre** [comment]
Great, all checks have passed and I removed the commented out includes

**Comment by ofTheo** [comment]
@dimitre - there is a merge conflict on this one, since another PR merge :)

**Comment by dimitre** [comment]
Nice, solved conflict and passed all checks. Merging this one

**Pull request merged**
