### PR TITLE
FreeImage compiled on 10.8 for osx.

### LINKED ISSUE #4385: Freeimage 3.17.0 'Undefined symbols for architecture x86_64'
On latest master 0.9.0 Xcode 4.x 10.8 SDK I can't compile x64 projects because of:

>Undefined symbols for architecture x86_64:
  "___exp10", referenced from:
      _opj_tcd_rateallocate in freeimage.a(tcd.o-x86_64)
ld: symbol(s) not found for architecture x86_64

Recompiling a universal 32/64bit lib with c++11 support against the 10.8 SDK fixes the problem on my machine. 

@danoli3 maybe the build in #3936 and mentioned in #3925 done against 10.9, 10.10 SDK?

Anyway, I've been out of the game for a while so maybe I just checked out the wrong 0.9.0 or perhaps we dropped support for 10.8 - I'm not sure - but in any case I had to recompile :(

### PR DESCRIPTION
**Pull request by bakercp**
Fixes #4385

### CODE REVIEW

**Comment by bakercp** [comment]
Not sure why permissions changed on the text files.  Just ran the apothecary script and committed.

**Comment by bilderbuchi** [comment]
one possibility is if the files are on an NTFS partition you have mounted in a non-windows with the mounting bits such that all files are mounted executable (I experienced this previously, basically you have the options to be able to execute all or none of them). It's kinda remote, but that's all i can come up with. Would be great to correct this before merging.

**Comment by geeta-saraswat** [comment]
@bakercp  hey I am trying to build free image with SDK MAC OS 10.7 and and 10.8 ,  and my OS is 10.10 yesomite. 
seems like changing the SDK path alone in makefile is not suffice , as I am getting all that linking error 
libtool: object: ./Source/FreeImage/BitmapAccess.o-x86_64 malformed object (unknown load command 1)
libtool: object: ./Source/FreeImage/ColorLookup.o-x86_64 malformed object (unknown load command 1)
libtool: object: ./Source/FreeImage/FreeImage.o-x86_64 malformed object (unknown load command 1)
libtool: object: ./Source/FreeImage/FreeImageIO.o-x86_64 malformed object (unknown load command 1)
libtool: object: ./Source/FreeImage/GetType.o-x86_64 malformed object (unknown load command 1)
libtool: object: ./Source/FreeImage/MemoryIO.o-x86_64 malformed object (unknown load command 1)

Could you ping me the makefile you used to build free image with SDK 10.8

**Comment by bakercp** [comment]
I just used the apothecary script.  The apothecary read me in the
openframeworks/scripts/apothecary directory for instructions.

**Pull request closed without merging**
