### PR TITLE
ofFileUtils: low_level_docs & api updates

### PR DESCRIPTION
**Pull request by danomatika**
PR for fixes related to #4951 & #4931

I would have done this sooner but we decided to head to the mountains last weekend. I think everyone should :)

### CODE REVIEW

**Comment by arturoc** [comment]
can you deprecate setReadOnly with a message asking to use setWritable instead of completely remove it?

also if you can change the test that is currently failing to use the new method instead?

**Comment by danomatika** [comment]
sure thing

**Comment by danomatika** [comment]
Updated.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
