### PR TITLE
Apothecary - Formula Updates

### PR DESCRIPTION
**Pull request by danoli3**
Formula Updates
----------

- Features Formula for changes to support tvOS
- Fixes for OpenCV script (https://github.com/openframeworks/openFrameworks/issues/4578 / https://github.com/openframeworks/openFrameworks/issues/4576 )
- Fixes for LANG_C issues when using sed
- Fixes for timeout on travis
- OpenSSL updated to 1.0.2d
- Poco Updated to 1.6.2
- Fixed using checkout issues.
- Implemented https://github.com/openframeworks/openFrameworks/issues/4451 in some of the scripts

---

# Build Status:

| Lib                             | OSX |  iOS |  tvOS | 
|---------------------------------|-----|-------|---------------------|
| FreeImage                       |[Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=freeimage-osx) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=freeimage-ios) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=freeimage-tvos) |
| FreeType                        |[Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=freetype-osx) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=freetype-ios) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=freetype-tvos) |
| tess2                           | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=tess2-osx) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=tess2-ios) |  [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=tess2-tvos)|
| poco                            |[Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=poco-osx) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=poco-ios) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=poco-tvos) |
| openssl                         | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=openssl-osx) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=openssl-ios) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=openssl-tvos) |
| ofxAssimpModelLoader -> assimp  |[Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=assimp-osx) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=assimp-ios) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=assimp-tvos) |
| ofxOpenCV -> opencv             | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=opencv-osx) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=opencv-ios) | N/A |
| glew                            | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=glew-osx)| N/A | N/A |
| glfw                            | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=glfw-osx) | N/A | N/A |
| cairo                          | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=cairo-osx) |  N/A  | N/A |
| kiss                            | N/A  |  N/A | N/A |
| rtAudio                         | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=rtaudio-osx)  |  N/A | N/A |
| Boost 1.58.0 FileSystem/System  |  [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=boost-osx) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=boost-ios)  | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=boost-tvos) |
| URI  |  [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=uri-osx) | [Build Status](https://travis-ci.org/danoli3/apothecary-den?branch=uri-ios)  | N/A |

----------------------------------

### CODE REVIEW

**Comment by danoli3** [comment]
@arturoc @ofTheo Is this good to merge to master now. It has some fixes for 0.9.1 as well (in regards to opencv). 

The other scripts, such as openssl which have been updated, don't have to be run for 0.9.1, but good to have those changes in master before the tvOS merger, so we can do other platforms at the same time.

**Comment by r9y9** [comment]
@danoli3 I'm sorry if you are already working on it or if I'm wrongs, but it seems like there is a commit that reverts some of recent changes from me (see #4579, #4577). Could you take a look if this is a correct change when you have time?

**Comment by danoli3** [comment]
@r9y9 Hey, could you tag the lines that are missing here: I see all the EXR changes. Is it just the cmakelists file?
https://github.com/danoli3/openFrameworks/blob/f730e1410521c4d78e3d2521fbda7e7e4aed12ef/addons/ofxOpenCv/scripts/formulas/opencv.sh

**Comment by r9y9** [comment]
@danoli3 
- https://github.com/danoli3/openFrameworks/blob/f730e1410521c4d78e3d2521fbda7e7e4aed12ef/addons/ofxOpenCv/scripts/formulas/opencv.sh#L100 misssing `-a` and `2>&1`. ref #4577 
- https://github.com/danoli3/openFrameworks/blob/f730e1410521c4d78e3d2521fbda7e7e4aed12ef/addons/ofxOpenCv/scripts/formulas/opencv.sh#L105 misssing `-a` and `2>&1`
- https://github.com/danoli3/openFrameworks/blob/f730e1410521c4d78e3d2521fbda7e7e4aed12ef/addons/ofxOpenCv/scripts/formulas/opencv.sh#L115 misssing `-a` and `2>&1`
- https://github.com/danoli3/openFrameworks/blob/f730e1410521c4d78e3d2521fbda7e7e4aed12ef/addons/ofxOpenCv/scripts/formulas/opencv.sh#L54 this is incorrect. ref: #4579 

I'm not saying about openexr...

**Comment by danoli3** [comment]
@r9y9 Awesome yeah got it! Thanks, must have failed to merge those lines for some reason!

**Comment by r9y9** [comment]
@danoli3 Thanks!

**Pull request merged**
